### PR TITLE
fix(integration): Product ordered by variants prices

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
Ensure that there is no randomness in the data to validate the ordering

### CODE REVIEW

**Review by olivermrbl — APPROVED** [review]
LGTM, we couldn't just change the seeded price amount?

**Comment by adrien2p** [comment]
> LGTM, we couldn't just change the seeded price amount?

didn't want to impact all the other suite that might depends on it. since it is mainly related to those specific tests, it seems more appropriate to have action in those tests

**Comment by olivermrbl** [comment]
Damn, looks like it did impact other tests 😅

**Comment by adrien2p** [comment]
> Damn, looks like it did impact other tests 😅

I will have a look 😂

**Review by olivermrbl — APPROVED** [review]

**Pull request merged**
