### PR TITLE
feat(medusa-react): Upgrade react-query and clean up dependencies

### PR DESCRIPTION
**Pull request by kasperkristensen**
**What**
- Updates the required peer dependency version of `react-query` -> `@tanstack/react-query` (v4)
- Fixes a wrong direct dependency on `react-query` as it should only be a `peer- and devDependency`.

**Why**
- Due to `react-query` being both a direct and peer dependency it could resolve in multiple versions of `react-query` being bundled in the production build of users' projects. This results in the error `No QueryClient set, use QueryClientProvider to set one` being thrown.
- Upgrading to the latest version of `react-query` plays better with Vite, and due to that the upgrade has been included. This will require users to update their version of `react-query` -> `@tanstack/react-query@^4` to continue using `medusa-react`.

Resolves CORE-972

### CODE REVIEW

**Comment by shahednasser** [comment]
@olivermrbl I'll add it to the open PR

**Comment by olivermrbl** [comment]
LGTM but will keep it out of upcoming release to not introduce unnecessary required actions for v1.7.3

**Review by olivermrbl — APPROVED** [review]
LGTM!

**Pull request merged**
