### PR TITLE
fix(medusa-oas-cli): Add separator after tmpdir base

### PR DESCRIPTION
**Pull request by pevey**
Fixes build issue https://github.com/medusajs/medusa/issues/3919

### CODE REVIEW

**Comment by pevey** [comment]
@olivermrbl I'm not at all sure why some integration tests are failing.  They pass on my local machine.  Is there a way to trigger the CI to try the tests again?

If they really are failing, it must be that the Github CI ubuntu does not play nice with path.sep ?

**Comment by olivermrbl** [comment]
@pevey – have given the CI another go. Let's see :)

**Comment by pevey** [comment]
Looks like all the tests are passing now.  Must have been gremlins.

**Review by olivermrbl — APPROVED** [review]
Great, thanks @pevey !

**Pull request merged**
