### PR TITLE
Feat/async load

### PR DESCRIPTION
**Pull request by SGFGOV**
Currently, medusa supports only synchronously loading configuration.
In several situations, one might need to load the config file asynchronously, such as after reading settings from an external store or key store.
This PR Addresses that issue. Fixes merge issues in #3130 #1742

### CODE REVIEW

**Comment by adrien2p** [comment]
@SGFGOV you have done the same in the extender package, it has come with some unexpected issues and I suggest you look at the changes in the extender and not apply the same issues here. Basically, all functions are resolved and stored as the prop's value. The problem is that it also resolve function that is not meant to be executed and stored, for example in some plugins you can provide a custom function handler that will be consumed by the plugin and is not supposed to be executed by the loader, and then the result store as the value of the prop. Hope it makes sense and in the meantime you can have a look at what @dwene and I have done.

**Comment by SGFGOV** [comment]
> @SGFGOV you have done the same in the extender package, it has come with some unexpected issues and I suggest you look at the changes in the extender and not apply the same issues here. Basically, all functions are resolved and stored as the prop's value. The problem is that it also resolve function that is not meant to be executed and stored, for example in some plugins you can provide a custom function handler that will be consumed by the plugin and is not supposed to be executed by the loader, and then the result store as the value of the prop. Hope it makes sense and in the meantime you can have a look at what @dwene and I have done.

thanks.. let me have a look at it.. I am using this in my current environment without a hitch so thought it was good as is

**Comment by adrien2p** [comment]
It is only good in your case indeed and people that do not use any configuration where they need to pass a function as the value of the property. For example, if you use the auth plugin, you can pass a custom function as an option. This function is meant to be consumed by the underlying plugins. With your implementation, the option being a function, the loader execute it and store the result on the property even though it should not. Therefore, the option become void instead of being a function as expected.

**Comment by SGFGOV** [comment]
yes, but I too use the auth plugin with the function call back.. however the reason it worked for me was that I faced this plugin issue very early on and worked around the issue by modifying the medusa-config.js to resolve the plugin settings only after the project config has been resolved ..this was necessary as I am configuring the plugins based on information read asynchronously. both approaches work..

**Comment by adrien2p** [comment]
Yes indeed, the most disturbing is that it forces all the users to change the way their build their config, which should be avoided. So I suggest you to have a look to the changes I ve told you about 💪

**Comment by adrien2p** [comment]
Yes indeed, the most disturbing is that it forces all the users to change the way their build their config, which should be avoided. So I suggest you to have a look to the changes I ve told you about 💪

**Comment by SGFGOV** [comment]
closing due to merge issue

**Comment by riqwan** [comment]
Hey, thanks for the PR! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket.

**Pull request closed without merging**
