### PR TITLE
feat(medusa-js): Bundle package using Rollup

### PR DESCRIPTION
**Pull request by kasperkristensen**
**What**
- Adds Rollup to `medusa-js` and use it to build the package.
- Updates the version of `axios` to remove circular dependency warning, which helps speed up the build time.

**Why**
- The current approach to building the project resulted in errors when used in projects that use the latest versions of "modern" build tools such as Vite, esbuild, etc.

Resolves CORE-971

### CODE REVIEW

**Review by fPolic — APPROVED** [review]
LGTM!
We might consider adding `rollup-plugin-peer-deps-external` to plugins so we don't end up with a peer dep in the bundle, wdyt?

**Review by srindom — APPROVED** [review]
LGTM!

**Comment by srindom** [comment]
Looks like there are some build issues in the pipeline

**Pull request merged**
