### PR TITLE
feat(admin-ui): add Kannada translation

### PR DESCRIPTION
**Pull request by vineetjk**
- Kannada translation for Admin UI

Resolves: https://github.com/medusajs/medusa/issues/5346

### CODE REVIEW

**Comment by vineetjk** [comment]
@variablevic could you please check this PR

**Review by VariableVic — CHANGES_REQUESTED** [review]
Please add your language to the `supportedLanguages` array in `packages/admin-ui/ui/src/i18n/index.ts`

**Comment by vineetjk** [comment]
Hi @VariableVic, I have added kn to supportedLanguages array.

**Review by VariableVic — APPROVED** [review]
LGTM! Nice work

**Comment by vineetjk** [comment]
I have resolved merge conflicts, I hope its ready to merge now.

**Comment by olivermrbl** [comment]
We are reworking how translations in admin are handled, so this will not be merged. However, we appreciate the contribution. Keep an eye out for our upcoming releases to know more about this update, and if you are still interested, we'd love to see a new PR then :)

**Pull request closed without merging**
