### PR TITLE
Add RTL Support and Fix UI Issues in RTL for Admin UI V1.x

### PR DESCRIPTION
**Pull request by MEClouds**
#### Overview
This pull request introduces RTL (Right-to-Left) support and addresses various UI issues when using RTL layout in the Medusa Admin UI v1.x. It resolves issue #8086 

#### Changes

1. **Direction Based on Language**:
    - Implemented direction changes based on the language direction (RTL/LTR) in the `i18n` configuration.
    - The direction of the application now dynamically adjusts based on the selected language.

2. **Tailwind Styles Adaptation**:
    - Utilized Tailwind CSS classes that support both RTL and LTR directions without issues.
    - Converted the following classes:
        - `pl` to `ps`
        - `pr` to `pe`
        - `ml` to `ms`
        - `mr` to `me`
        - `left` to `start`
        - `right` to `end`
        - And other similar adjustments
    - Ensured consistent and correct styling across different directional layouts.

3. **Component-Specific Direction Properties**:
    - Added `dir` properties to components that did not respond to the root direction setting, such as the dropdown menu.
    - Ensured these components display correctly in both RTL and LTR modes.

4. **Styling Fixes**:
    - Fixed styling issues in tanstack/react-table to ensure proper display and functionality in RTL.
    - Addressed styling issues with switch and radio button components to ensure consistent behavior and appearance in RTL.

#### Additional Notes
- Ensured that all changes are backward compatible and do not affect the LTR layout.
- Tested the changes extensively to ensure there are no regressions or new issues introduced.
- Please review the changes and provide feedback or suggestions for further improvements.

Thank you for your attention to this pull request. I look forward to your feedback and hope these changes improve the usability of Medusa Admin-UI for RTL languages.

### CODE REVIEW

**Comment by MEClouds** [comment]
@kasperkristensen

**Comment by kasperkristensen** [comment]
Thanks for the PR @MEClouds. We are quite busy with working on V2 at the moment, but I will give this a review in the coming weeks.

**Comment by alisafavi** [comment]
How can use this customization ?
Should I publish it in to npm ?

**Comment by alsherif-khalaf** [comment]
I think this solution is easy

**Comment by SalahAdDin** [comment]
> I think this solution is easy

I guess it won't be fixed for the 1.x version.

**Pull request closed without merging**
