### PR TITLE
feat(medusa): Add `metadata` to Product Category

### PR DESCRIPTION
**Pull request by bqst**
Resolves: #5598 

# What

This PR introduces the addition of `metadata` (JSONB) attributes in the `Product Category` feature. Previously, `metadata` attributes were available for `Product Collections` and `Product Tags`, but not for categories. This update adds consistent metadata functionality across various entities within the platform.

# Why

It allows for the storage of additional, custom data associated with categories, aligning the capabilities of Product Categories with that of product collections and tags. This change is relevant for developers and users who require extended information tied to each category for custom implementations.

# How 

Adding the `JSONB` field, exactly the same as the other metadata implementations.

# Testing

- Tested by running the migrations
- API insert / update / read

### CODE REVIEW

**Review by olivermrbl — COMMENTED** [review]
LGTM, @riqwan could you review this one please? 🙏

**Comment by luluhoc** [comment]
Please merge this!

**Review by riqwan — APPROVED** [review]
lgtm, clean work @bqst! 🔥

**Comment by muke5hy** [comment]
Hi, is this available in the version 1.20.2?

I am getting following error when I run after upgrading to 1.20.2 

```
  query: 'SELECT "product"."id" AS "product_id", "product"."created_at" AS "product_created_at", "product"."updated_at" AS "product_updated_at", "product"."deleted_at" AS "product_deleted_at", "product"."title" AS "product_title", "product"."subtitle" AS "product_subtitle", "product"."description" AS "product_description", "product"."handle" AS "product_handle", "product"."is_giftcard" AS "product_is_giftcard", "product"."status" AS "product_status", "product"."thumbnail" AS "product_thumbnail", "product"."weight" AS "product_weight", "product"."length" AS "product_length", "product"."height" AS "product_height", "product"."width" AS "product_width", "product"."hs_code" AS "product_hs_code", "product"."origin_country" AS "product_origin_country", "product"."mid_code" AS "product_mid_code", "product"."material" AS "product_material", "product"."collection_id" AS "product_collection_id", "product"."type_id" AS "product_type_id", "product"."discountable" AS "product_discountable", "product"."external_id" AS "product_external_id", "product"."metadata" AS "product_metadata", "categories"."id" AS "categories_id", "categories"."created_at" AS "categories_created_at", "categories"."updated_at" AS "categories_updated_at", "categories"."name" AS "categories_name", "categories"."description" AS "categories_description", "categories"."handle" AS "categories_handle", "categories"."is_active" AS "categories_is_active", "categories"."is_internal" AS "categories_is_internal", "categories"."parent_category_id" AS "categories_parent_category_id", "categories"."rank" AS "categories_rank", "categories"."metadata" AS "categories_metadata", "categories"."mpath" AS "categories_mpath" FROM "public"."product" "product" LEFT JOIN "public"."product_category_product" "product_categories" ON "product_categories"."product_id"="product"."id" LEFT JOIN "public"."product_category" "categories" ON "categories"."id"="product_categories"."product_category_id" WHERE ( "product"."id" IN ($1) ) AND ( "product"."deleted_at" IS NULL )',
  parameters: [ 'prod_01HHYFBA21T124902F5FA6QKQX' ],
  driverError: error: column categories.metadata does not exist
  
  ```

**Comment by olivermrbl** [comment]
@muke5hy, have you run migrations?

```
npx medusa migrations run
```

**Pull request merged**
