### PR TITLE
fix: migrate segment subscribers + typescript support

### LINKED ISSUE #6068: Segment plugin failing when order has no shipping address
### Describe the bug

Our product is digital, so we don't add a shipping address to it. Segment fails to emit events as it always expects a shipping address.

### Steps to reproduce the behavior

1. Setup Medusa and Segment
2. Place an order without shipping address
3. Segment fails with `An error occurred while processing order.shipment_created: TypeError: Cannot read properties of null (reading 'country_code')`

### Expected behavior

Segments ignores shipping data if not available and emits the message

### Code snippets

https://github.com/medusajs/medusa/blob/8472460f533322cc4535199aa768ac163021bc79/packages/medusa-plugin-segment/src/services/segment.js#L83-L84

### Additional context

-

### PR DESCRIPTION
**Pull request by srindom**
Fixes #6068.

**What**

- Uses new Subscriber API.
- Adds support for typescript files in Segment plugin.
- Adds a peerDependency on @medusajs/medusa for the version that introduced new Subscriber API.

### CODE REVIEW

**Comment by adrien2p** [comment]
Would it make sense to use retrieveWithTotals instead to benefit from all the perf improvements and go into the direction of deprecating the ild total service?

**Review by adrien2p — APPROVED** [review]
LGTM 💪

**Comment by olivermrbl** [comment]
Now that we are at it, should we address #6068 and #6069?

**Comment by Edan-Swipik** [comment]
hi,
i don't see that those changes has been released with any of the latests versions.
what am i missing?

**Comment by sumanchy88** [comment]
Yes. I also don't see new changes after release. @srindom Could you please help with the version if it's released?

**Pull request merged**
