### PR TITLE
docs: fix edit button links

### LINKED ISSUE #4880: Docu: 'Edit page' links are broken
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Open any documentation page, e.g. [Medusa JS Client](https://docs.medusajs.com/js-client/overview).
At the bottom you will find a link Èdit this page`. This link is broken:

Actual value: `https://github.com/medusajs/medusa/edit/develop/www/docs/content/content/js-client/overview.md`
Expected value: `https://github.com/medusajs/medusa/edit/develop/www/docs/content/js-client/overview.md` 

### How can this issue be resolved?

Correctly configure the `Edit link` function in Docusaurus.

If you point me toward the corresponding config option, I'm willing to author a PR.

### Are you interested in working on this issue?

- [X] I would like to fix this issue

### PR DESCRIPTION
**Pull request by jhony112**
Closes #4880 
 
 Summary
 Fixes the  absolute  `Edit this page`  link from config 
 
 Before 
` ....content/content/js-client/overview.md`
After 
` ....content/js-client/overview.md`

### CODE REVIEW

**Review by shahednasser — APPROVED** [review]
LGTM! Thanks @jhony112

**Comment by shahednasser** [comment]
@jhony112 can I get you to resolve eslint errors by running the following command in `www/docs`:

```bash
yarn lint --fix
# or npm run lint -- --fix
```

**Comment by jhony112** [comment]
@shahednasser  ran `yarn lint --fix` , looks like the build scripts are stuck

**Comment by shahednasser** [comment]
@jhony112 ~you need to commit the changes after running the command~ Nevermind, just saw that you did 😄 I just need to re-run the tests and it should be good

**Pull request merged**
