### PR TITLE
fix(medusa): Plugin repository loader

### PR DESCRIPTION
**Pull request by adrien2p**
FIXES CORE-1177

### CODE REVIEW

**Comment by olivermrbl** [comment]
@adrien2p Is this ready for review?

**Comment by adrien2p** [comment]
@olivermrbl I did not test it yet, i ll do that tomorrow morning

**Comment by adrien2p** [comment]
@olivermrbl I ve just tested it and it worked

```ts
import { dataSource } from "@medusajs/medusa/dist/loaders/database";
import { User } from "@medusajs/medusa";

const UserRepository = dataSource.getRepository(User).extend({
  test() {
    return { test: "test" }
  }
})

export default UserRepository
```

**Review by olivermrbl — APPROVED** [review]
LGTM, we could add an integration test :)

**Pull request merged**
