### PR TITLE
chore: Refactor and improve abstract module service factory

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
Refactor and cleanup the modules service API

**NOTE**
Fix create/update mapped types not working, now they are working but the API must be generic any as not all modules follow the same convention and that can't be define through the types currently

**NOTE 2**
We have to add back the ts-ignore now that the types have been fixed and therefore we get back to the known ts issue about mapped types instance method of dynamic classes (https://github.com/microsoft/TypeScript/issues/48125)

FIXES CORE-2294

### CODE REVIEW

**Comment by adrien2p** [comment]
@sradevski @thetutlage @olivermrbl should be good to review and merge, then I can open the other pr with the fondational changes

**Comment by thetutlage** [comment]
Looks pretty neat to me!

**Review by thetutlage — APPROVED** [review]

**Comment by adrien2p** [comment]
@shahednasser just for info here how it will look like for simple users, some more changes will come soon though
```
export class TestModel {
  id: string
}

export class OtherModel {
  title: string
  id: string
}

class Service extends MedusaService(TestModel, { OtherModel }) {
  constructor(container: InjectedDependencies) {
    super(container)
  }

  async test() {
    const entities = await super.listOtherModels()
    const id = entities[0].title
  }
}
```

**Comment by shahednasser** [comment]
@adrien2p looks much cleaner 😄 can you let me know when it's ok to update the docs with this change? (as in, when it's ok for users to use this).

Also, do we not need type arguments anymore?

**Review by olivermrbl — APPROVED** [review]
Sublime work!

**Comment by olivermrbl** [comment]
cc @VariableVic

**Comment by adrien2p** [comment]
> @adrien2p looks much cleaner 😄 can you let me know when it's ok to update the docs with this change? (as in, when it's ok for users to use this).
> 
> 
> 
> Also, do we not need type arguments anymore?

Yes i let you know, yes the template args are not required but can be used if you want to specify a specific dto for example

**Pull request merged**
