### PR TITLE
fix/Aligned endpoints

### LINKED ISSUE #386: Align `POST /swaps` and `POST /returns` payloads
In [/api/routes/store/create-return.js](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/api/routes/store/returns/create-return.js) the payload calls for:

```js
    return_shipping: Validator.object()
      .keys({
        option_id: Validator.string().optional(),
      })
      .optional(),
```

and in [/api/routes/store/create-swap.js](https://github.com/medusajs/medusa/blob/master/packages/medusa/src/api/routes/store/swaps/create-swap.js) the payload calls for: 

```js
    return_shipping_option: Validator.string().optional(),
```

These should be aligned so that both use:
```js
    return_shipping_option: Validator.string().optional(),
```

### PR DESCRIPTION
**Pull request by Yuhanun**
Closes #386 

**What?**
Changed the JSON payload for the endpoints described in #386 (And fixed documentation consistency)

**Why?** 
Ensure consistency within Medusa.

**How?**
I simply changed the payload from an object to a string, as this is what the other endpoint had.

**Testing**
Sadly, I wasn't able to get the documentation to generate properly, due to issues with the documentation (as mentioned on discord in #need-help)

npm test was ran and all tests passed (if I recall correctly, I did this a few days ago.)

### CODE REVIEW

**Review by srindom — CHANGES_REQUESTED** [review]
Hi @Yuhanun great work so far 🎉  - there are still a couple of changes to be made here.

In `src/api/routes/store/returns/create-return.js` on line 108 you should check for `return_shipping_option` instead of `return_shipping` and make sure that the data is sent to the service layer correctly. 

Furthermore it would be good to see unit tests and integration tests for this. Let me know if you need help with setting up your env.

Please remove the API spec files from the change here - we run it once before every release so that we don't have huge PRs (like this one +15k lines :D:D).

**Comment by srindom** [comment]
[Maybe the comment on #451 is helpful for testing](https://github.com/medusajs/medusa/pull/451#issuecomment-933276790)

**Comment by Yuhanun** [comment]
> In src/api/routes/store/returns/create-return.js on line 108 you should check for return_shipping_option instead of return_shipping and make sure that the data is sent to the service layer correctly.

Where exactly does it get sent to the service layer? Is that also in create-returns.js?

> Furthermore it would be good to see unit tests and integration tests for this. Let me know if you need help with setting up your env.

I thought I already updated the integration tests to properly reflect the new layout though? I'll double check and make sure.

I would need help setting up my env, but since I'm probably going to start working on Medusa more seriously, I'll either switch back to Linux or MacOS for development and I don't really want to waste your time setting up a windows environment.

> Please remove the API spec files from the change here - we run it once before every release so that we don't have huge PRs (like this one +15k lines :D:D).
Will do, my bad.

I'll try and get this working this week.

**Comment by olivermrbl** [comment]
> here exactly does it get sent to the service layer? Is that also in create-returns.js?
See [this statement](https://github.com/Yuhanun/medusa/blob/720aac24f25edcc0ab79f976e8df85702e9f46cf/packages/medusa/src/api/routes/store/returns/create-return.js#L108)

**Comment by olivermrbl** [comment]
Solved in #817

**Pull request closed without merging**
