### PR TITLE
chore(ui,icons,ui-preset,toolbox): Move design system packages to monorepo

### PR DESCRIPTION
**Pull request by kasperkristensen**
Moves all design system packages into the core monorepo under `/packages/design-system`.

### CODE REVIEW

**Review by olivermrbl — APPROVED** [review]
🚀 🚀

**Comment by olivermrbl** [comment]
@kasperkristensen, can I get you to solve the conflicts? Should be ready to merge

**Comment by kasperkristensen** [comment]
> @kasperkristensen, can I get you to solve the conflicts? Should be ready to merge

@olivermrbl The CI continuously fail in `test-cli-with-database` because it can't resolve `@medusajs/ui-preset`, and I haven't been able to figure out how to fix it. It seems to stem from the fact that the action uses `medusa-dev`, and that causes `@medusajs/ui-preset` to get stored somewhere in the node_modules that causes it to no longer be reachable by the tailwind config in `@medusajs/admin-ui`. But it of course works without any issues locally, so I am having a hard time figuring out exactly where the preset is ending up within the action, which makes it hard to figure out how to fix it 🤷 I'll try to find some time to debug it this week, but it's super painful since I can only test it against the CI and its taking close to 20 min before it gets to the point that fails.

Edit:
And now it just worked all of the sudden, I changed the versioning to `workspace:^` so perhaps that made a difference. But we should properly run the tests a couple more times to make sure that it works every time, as I don't think we should merge this right now if it introduces CI flakiness. 

Edit 2:
Passed 3 times in a row so I am merging 🥳

**Pull request merged**
