### PR TITLE
feat: development server

### PR DESCRIPTION
**Pull request by carlos-r-l-rodrigues**
What:

Initial iteration for a simple development server of medusa core.
`yarn run develop:create:db` - Creates the database and seed it.
`yarn run develop` - Initialize the core as a server and auto reload when files are changed.

### CODE REVIEW

**Comment by adrien2p** [comment]
Seams pretty cool from a first look, i ll look at deeper next week 💪

**Comment by srindom** [comment]
Is the idea with this PR that you can do `yarn develop` while working on Medusa in order to avoid having a "dummy-project" that you run `medusa-dev` in?

**Comment by carlos-r-l-rodrigues** [comment]
> Is the idea with this PR that you can do `yarn develop` while working on Medusa to avoid having a "dummy-project" that you run `medusa-dev` in?

The idea is having a develop mode to medusa core and all the built-in plugins. Currently we have no easy way to update a plugin or create a new endpoint and easily test it while developing.
This PR will run `ts-node` to execute all the files directly from the `/src` folder and auto reload them when something has changed.
All the endpoints will be accessible so you can manually trigger requests to test.

**Comment by srindom** [comment]
I get this when `yarn run develop:create:db`

**Comment by srindom** [comment]
``

**Comment by carlos-r-l-rodrigues** [comment]
> I get this when `yarn run develop:create:db`

Fixed. Thanks

**Comment by olivermrbl** [comment]
This is really awesome @carlos-r-l-rodrigues! 

How should we proceed?

We could add additional seeders, or let more from the team spin up the development server to ensure it works in more local environments. Let me know what you think :)

**Comment by carlos-r-l-rodrigues** [comment]
Ideally we have more people trying it before merging this, and following that we can have another PR seeding the DB with all the required data.
Next steps we add support to feature flags on the seeders.

**Comment by olivermrbl** [comment]
> Ideally we have more people trying it before merging this

Sounds good!

**Comment by olivermrbl** [comment]
Would be great to run a couple more tests on local machines. Is anyone up for the task? @medusajs/engineering

**Review by olivermrbl — APPROVED** [review]
LGTM!

**Pull request merged**
