### PR TITLE
fix(medusa): Add product category relation in ProductSearchSubscriber

### PR DESCRIPTION
**Pull request by pepijn-vanvlaanderen**
The product search subscriber is currently not taking the `categories` relation into account when the product category feature flag is enabled. This PR solves that.

### CODE REVIEW

**Review by olivermrbl — APPROVED** [review]
Thanks @pepijn-vanvlaanderen, this is great.

**Comment by olivermrbl** [comment]
@pepijn-vanvlaanderen, can I get you to update the branch? We have merged a few things, that should make your PR pass the CI

**Comment by JoaquinUey** [comment]
I'm facing the same issue. When will this fix be publicly available?
Thanks

**Comment by olivermrbl** [comment]
@JoaquinUey today :)

**Comment by enyhma** [comment]
Hi @olivermrbl, has the fixed been released?

**Pull request merged**
