### PR TITLE
chore(pricing): remove priceSetMoneyAmountRules from pricing module

### PR DESCRIPTION
**Pull request by riqwan**
what:

- removes a model and its service methods that isn't being used
- removes all the database related changes

### CODE REVIEW

**Comment by olivermrbl** [comment]
Oh, this is nice!

**Review by sradevski — APPROVED** [review]
I really like LOC-negative PRs 😄

**Review by adrien2p — APPROVED** [review]
Love it 🔥

**Comment by adrien2p** [comment]
would it still work if we remove all models? 😂

**Pull request merged**
