### PR TITLE
Added compiling typescript files to develop command

### PR DESCRIPTION
**Pull request by ScuroGuardiano**
Added typescript support to `medusa develop` command.

### CODE REVIEW

**Comment by ScuroGuardiano** [comment]
It's for this issue [https://github.com/medusajs/medusa/issues/1281](https://github.com/medusajs/medusa/issues/1281)
Sorry, I don't know how to link issue to PR 😞

**Comment by olivermrbl** [comment]
Thanks for the contribution @ScuroGuardiano :) Could I get you to open the PR against `develop` instead?

**Comment by olivermrbl** [comment]
Sorry for the trouble @ScuroGuardiano, but it seems, that your branch now holds changes from `master`. Could I get you to rebase off of `develop`?

**Comment by ScuroGuardiano** [comment]
@olivermrbl Sorry, I am too dumb for it, just created another clean PR [https://github.com/medusajs/medusa/pull/1307](https://github.com/medusajs/medusa/pull/1307)

**Pull request closed without merging**
