### PR TITLE
fix: Improve get caller file path util

### PR DESCRIPTION
**Pull request by adrien2p**
FIXES CORE-2492

### CODE REVIEW

**Review by riqwan — APPROVED** [review]
🥇

**Comment by thetutlage** [comment]
Just curious, where do we use this helper?

**Comment by adrien2p** [comment]
> Just curious, where do we use this helper?

for the joiner config builder, basically since the choice was to make it fully magic and this builder is at different level in the application stack, I needed a way to retrieve the location of the original module caller

**Comment by adrien2p** [comment]
@thetutlage as I was explaining to carlos, since node deprecated the callee and that the require.resolve parent is deprecated as well, I didnt get a choice 😂 if you have anyhting in mind let me know

**Comment by thetutlage** [comment]
@adrien2p Nope. I am not questioning the implementation. Just curious, where do we/in which use cases we look for the callee path?

**Review by carlos-r-l-rodrigues — APPROVED** [review]

**Comment by thetutlage** [comment]
> for the joiner config builder, basically since the choice was to make it fully magic and this builder is at different level in the application stack, I needed a way to retrieve the location of the original module caller

Saw this comment now. Cool, makes sense!

**Pull request merged**
