### PR TITLE
Feat/product collection images

### PR DESCRIPTION
**Pull request by edihasaj**

### CODE REVIEW

**Comment by edihasaj** [comment]
https://github.com/medusajs/medusa/pull/1799

@kasperkristensen what do you think, I also added description to collections?

**Comment by edihasaj** [comment]
I'll also refer https://github.com/medusajs/admin/pull/631 so that we have an idea

**Comment by impactcolor** [comment]
@edihasaj this is great how do I pull? I'd like to use the collection images and descriptions.

**Comment by edihasaj** [comment]
You can pull from my branch. I am still waiting for a green light for this to be merged and completed.

**Comment by pevey** [comment]
It's a shame this feature was not merged.  Is it because someone on the core team is already working on it?

**Comment by edihasaj** [comment]
I don't know but anyways I am seeking other solutions

**Pull request closed without merging**
