### PR TITLE
fix(admin-ui): Undefined vars in admin

### PR DESCRIPTION
**Pull request by olivermrbl**

### CODE REVIEW

**Review by adrien2p — APPROVED** [review]
LGTM. Should we check if we have any other \W\s-\s\W in the package ?

**Comment by olivermrbl** [comment]
> LGTM. Should we check if we have any other \W\s-\s\W in the package ?

I've done a global search, and we should be good. Will try to set up a CI lint check for this specific rule.

**Review by fPolic — APPROVED** [review]
LGTM!

**Review by pKorsholm — APPROVED** [review]
lgtm

**Comment by olivermrbl** [comment]
I missed one undefined var. Will open a follow up

**Pull request merged**
