### PR TITLE
chore: es target 2021

### PR DESCRIPTION
**Pull request by carlos-r-l-rodrigues**

### CODE REVIEW

**Comment by carlos-r-l-rodrigues** [comment]
cc: @olivermrbl

**Comment by olivermrbl** [comment]
I like it! 

@carlos-r-l-rodrigues anything specific that prompted the change, or was it housekeeping?

**Review by sradevski — APPROVED** [review]
Really nice 👍

**Comment by carlos-r-l-rodrigues** [comment]
> I like it!
> 
> @carlos-r-l-rodrigues anything specific that prompted the change, or was it housekeeping?

Nothing specific. Just to get rid of polyfills in the generated JS code, and potentially help us serve Medusa with TSNode for development.

**Comment by olivermrbl** [comment]
@carlos-r-l-rodrigues cool, that's great 💪

**Pull request merged**
