### PR TITLE
fix(stripe): Wrong container type

### PR DESCRIPTION
**Pull request by adrien2p**
RESOLVES SUP-238

**What**

wrong container type withing payment providers

### CODE REVIEW

**Review by olivermrbl — COMMENTED** [review]
thought(non-blocking): Should we rename containers to `cradle` in the provider interfaces, abstract classes, and classes? Perhaps, this would make the access pattern even more obvious.

**Review by srindom — APPROVED** [review]
LGTM

**Comment by adrien2p** [comment]
> thought(non-blocking): Should we rename containers to `cradle` in the provider interfaces, abstract classes, and classes? Perhaps, this would make the access pattern even more obvious.

yes that might be better indeed, let me change that

**Comment by adrien2p** [comment]
@olivermrbl are you fine if I just change the name in the constructor but not the class prop as it would create a breaking change?

**Comment by olivermrbl** [comment]
Yes, sure, makes sense to me.

**Review by olivermrbl — APPROVED** [review]

**Pull request merged**
