### PR TITLE
chore(framework): Move and improve routes loader

### PR DESCRIPTION
**Pull request by adrien2p**
FIXES FRMW-2604
FIXES FRMW-2605

**What**
Little improvements of the routes loader as well as cleanup and moved to the framework. this pr does not include any fixes but the improvements to improve readability and reduce complexity gave us a 30% tests runtime improvements as a side effects

### CODE REVIEW

**Review by sradevski — APPROVED** [review]
LGTM, I assume there were no changes to the middlewares, just the loader? It's difficult to tell what changed and what didn't 😃

**Comment by adrien2p** [comment]
> LGTM, I assume there were no changes to the middlewares, just the loader? It's difficult to tell what changed and what didn't 😃 

Yeah i ce kept the middlewares as they are 😅 i think a first iteration like that is enough and we can refine later for the rest to not include breaking changes etc. I ve mostly cleaned up the routes loader

**Comment by adrien2p** [comment]
But a full review @sradevski would still be nice cause it is a central piece at the moment (even if it is a bit broken). My approach in those cases is to open both files in my ide to check 😅

**Review by thetutlage — APPROVED** [review]

**Review by olivermrbl — APPROVED** [review]
LGTM, nice work

**Pull request merged**
