### PR TITLE
feat(metadata): ability to delete metadata if value of null is explicitly set

### PR DESCRIPTION
**Pull request by jaruesink**
Screen Shot 2021-12-02 at 3 18 11 PM

Usecase: Ability to add/remove metadata for products

### CODE REVIEW

**Comment by jaruesink** [comment]
@srindom sorry, didn't realize there was a `develop` branch. for sure will PR here from now on!

**Review by srindom — APPROVED** [review]

**Comment by jaruesink** [comment]
@srindom looks like y'all are using `yarn` now? I'll update this once more

**Comment by srindom** [comment]
Please make sure the integration tests are passing - looks like you can just run the integration tests with `-u` to update the snapshot :)

**Comment by jaruesink** [comment]
@srindom why would me changing a function change a snapshot? I'll see if running that fixes it.

**Comment by jaruesink** [comment]
@srindom ok after pulling in latest dev and reinstalling things, that one seemed to pass

**Comment by jaruesink** [comment]
@srindom the UI looks different now, but I still think this is an important feature. Let me know if we can get this merged!

**Pull request closed without merging**
