### PR TITLE
fix(medusa-cli): Logger arguments

### PR DESCRIPTION
**Pull request by xyzones**
- winston.Logger.log requires level as param

### CODE REVIEW

**Review by adrien2p — COMMENTED** [review]
Should we instead update the log method from the logger to pass (`info', ... args) wdyt? cc @olivermrbl

**Comment by xyzones** [comment]
Well, we could extend the
Log wrapper however as we do not know where this is used defaulting to info might not be the best. 

I would maybe do something like 
```typescript
if (args.length > 1) { 
  logger.log(...args)
} else {
  logger.info(args[0])
}
```

**Comment by adrien2p** [comment]
> Well, we could extend the Log wrapper however as we do not know where this is used defaulting to info might not be the best.
> 
> I would maybe do something like
> 
> ```ts
> if (args.length > 1) { 
>   logger.log(...args)
> } else {
>   logger.info(args[0])
> }
> ```

yeah lets go with

```ts
if (args.length > 1) { 
  return logger.log(...args)
}

logger.info(args[0])
```

**Comment by xyzones** [comment]
I have updated the medusa-cli reporter that is used by the migrate-inventory-items

**Comment by olivermrbl** [comment]
LGTM!

**Review by gancena — APPROVED** [review]

**Review by sradevski — APPROVED** [review]

**Pull request merged**
