### PR TITLE
fix: :bug: Order can be deleted multiple times in the admin-ui

### PR DESCRIPTION
**Pull request by adevinwild**
- added a condition to check if the order status is already `canceled` and show a notification error in that case

### CODE REVIEW

**Comment by StephixOne** [comment]
Thanks for finding this and for your contribution!

I think the cleaner approach here, though, would be to hide the actionables on that card if the order is cancelled. That way a user isn't presented with an action we know will not work.

**Comment by adevinwild** [comment]
> Thanks for finding this and for your contribution!
> 
> I think the cleaner approach here, though, would be to hide the actionables on that card if the order is cancelled. That way a user isn't presented with an action we know will not work.

You're right, I'll take care of it ASAP

**Comment by tsvetann** [comment]
> Thanks for finding this and for your contribution!
> 
> I think the cleaner approach here, though, would be to hide the actionables on that card if the order is cancelled. That way a user isn't presented with an action we know will not work.

From @adevinwild findings what I understand is that there is definitely an issue in the admin API which handles deletions not in the best way, therefore, I think both the admin api and the admin UI should be fixed. If we only fix the UI (as per your suggestion) we are basically leaving a time bomb in the API that soon or later someone will stumble upon. Thanks

**Comment by adevinwild** [comment]
> > Thanks for finding this and for your contribution!
> > I think the cleaner approach here, though, would be to hide the actionables on that card if the order is cancelled. That way a user isn't presented with an action we know will not work.
> 
> From @adevinwild findings what I understand is that there is definitely an issue in the admin API which handles deletions not in the best way, therefore, I think both the admin api and the admin UI should be fixed. If we only fix the UI (as per your suggestion) we are basically leaving a time bomb in the API that soon or later someone will stumble upon. Thanks

i totally agree with you, that's what I had stipulated in my [_Issue_](https://github.com/medusajs/medusa/issues/4336), I'll try to take care of it too on the API side 👍

**Comment by adevinwild** [comment]
it's ok for me I think, need a review  👍

**Comment by adevinwild** [comment]
it's ok for me 👍

**Comment by riqwan** [comment]
Hey, thanks for the PR! Since v2 brought a lot of architectural changes, we will be closing this ticket since it no longer applies to our new setup.

**Pull request closed without merging**
