### PR TITLE
chore: Rename entity to model

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
Start renaming `entity` to `model`

### CODE REVIEW

**Comment by adrien2p** [comment]
cc @shahednasser would this be a good start?

**Review by shahednasser — APPROVED** [review]
Love this 🔥

**Comment by adrien2p** [comment]
@olivermrbl wdyt of this first step around the medusa service and so, cause it is one of the first thing people will see and use

**Comment by adrien2p** [comment]
@shahednasser I ll wait oli approval before merging

**Review by sradevski — APPROVED** [review]
One step closer to cleaner codebase 😄

**Review by olivermrbl — APPROVED** [review]
This is great @adrien2p!

**Pull request merged**
