### PR TITLE
fix(stripe): await promises to make sure they complete before moving on.

### PR DESCRIPTION
**Pull request by dwene**
I was having issues updating payment sessions when using stripe. I believe the issue is that there are un-awaited promises floating around in here. I'm thinking this will fix the issue.

### CODE REVIEW

**Comment by adrien2p** [comment]
We should not have to await for returned promises. The consumer should manage the awaiting since it receive a promise. Are you sure the problem comes from that ?

**Comment by jaruesink** [comment]
@adrien2p I don't think it solves the problem in this instance, however I don't think the Try / Catches will work as expected here. Here's an article outlining that https://dmitripavlutin.com/return-await-promise-javascript/

**Comment by adrien2p** [comment]
It is not entirely true, here is an example that you can run

```javascript
async function rejection() {
	return Promise.reject("test error");
}

async function runWithoutTryBlock() {
	return await rejection()
}

async function run() {
	try {
		return await rejection()
	} catch (e) {
		console.log(e);
	}

}

runWithoutTryBlock(); // UnhandledPromiseRejectionWarning
run(); // error handled
```

**Comment by adrien2p** [comment]
in fact, both are right, either adding the await or removing the try catch blocks that just re throw the errors :)

**Comment by dwene** [comment]
Ok, @adrien2p I can do that also. I found the actual issue in the stripe provider, so I'm going to close this PR and open another one with the actual fixes, and do what you suggest also :)

**Pull request closed without merging**
