### PR TITLE
chore(docs): remove unused files from `www` directory

### PR DESCRIPTION
**Pull request by patrick-medusajs**
### What

Only keep `/www/docs` and remove all other files and directories from `/www`

### Why

The `www` directory contained files that are not in use anymore. These dangling files lead to confusion when investigating usage of a specific piece of code.

### CODE REVIEW

**Review by shahednasser — APPROVED** [review]
LGTM 🚀

**Comment by shahednasser** [comment]
Actually @patrick-medusajs can we change to the `master` branch? We use the `master` branch for basically everything docs and the required tests on the `develop` branch do not run for changes in the documentation directories

**Comment by patrick-medusajs** [comment]
@shahednasser I rebased the branch onto `master`. Could you have a quick look to verify that I didn't mess anything. Then, I'll create a PR to merge `master` back into `develop`

**Comment by shahednasser** [comment]
@patrick-medusajs all file changes look fine to me, and I testing running and building the current documentation - all works fine!

**Pull request merged**
