### PR TITLE
feat(admin-ui): Allocation order time line events

### PR DESCRIPTION
**Pull request by pKorsholm**
**What**
- Add "Awaits Allocation" and "allocation created" order timeline events 
- Convert all timestamps to dates

Fixes CORE-1348

### CODE REVIEW

**Review by fPolic — APPROVED** [review]
LGTM!

**Comment by olivermrbl** [comment]
Something seems off. Before allocation the "Awaits Allocation" timeline event is not present. Though, after allocating the items it shows up. Am I missing something @pKorsholm ?

CleanShot 2023-05-03 at 10 03 04@2x

**Comment by olivermrbl** [comment]
Also, refreshing the order details page removes the timeline events entirely:
CleanShot 2023-05-03 at 10 04 58@2x

**Comment by olivermrbl** [comment]
I believe both issues could be caused by events not being fetched and displayed properly, so this is maybe a simple fix.

**Comment by olivermrbl** [comment]
@pKorsholm – have you been able to reproduce the issues I highlighted?

**Pull request closed without merging**
