### PR TITLE
feat(medusa):  Add Mongolian Tugrug (MNT)

### PR DESCRIPTION
**Pull request by endigo**
Add missing Mongolian national currency Tugrik/Tugrug/Төгрөг.

### CODE REVIEW

**Comment by endigo** [comment]
@adrien2p Can you please review it?

**Comment by olivermrbl** [comment]
Thanks for the contribution @endigo! Can I get you to change base branch to develop and rebase?

**Comment by olivermrbl** [comment]
Also, this change should not result in a major update, so please modify the changeset to be `patch` instead 👍

**Comment by olivermrbl** [comment]
@endigo You are still missing to rebase off of `develop`. The PR currently holds a lot of files not relevant for the change here.

**Comment by endigo** [comment]
@olivermrbl I couldn't rebase, Can you help me with this?

Thanks

**Pull request closed without merging**
