### PR TITLE
docs: fixed a typo in development docs

### PR DESCRIPTION
**Pull request by yakin-ts**
There is a minor typo under the section "(Optional) Medusa CLI".

### CODE REVIEW

**Comment by shahednasser** [comment]
Thank you for your contribution! However, that's not a type. So, I'll close this PR.

**Comment by yakin-ts** [comment]
@shahednasser Is the first 'your' intentional in the following statement ? that is what I am referring to( a typo not a type issue). I think the first "your" should be "you".
"Medusa provides a CLI tool that can aid your through your Medusa development"

**Comment by shahednasser** [comment]
Yes, the first one is you intentionally. Medusa CLI aids you, as in the developer.

**Comment by yakin-ts** [comment]
Exactly, it should be you but it's "your" in the documentation, that's what I am trying to fix.

**Comment by yakin-ts** [comment]
Have a second look at the change please.

**Comment by yakin-ts** [comment]
@shahednasser should I delete this branch and open another PR or what do you suggest ?

**Comment by shahednasser** [comment]
Sorry I mixed up your change with the original text 😅 re-opening the PR.

**Review by shahednasser — APPROVED** [review]
LGTM

**Pull request merged**
