### PR TITLE
fix(medusa): Get cart missing transaction on update

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
If some constraint are meet and there is a logged in user, an update is run on the cart, but the transaction was missing and can lead to a query running already released

FIXES CORE-1124

### CODE REVIEW

**Review by pKorsholm — APPROVED** [review]
lgt

**Review by fPolic — APPROVED** [review]
LGTM

**Comment by josetr** [comment]
I was wondering why the `atomicPhase_` call at `cartService.update` that creates a transaction wasn't enough, but it seems that this problem is the same as https://github.com/medusajs/medusa/issues/1845 .

I think this behavior should be in the docs, because I'm afraid those creating custom endpoints will make this mistake more often than not.

The admin update currency endpoint seems to have this problem too - I've created a PR to address it.

There is a typo in `transctionManager` btw.

**Pull request merged**
