### PR TITLE
fix(medusa): Deleted discount missing on order

### PR DESCRIPTION
**Pull request by pepijn-vanvlaanderen**
Also see https://github.com/medusajs/medusa/issues/6291
The order totals are scewed when a discount is deleted.

### CODE REVIEW

**Review by olivermrbl — APPROVED** [review]
Thanks @pepijn-vanvlaanderen, this is great

**Comment by olivermrbl** [comment]
Could I get you to add an integration for it? 

It would be almost identical to the one testing deleted regions:
https://github.com/medusajs/medusa/blob/4cf71af07d1807c83df3889c1774f82cbd1b9a6f/integration-tests/api/__tests__/admin/order/order.js#L2627-L2651

**Comment by pepijn-vanvlaanderen** [comment]
@olivermrbl sure thing, the integration test has been added.

**Comment by olivermrbl** [comment]
@pepijn-vanvlaanderen, finally please [add a changeset](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md), as per the contribution guide.

**Comment by pepijn-vanvlaanderen** [comment]
@olivermrbl sure thing, added it just now

**Comment by olivermrbl** [comment]
@pepijn-vanvlaanderen, can I get you to update your branch with the latest from develop? Then I'll merge 🚢

**Comment by pepijn-vanvlaanderen** [comment]
@olivermrbl yes, done!

**Pull request merged**
