### PR TITLE
fix(medusa): Broken payment session migration

### PR DESCRIPTION
**Pull request by rajshrimohanks**
Currently, when setting up a fresh project, the initial migration fails when running the seed or migrate commands in a non-public schema in PostgreSQL. This is probably because the last migration file looks for `UniqPaymentSessionCartIdProviderId` in the `public` schema which will not exist. This will cause the transaction to rollback.

 This PR fixes it.

### CODE REVIEW

**Comment by adrien2p** [comment]
@rajshrimohanks Can I get you to change the base branch to `develop` and update the pr please

**Comment by rajshrimohanks** [comment]
> @rajshrimohanks Can I get you to change the base branch to `develop` and update the pr please

Updated it now. Sorry, didn't realize that base branch has to be `develop`. First time PR here.

**Comment by oakbani** [comment]
@olivermrbl  Can we merge this? We are blocked by using multi-tenant approach.

**Review by adrien2p — APPROVED** [review]
LGTM. thought, not sure it is needed to specify the schema in the query. The schema can be specified in the typeorm datasource configuration and might clash with a fixed schema. wdyt?

**Comment by rajshrimohanks** [comment]
> The schema can be specified in the typeorm datasource configuration and might clash with a fixed schema. wdyt?

The original cause of the problem was specifying the schema in the query:

```typescript
await queryRunner.query(`DROP INDEX "public"."UniqPaymentSessionCartIdProviderId"`);
```
I'm dropping that index in case it exists (just as a precaution) and adding it back without specifying the schema. This way, whatever schema is configured in TypeORM's config will be picked up.

**Review by adrien2p — APPROVED** [review]
LGTM

**Comment by Mark-Jung** [comment]
When will this get merged? 
I've been following the marketplace tutorial and wanted to share this to my colleagues to migrate, and facing a failure on their first run isn't a good look so I wanted to wait until this gets fixed :)

**Review by carlos-r-l-rodrigues — APPROVED** [review]

**Review by olivermrbl — APPROVED** [review]

**Comment by olivermrbl** [comment]
@Mark-Jung – sorry for the slow follow-up. This fix will be included in the next release. Until then, you can use this snapshot: `@medusajs/medusa@1.9.1-next-20230427083711` :)

**Comment by rbkdigital** [comment]
I came across this PR trying to find how to run medusa migrations in a non-public schema. Is there a tutorial or documentation to run migrations in a non-public schema?

**Comment by oakbani** [comment]
@rbkdigital  You just need to append search path param to psql connection string and should do the work. search_path witll help you define your schema when connecting to database

psql "postgresql://user:pwd@127.0.0.1:6789/postgres?options=-csearch_path%3Dabc"

**Pull request merged**
