### PR TITLE
fix(medusa-file-s3, medusa-file-minio): Use file.mimetype to upload file with correct ContentType

### PR DESCRIPTION
**Pull request by dwene**
2 fixes here:

1. I noticed when we uploaded webp images to either S3 or Minio, their ContentType was marked application/octet-stream. This was fine most of the time, until I tried sending emails with those images. Some email services proxy images (like gmail), and the images were all 500-ing because of the incorrect content type. This fixes that issue.

2. I noticed that minio adds a date to the file key when uploading an image, but s3 does not. I don't think anyone wants accidental overrides of file content by having the same file name, so I'm including that pattern in the s3 file plugin also.

### CODE REVIEW

**Comment by olivermrbl** [comment]
This is great. Thank @dwene. Can I get you to merge in latest changes from `develop` and add a changeset? For the latter, you can find examples in folder `.changeset` at root.

**Comment by dwene** [comment]
@olivermrbl done!

**Comment by pevey** [comment]
It seems like this PR was never merged?  I am having a similar issue, and separately I was wondering about setting other metadata on file upload, specifically cache control.  Currently, images are uploaded with no caching.  You can go in and do it in the AWS console, but you have to do it one by one.

The logs from the failed integration tests have expired, so I can't see what is holding this back.  @dwene Any chance you could merge changes to bring this up to date?  

After this PR is merged, I want to do one for setting the cache control header based on a config setting.

**Comment by dwene** [comment]
Hey @pevey , I actually got all these changes merged when I migrated the plugins to typescript here: https://github.com/medusajs/medusa/pull/3740

I'm going to close this PR.

**Comment by pevey** [comment]
Ah, that makes sense.  Thanks.  I guess all my images that I was viewing were uploaded before those changes were released.

**Pull request closed without merging**
