### PR TITLE
fix(medusa): add payments default relation to getTotalsRelations

### LINKED ISSUE #5874: bug: order.paid_total by default always 0
### Describe the bug

Retrieve with totals in order service always returns paid_total=0

### System information

Medusa version (including plugins): 1.18

### Steps to reproduce the behavior

1. Call any method that calls decorateTotals (retrieveWithTotals, retrieveByCartIdWithTotals, etc.) without passing in the payments relation manually
2. Observe paid_total always 0

### Expected behavior

Expect paid total to be calculated correctly without passing "payments" explicitly

### Additional context

https://github.com/medusajs/medusa/blob/1c6c759aa895db4a5888257fac1ccadb2ea74162/packages/medusa/src/services/order.ts#L1858C12-L1858C12
This line calculates paid_total and will always result in 0 unless the user passes in the payments field by himself, since the "payments" field isnt in getTotalsRelations.

### PR DESCRIPTION
**Pull request by cyf0e**
- **What** - add "payments" relation to getTotalsRelations in order service
- **Why** - fixes bug where order.paid_total is always 0 by default
- **How** - add "payments" relation to getTotalsRelations in order service
- **Testing** - manual testing

Fixes #5874 

This line https://github.com/medusajs/medusa/blob/1c6c759aa895db4a5888257fac1ccadb2ea74162/packages/medusa/src/services/order.ts#L1858C12-L1858C12 in the order service looks to beresponsible for calculating paid_total when you try to retrieve an order with totals.

By default if the user doesnt pass in the "payments" relation manually by himself, the paid total will always be 0 which is probably not the expected behaviour. 

Adding the payments relation to default getTotalsRelations fixes this.

### CODE REVIEW

**Review by adrien2p — APPROVED** [review]
LGTM

**Comment by olivermrbl** [comment]
@cyf0e please fix the integration tests, so we can merge :)

**Comment by cyf0e** [comment]
@olivermrbl should be good, having trouble running the integration tests locally so cant really validate. sorry about that

**Pull request merged**
