### PR TITLE
fix(utils): Cascade soft deletion management

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
Fix broken soft deletion depending on the object received

### CODE REVIEW

**Comment by olivermrbl** [comment]
What was the broken scenario?

**Comment by adrien2p** [comment]
> What was the broken scenario?

in some cases depending on the object, entity is not a function which was breaking the soft deletion entirely. Now it works in all cases. Also, since we haven't migrated our entire core to DML we didn't catch it and we didn't had tests on the DML for this. So I ve added it so that DML test the soft deletion itself as well

**Comment by adrien2p** [comment]
@christiananese have you been able to give it a spin?

**Review by riqwan — APPROVED** [review]

**Review by olivermrbl — APPROVED** [review]

**Pull request merged**
