### PR TITLE
feat(dashboard): shipping & location

### PR DESCRIPTION
**Pull request by fPolic**
**What**
- new shipping and location domains

**NOTEs**
- "Edit shipping options prices" modal is a todo (a followup PR)
- deleted Locations are still returned when listing locations

**Depends on**
- [x] #7175
  - _updating "enabled in store" depends on this one_

---

https://github.com/medusajs/medusa/assets/16856471/d52eedcc-f0d5-45fe-81ca-ff348f5320bc

### CODE REVIEW

**Comment by olivermrbl** [comment]
The left border on the "View details" button seems off. Should it even be there?

CleanShot 2024-05-01 at 14 51 36

**Comment by olivermrbl** [comment]
When I create a new location, I get a 404. Think the URL is wrong:
CleanShot 2024-05-01 at 15 08 23

**Comment by olivermrbl** [comment]
It seems enabling pick up doesn't work as expected. See video below. I presume we are switching on the `type` somewhere incorrectly:


https://github.com/medusajs/medusa/assets/59018053/320e7117-c697-4783-9585-2c07220ad295

**Comment by fPolic** [comment]
@olivermrbl should be fixed now.

**Comment by sradevski** [comment]
I didn't go through the code, but for what is worth it it works as expected when I tested it.

**Review by olivermrbl — APPROVED** [review]

**Pull request merged**
