### PR TITLE
fix(product): Serialize typings

### PR DESCRIPTION
**Pull request by adrien2p**
What:
Fix the serializer

### CODE REVIEW

**Comment by olivermrbl** [comment]
Why are these updated?

**Comment by adrien2p** [comment]
> Why are these updated?

To fix the serializer

**Comment by olivermrbl** [comment]
> To fix the serializer

Yes, I see that it fixes the serializer, but what was wrong? 😅

**Comment by adrien2p** [comment]
> > To fix the serializer
> 
> 
> 
> Yes, I see that it fixes the serializer, but what was wrong? 😅 

The return value was wrong, if it wasn't an array it was returning undefined.

**Review by olivermrbl — APPROVED** [review]

**Pull request merged**
