### PR TITLE
Fix(medusa): duplicated migration

### PR DESCRIPTION
**Pull request by carlos-r-l-rodrigues**
Fix duplicated migration class name

### CODE REVIEW

**Review by adrien2p — APPROVED** [review]
Noce catch LGTM

**Comment by carlos-r-l-rodrigues** [comment]
@adrien2p @olivermrbl do we need a changeset for this? or no as it wasn't released yet.

**Comment by adrien2p** [comment]
I believe we need a changeset to get it included no?

**Comment by olivermrbl** [comment]
Yes, a patch changeset. But not super important. Fine with me to merge as is :)

**Review by olivermrbl — APPROVED** [review]

**Pull request merged**
