### PR TITLE
feat(medusa-js): add axios adapter to config

### LINKED ISSUE #6133: Unhandled Runtime Error: adapter is not a function
**Bug Report**
**Describe the Bug**
I am encountering an issue with MedusaJS when executing requests on NextJS Edge runtime. The bug seems to be associated with Axios, displaying the error: 'Unhandled Runtime Error: adapter is not a function.'

**System Information**
Medusa Version: "@medusajs/medusa-js": "^6.1.5", "medusa-react": "^9.0.13"
Node.js Version: [Not relevant]
Database: [Not relevant]
Operating System: [Not relevant]
Browser: [Not relevant]

**Steps to Reproduce the Behavior**
Initialize a Next.js project.
Install medusajs and medusa-react.
Initialize an instance of a MedusaJS client.
Switch Page runtime to edge
Attempt to fetch data using a method such as medusaClient.products.list().

**Expected Behavior**
The expectation is to successfully fetch data in the same manner as when using a Node.js runtime environment.

**Screenshots**
_yarn run dev_
image

_yarn build
yarn start_
image

**Code Snippets**
A minimal repository reproducing the bug can be found here: [MedusaJS Minimal Bug Reproduction](https://github.com/nabilAparicio/MedusaJS-MinimalBugRepro)

### PR DESCRIPTION
**Pull request by SirRodney**
**What**

- Adds the ability to pass an Axios adapter through the client's config.

**Why**

- When using NextJS with the edge runtime for deployment on Cloudflare Pages, for example, Axios does not work. Therefore, it is necessary to pass an adapter like [@vespaiach/axios-fetch-adapter](https://github.com/vespaiach/axios-fetch-adapter).

**How**

- Receives the **axiosAdapter** in the config and implements it when creating the **axiosClient**.

Closes #6133

### CODE REVIEW

**Review by carlos-r-l-rodrigues — APPROVED** [review]
LGTM

**Comment by lekterable** [comment]
when is this going out?

sorry to tag you directly @srindom, but I'm on `6.1.6` (latest) and this issue prevents me from using the `@medusajs/medusa-js` package completely (patch-packaging would be quite difficult with all this minified code)

I'd appreciate a quick resolution, thanks!

**Comment by olivermrbl** [comment]
@lekterable, this PR was missing a changeset on merge, so the version was not bumped in the recent release. I'll add one manually and release the package as soon as possible. I hope to be able to do this later today.

**Comment by olivermrbl** [comment]
@lekterable, new release is out. Please try `@medusajs/medusa-js@6.1.7` and let me know :)

**Comment by lekterable** [comment]
thanks for such a quick response @olivermrbl, but seems like the issue is still there :(

any ideas? I updated the package version, cleaned up node_modules and reinstalled

```
  "dependencies": {
    "@headlessui/react": "1.7.18",
    "@heroicons/react": "2.1.1",
    "@medusajs/medusa": "1.20.2",
    "@medusajs/medusa-js": "6.1.7",
    "@medusajs/ui": "2.4.0",
    "@next/third-parties": "14.1.0",
    "@stripe/react-stripe-js": "2.4.0",
    "@stripe/stripe-js": "2.4.0",
    "@tanstack/react-query": "4.22",
    "@vercel/analytics": "1.1.3",
    "clsx": "2.1.0",
    "medusa-react": "9.0.15",
    "next": "14.1.0",
    "react": "18.2.0",
    "react-country-flag": "3.1.0",
    "react-dom": "18.2.0",
    "tailwind-merge": "2.2.0"
  },
```

image

**Comment by lekterable** [comment]
ah I see now, we are required to pass this adapter ourselves, I tried adding the one which is mentioned in description (https://github.com/vespaiach/axios-fetch-adapter) and now I get a different error

suggestion: maybe we could just ship it with some default adapter for easy usage?

image

**Comment by zaidrashid** [comment]
Hi @lekterable , how do you instantiate the adapter and added in the Medusa configuration? Do you have any code examples that I can take a look at?

Also, any chance you have managed tp solve the issue by now?

Thanks

**Pull request merged**
