### PR TITLE
feat(addToCartWorkflow): Add beforeAddToCart hook

### PR DESCRIPTION
**Pull request by Alexnortung**
This PR adds a hook to the `addToCartWorkflow`

### CODE REVIEW

**Review by riqwan — COMMENTED** [review]
nice! I'll tag @thetutlage in this one as he was spear heading this. We might need a more uniform naming pattern.

**Comment by adrien2p** [comment]
Great 🎉 we will loop back internally in order to validate the API for this hook 👍

**Comment by Alexnortung** [comment]
Hello @adrien2p , did you forget about this?

Can I also add a hook for after the items have been added to the cart?

**Comment by adrien2p** [comment]
> Hello @adrien2p , did you forget about this?
> 
> Can I also add a hook for after the items have been added to the cart?

Hi @Alexnortung sorry for the late response, I haven't forgot about it and shared it internally, unfortunately other priorities have taken my time at the moment.

cc @srindom

**Comment by thetutlage** [comment]
How about renaming the hook to `addingToCart`? This is basically to match how other hooks are named. For example: `cartUpdated`, `productsCreated` and so on.

**Comment by KMJ-007** [comment]
any update on this?

@sradevski 

> [@okechukwu0127](https://github.com/okechukwu0127) thanks for the detailed ticket description!
> 
> We are adding hooks as we go, but we are always open for PRs contributing such changes, it will definitely ensure this gets merged and released sooner.

**Pull request closed without merging**
