### PR TITLE
docs: fixed issue #2289 and Removed the Prerequisites section

### PR DESCRIPTION
**Pull request by ayushthe1**
* What - Docs: Remove the Prerequisites section in Create an Entity documentation #2289
* Why - The [prequisites section](https://github.com/medusajs/medusa/blob/6adaf56c737ab7ed68055fedcd98c89158dd1ca9/docs/content/advanced/backend/entities/index.md#prerequisites) in [Create an Entity documentation](https://docs.medusajs.com/advanced/backend/entities/#create-the-entity) is no longer necessary as this is now available by default in the starter.
* How - Following the guideline in the issue made the changes to `medusa/docs/content/tutorial/0-set-up-your-development-environment.mdx`
* Testing - it's a markup file, so should not require anything other than manual testing.

### CODE REVIEW

**Comment by shahednasser** [comment]
Thank you for your work @ayushthe1 but someone else is assigned this issue. We assign issues to the first person that comments.

**Comment by ayushthe1** [comment]
> Thank you for your work @ayushthe1 but someone else is assigned this issue. We assign issues to the first person that comments.

I get it .But i commented before the person you assigned this issue to (asking you to check the pr i made before but i deleted that comment an hour ago coz i deleted that pr due to not following contributing guidelines).

I also made another PR regarding this issue 2 days ago but i deleted that today as i found out that it didnt satisfied the contributing guidelines .So in actuality ,i have been working on this issue way before you assigned this issue to the current assignee. So please accept my commit.

**Comment by shahednasser** [comment]
Sorry but to manage all the requests to get assigned better we assign based on first comment, not first PR. Thank you for working on this and there will be more issues to work on in the future.

**Comment by ayushthe1** [comment]
Thanks for your time. Will try to contribute on other issues .

**Pull request closed without merging**
