### PR TITLE
fix(medusa): Remove shipping on updates to `cart.items`

### LINKED ISSUE #4707: Shipping methods are never removed when line item is removed or added from cart
### Describe the bug

When you remove something from your shopping cart the shipping method should be deleted because it needs to be recalculated. This bug can lead to cases where the shipping costs are too low or too high. To prevent this from happening you want the shipping methods to be deleted when an item is added or removed to the cart.

For the removal of an item there is code that does this but it never gets called because "shipping_methods" is never fetched from the database. E.g. this line of code can never be reached because "shipping_methods" is not retrieved
https://github.com/medusajs/medusa/blob/efdea04963916b49271b4b01440ee7e584207992/packages/medusa/src/services/cart.ts#L493

Note that adding an item or updating an item in the cart should also remove the shipping method from the cart. There is currently no code that does this.

### System information

Medusa version (including plugins): 1.13.1-beta-20230727162508 (i checked and the bug is also in the latest non beta version)
Node.js version: v20.2.0
Database: Postgres
Operating system: MacOS

### Steps to reproduce the behavior

1. Set up a shipping method that calculates the price based on the items in the cart 
2. Put something in your cart
3. Go to checkout
4. Fill out shipping address and calculate the shipping price
5. Go back to the store and add another item to the cart
6. Go back to checkout
7. Shipping price is still based on the old items in the cart from step 4.

### Expected behavior

1. Set up a shipping method that calculates the price based on the items in the cart 
2. Put something in your cart
3. Go to checkout
4. Fill out shipping address and calculate the shipping price
5. Go back to the store and add another item to the cart
6. Go back to checkout
7. Shipping price is recalculated based on the new cart

### PR DESCRIPTION
**Pull request by olivermrbl**
@adrien2p, what do you think about this? Resolves #4707

I think it's reasonable to remove the method on line item updates to always ensure correct shipping on the cart.

The more elegant way would be to validate if the shipping method is still applicable given the update to the items, but that is a more extensive change that I don't know if we should do given we will be modularizing the cart + shipping soon.

### CODE REVIEW

**Review by adrien2p — APPROVED** [review]
LGTM, i think it is fine to remove the methods completely when we update the items ✅

**Comment by SimonsThijs** [comment]
Crazy quick fix! thanks!

If i am not mistaken you missed the addOrUpdateLineItems function.

**Comment by olivermrbl** [comment]
Right, thx @SimonsThijs!

Now that you've seen what needs to be added, would you be up for tackling this one?

**Comment by SimonsThijs** [comment]
Yes, should be no problem.

@olivermrbl do you want me to just make a new pull request?

**Comment by olivermrbl** [comment]
That would be great, thanks!

**Comment by SimonsThijs** [comment]
Alright https://github.com/medusajs/medusa/pull/4725 ✅

**Pull request merged**
