### PR TITLE
fix(modules-sdk): medusa app load legacy modules

### PR DESCRIPTION
**Pull request by carlos-r-l-rodrigues**

### CODE REVIEW

**Review by olivermrbl — COMMENTED** [review]
Is this related to @adrien2p's [comment on his PR](https://github.com/medusajs/medusa/pull/5081#discussion_r1327324750)?

**Comment by carlos-r-l-rodrigues** [comment]
> Is this related to @adrien2p's [comment on his PR](https://github.com/medusajs/medusa/pull/5081#discussion_r1327324750)?

No, not directly related to it. This check is preventing "legacy" modules (inventory and stock-location) to be loaded using MedusaApp.

**Comment by olivermrbl** [comment]
> No, not directly related to it. This check is preventing "legacy" modules (inventory and stock-location) to be loaded using MedusaApp.

What was the idea behind adding it in the first place? Just curious as it is quite a significant change 😄

**Review by olivermrbl — APPROVED** [review]

**Comment by carlos-r-l-rodrigues** [comment]
> > No, not directly related to it. This check is preventing "legacy" modules (inventory and stock-location) to be loaded using MedusaApp.
> 
> What was the idea behind adding it in the first place? Just curious as it is quite a significant change 😄

Just as a safe guard to do not use this method to load legacy modules in the core. But we missed the point that any app can use MedusaApp to load whatever module.
Now the core is registering legacy modules as before and using MedusaApp for new ones.

**Review by adrien2p — APPROVED** [review]
LGTM, if we can end up having only the medusa app that loads the modules since we are merging the config, it would be nice, then we just need to get the container to register them in the core. wdyt?

**Pull request merged**
