### PR TITLE
feat(typeorm): Upgrade Typeorm to V3

### PR DESCRIPTION
**Pull request by juanzgc**
This PR references https://github.com/medusajs/medusa/pull/2294 so all credit to Adrien for laying the groundwork.

Unfortunately, migrating Typeorm becomes very difficult as new code continues to be committed. Therefore, I created this PR which **only** focuses on the migration. This PR limits the amount of code changes in the Service and Repository repos to prevent **as many** painful merge conflicts.

I believe with this PR we can actually move forward with migrating to Typeorm V3.

The overall goal is to eventually fix: https://github.com/medusajs/medusa/issues/2054 which I believe will improve Developer Experience when using the medusa-extender.

### CODE REVIEW

**Comment by juanzgc** [comment]
@adrien2p Hopefully this helps a bit with the painful migration 😇 I tried my best to limit the amount of possible merge conflicts to make migrating actually _doable_

Thanks to your new `buildQuery` util this was made possibly 😄 It's also important to note we don't require updating the current format of `relations` since Typeorm V3 can handle both formats.

**Comment by mariusa** [comment]
@olivermrbl could this be considered, please? The longer it waits, the more painful to rebase. Thanks

**Comment by olivermrbl** [comment]
@mariusa Sorry for letting your message hang. We are discussing the migration this week and will hopefully be able to get back to you with a clear timeline for when this will be prioritized and eventually released :)

**Comment by olivermrbl** [comment]
@juanzgc We highly appreciate your contributions to the migration. We will use your branch as a foundation for continuing the work, but split it into smaller, isolated PRs, that are easier to review.

We expect the migration to be finalized mid next week.

Closing for now.

**Comment by juanzgc** [comment]
@olivermrbl Thanks Oliver for prioritizing the Typeorm migration!

**Pull request closed without merging**
