### PR TITLE
feat(medusa): Allow using a custom database schema

### PR DESCRIPTION
**Pull request by josetr**
**What**
Allow custom database schema

### CODE REVIEW

**Comment by olivermrbl** [comment]
@josetr Have you tested these changes? I can't seem to make my local Postgres pick up the schema and migrate properly. 

Can I get you to add the steps for how to configure this? Would also help us add an entry in our documentation.

**Comment by josetr** [comment]
> @josetr Have you tested these changes? I can't seem to make my local Postgres pick up the schema and migrate properly.
> 
> Can I get you to add the steps for how to configure this? Would also help us add an entry in our documentation.

Sorry, I forgot to provide one important detail which is the `search_path` option that I thought wasn't needed anymore:

1) 
```.JS
module.exports = {
  projectConfig: {
    database_url: "postgres://postgres:postgres@postgres:5432/medusa-docker?options=-c search_path=test",
    database_schema: "test",
  },
```

2) npm run seed && npm run start

**Review by olivermrbl — APPROVED** [review]
LGTM - tested locally and worked as expected. Thanks for the contribution @josetr.

Looping in @srindom for approval. 

If merged, this would be great to include in our documentation @shahednasser 🙌

**Review by srindom — APPROVED** [review]

**Comment by oakbani** [comment]
@josetr  @shahednasser 
I think even if we don't set `database_schema: "test",`, it would work as expected due to having search_path in db url. Is this correct? I don't see this config database_schema being used in the code.

**Comment by oakbani** [comment]
I just tried this and it works as expected. The documentation is misleading.

**Comment by shahednasser** [comment]
@josetr can you confirm this?

**Comment by josetr** [comment]
@shahednasser I believe @oakbani is correct, the database connection string takes precedence.

**Comment by shahednasser** [comment]
Thanks for letting me know. I'll change the documentation based on this

**Pull request merged**
