### PR TITLE
fix: DML relation management for many to one relation ship foreign keys

### PR DESCRIPTION
**Pull request by adrien2p**
FIXES CORE-2369

cc @thetutlage

### CODE REVIEW

**Review by riqwan — APPROVED** [review]
🔥 mad magic!

**Review by olivermrbl — APPROVED** [review]

**Comment by adrien2p** [comment]
@olivermrbl i can see that you have merged without resolving the conflicts 😅

**Comment by olivermrbl** [comment]
@adrien2p, omg sorry – I attempted to resolve the conflicts in-line, but apparently I forgot to confirm the resolution before merging :'(

**Comment by olivermrbl** [comment]
I'll fix it

**Pull request merged**
