### PR TITLE
fix(product): when running migrations, prevent exploding on isolated case

### PR DESCRIPTION
**Pull request by riqwan**
**what:**

When executing the SQL in migrations, its currently throwing an error when products dont exist, but the catch is not stopping the migration from going through the fail route.

### CODE REVIEW

**Comment by riqwan** [comment]
@adrien2p - I'm not sure why this is here, but if its needed, I added a non exploding sql to check if table exists.

**Review by fPolic — APPROVED** [review]
LGTM!

**Comment by adrien2p** [comment]
Now that we have the if exists or not exists everywhere, couldn't we remove this totally?

**Comment by adrien2p** [comment]
PS: I love the changeset name "complain" 😂

**Review by adrien2p — APPROVED** [review]
LGTM

**Pull request merged**
