### PR TITLE
chore: refactor payment collection setPaymentSession

### PR DESCRIPTION
**Pull request by adrien2p**
**What**

Only use `setPaymentSessionsBatch` in `setPaymentSession` to reuse the logic as it is the same behavior. One for a unique session and the other one for multiple sessions.
This refactoring reduce the risk of introducing bugs when working around payment session if it needs to be changed (which is currently happening as part of the payment refactoring) and having to change it in less places instead of more and more places

### CODE REVIEW

**Comment by adrien2p** [comment]
@carlos-r-l-rodrigues I ll let you have a look at this pr. I would like to know if you think the checks in the setPaymentSession should be also present in the batch method. let me know

**Comment by carlos-r-l-rodrigues** [comment]
It looks good to me, but maybe we could avoid retriving the payment collection twice by changing the type on the batch method to:
`paymentCollectionOrId: PaymentCollection | string,` and passing it from `setPaymentSession`

**Comment by adrien2p** [comment]
> It looks good to me, but maybe we could avoid retriving the payment collection twice by changing the type on the batch method to:
> 
> `paymentCollectionOrId: PaymentCollection | string,` and passing it from `setPaymentSession`

Yes you are right 💪 glad that you suggested it, I did not wanted to change too much but i will include it

**Review by carlos-r-l-rodrigues — APPROVED** [review]
LGTM

**Review by olivermrbl — APPROVED** [review]
LGTM!

**Pull request merged**
