### PR TITLE
fix(admin-ui): disabling analytics when opted out

### LINKED ISSUE #4423: Disabling Telemetry
Even with these environment variables set as described here: https://docs.medusajs.com/usage:

```
MEDUSA_DISABLE_TELEMETRY=true
MEDUSA_FF_ANALYTICS=false
```

The admin is still making network calls to segment.com.

### PR DESCRIPTION
**Pull request by jporsay**
* fixes #4423 by either using the `useAnalytics` hook or using an ErrorBoundary specific instance

Also important when doing offline development with medusa admin. Unless I had this applied, application didn't load due to an exception bubbling on the creation of the `analytics` instance.

### CODE REVIEW

**Comment by jporsay** [comment]
Hey @adrien2p , sorry for pinging you, but can this PR get some attention? I've got another flight in the coming days and would love to be able to do some offline development using medusajs :)

**Comment by adrien2p** [comment]
Hey @jporsay thanks for the pr, we will have a look asap and let you know 👌

**Review by adrien2p — COMMENTED** [review]
Looks good to me, I would like @olivermrbl opinion on this one

**Comment by olivermrbl** [comment]
@kasperkristensen will you also have a look at this? 🙏

**Review by kasperkristensen — APPROVED** [review]
LGTM

**Comment by olivermrbl** [comment]
@jporsay, appreciate the contribution. Curious to hear what you are working on, if you don't mind sharing? :)

**Review by olivermrbl — APPROVED** [review]

**Pull request merged**
