### PR TITLE
fix(medusa): Performance improvement for variant availability

### PR DESCRIPTION
**Pull request by pKorsholm**
**What**
- refactor availability invocations to only do one call to the inventory module

@adrien2p would love to run through some tests of this with you and get your take on approach

### CODE REVIEW

**Review by olivermrbl — DISMISSED** [review]
LGTM!

**Comment by pKorsholm** [comment]
@olivermrbl would love to have a talk w/ @adrien2p about this before merging since he probably has opinions here 😉 

adding `blocked` label for now

**Comment by olivermrbl** [comment]
Sure, can I get you to add in the PR description, what you would like to discuss?

**Comment by olivermrbl** [comment]
Would it be possible to include benchmarks of the effect of these changes?

**Review by adrien2p — APPROVED** [review]
LGTM, good work 💪

**Comment by adrien2p** [comment]
> Would it be possible to include benchmarks of the effect of these changes?

The benchmark won't show much, but we go from 600 queries to 1 query instead, which has quite of an impact, instead of having the numbers of queries growing in correlation of the number of variants, it is constant :)

**Pull request merged**
