### PR TITLE
Allow using a custom cookie domain

### PR DESCRIPTION
**Pull request by josetr**

### CODE REVIEW

**Comment by pevey** [comment]
I think this is a great idea.  But does there need to be a check on this line to ensure that the option is not null?  

``
domain: session_options?.domain
``

I'm not sure how express-session handles a situation where the domain property is present but the value is null.

Edit: I'm also curious in what scenario you ran into an issue that prompted the PR.  I've wondered about this before. 
 I'm not quite sure how, but somehow even when the medusa backend is running on localhost but being proxied, it somehow sets the cookie for the correct domain.  I'm not sure if it is maybe the reverse proxy that is handling that.

**Comment by quiloos39** [comment]
Bump

**Comment by pevey** [comment]
I think this PR is dead and can probably be closed unless more info is added.  It's not clear the use case, and the implementation has the issue mentioned in my post above.

Note that setting the domain to something that is not the actual fully-qualified domain name that medusa is being served from will serve no purpose.  The browser will refuse to set the cookie if the domain set here does not match the origin the browser gets the cookie from.

**Comment by josetr** [comment]
I needed it to get the `medusaRequest` method (from the next storefront) to work with `options: {credentials: true}}`, otherwise the session cookie wouldn't be available ( my backend api is using a subdomain ).

As far as I've checked, 'express-session' won't do much with the domain value. IMO the right place to look for errors is to use Chrome DevTools. Any error that we provide will be much worse.

Regardless, I don't see a reason why this option shouldn't be added. It's straightforward and people will need it sooner or later.

**Comment by riqwan** [comment]
Hey, thanks for the PR! Since v2 brought a lot of architectural changes, we will be closing this PR since it no longer applies to our new setup.

If you would still like to open this PR, please rebase with the v1 branch and re-request a review & we'll get back on it quickly.

**Pull request closed without merging**
