### PR TITLE
fix(medusa): Allow deleting metadata fields

### PR DESCRIPTION
**Pull request by kasperkristensen**
**What**
- Updates the `setMetadata` method so that it will delete a field from an entity's metadata.

**How**
- If a key is passed with a value of `""` (empty string), the key is deleted from the entities metadata

**Why**
Currently, it is not possible to delete fields from metadata. This PR addresses this issue by allowing users to unset a metadata field by setting its value to an empty string. The empty string was chosen over `null`, as `null` may hold meaning to some users/plugins in some cases, and as such an empty string was seen as less intrusive/potentially breaking.

Still very much open to any input in regards to using an empty string/null for indicating a field should be unset.

**Testing**
- Added an integration test to validate that passing an empty string will unset the field.

### CODE REVIEW

**Review by patrick-medusajs — APPROVED** [review]
LGTM 🚀

Probably a niche case but the only drawback I could see if someone has declared an interface over their metadata. Typing on non-string fields in the metadata could be annoying.

```typescript
interface ProductMetadata = {
  "test-key"?: number
}
```
The above would throw a TS error when trying to assign `""` to delete the field.
`payload.metadata = { "test-key": "" }`

Would need to be rewritten as
```typescript
interface ProductMetadata = {
  "test-key"?: number | string
}
```

**Review by olivermrbl — APPROVED** [review]
LGTM, I think it makes sense to have a small note on this in our documentation, but I am not sure where to put it. @shahednasser do you have any ideas? Feels like an overkill to add it to all OAS in all update endpoints. Maybe define a metadata schema and add it in the description?

**Comment by shahednasser** [comment]
@olivermrbl If I'm not mistaken this allows deleting metadata fields in update requests right?

I think it's worth highlighting what metadata is in the first place and how most entities in Medusa have it. This can help guide developers in ways they can customize existing entities without actually having to customize their structure. => This can go into the [Entities conceptual guide](https://docs.medusajs.com/advanced/backend/entities/overview).

For the API reference, we can create a Metadata schema with multiple examples and description for those examples. So one example would be adding a metadata field and another deleting a metadata field. But we'd still need to update all the OAS update endpoints to use that metadata scheme. An alternative would be to add a how-to guide that is focused on managing metadata. However, although the second approach would be easier, most people using the API reference might not be aware of the how-to guide.

I would honestly rather do the first approach, even if it's a tedious task. We can create a metadata scheme and link it in update endpoints. The scheme itself can include the examples which would show up in the endpoint. We can also add a link to the metadata section in the conceptual guide (to be added as mentioned above) in the schema as a reference to what metadata is.

Let me know what you think, also curious about what @patrick-medusajs thinks since he's been working on OAS as well.

**Comment by olivermrbl** [comment]
> If I'm not mistaken this allows deleting metadata fields in update requests right?

Yes exactly!

> I think it's worth highlighting what metadata is in the first place

I agree, that would be great. I know our metadata concept is not as advanced as Shopify's, but I still think we can use [their documentation](https://help.shopify.com/en/manual/data-extensions/metafields) as inspiration for our own. 

-----

For the first iteration, I don't mind leaving out the OAS part of it. If we have an entry in our documentation that explains the metadata concept and how to use it, that should suffice for most cases.

That said, I agree, the OAS schemas are ideal. I'll let you and @patrick-medusajs decide on what to go with.

**Comment by shahednasser** [comment]
@olivermrbl yes of course. I'll create a Linear issue for this

**Comment by patrick-medusajs** [comment]
@shahednasser, please share with me the Linear issue once you have it.

**Comment by shahednasser** [comment]
Well I created only an issue for the entities section because I was waiting to hear your opinion on the OAS task. Should I go ahead and create an issue for a metadata OAS schema?

**Comment by patrick-medusajs** [comment]
yes please. Let's assume we will augment the OAS with metadata. Worst case, we will just close it if we decide to abandon the idea.

**Pull request merged**
