### PR TITLE
Feat/product collection images

### PR DESCRIPTION
**Pull request by edihasaj**

### CODE REVIEW

**Comment by edihasaj** [comment]
This PR is from https://github. com/medusajs/medusa/pull/1767

**Comment by srindom** [comment]
@edihasaj - looks like there is still a good amount of commits that are not related to this update; could you please clean out the commits that are not yours :)

**Comment by edihasaj** [comment]
> @edihasaj - looks like there is still a good amount of commits that are not related to this update; could you please clean out the commits that are not yours :)

Yes I saw that the merging did this. I'm gonna clean out other commits, and let you know. Thanks

**Comment by edihasaj** [comment]
I'll also refer [admin/631](https://github.com/medusajs/admin/pull/631) so that we have an idea

**Pull request closed without merging**
