### PR TITLE
feat(medusa): Add expanded relations to customer service query

### PR DESCRIPTION
**Pull request by pevey**
This PR addresses https://github.com/medusajs/medusa/issues/5091.

The relations in the expand parameter are now correctly passed in customerService query and returned by the route.

I will make a separate PR for proposed changes to the /store/auth endpoint so that you can decide to accept/reject them independently.

### CODE REVIEW

**Comment by fxmb** [comment]
Is there a date for when this will be merged? It is blocking us quite a bit since we want to introduce customer groups to our store

**Review by olivermrbl — COMMENTED** [review]
LGTM, could I get you to add an integration test?

**Comment by olivermrbl** [comment]
@fxmb – PR is good to go. Requested a test to ensure the functionality works as expected. You can expect it to be included in the coming release, provided the changes have been added before then.

**Comment by fxmb** [comment]
Was this included in the release? Couldnt find it in the list of fixes...

**Comment by fxmb** [comment]
Is there an expected date for the next release or a date when this will be included? Otherwise we will build a custom route but would like to avoid this...

**Review by olivermrbl — APPROVED** [review]

**Comment by riqwan** [comment]
Hey, thanks for the PR! Since v2 brought a lot of architectural changes, we will be closing this PR since it no longer applies to our new setup.

If you would still like to open this PR, please rebase with the v1 branch and re-request a review.

**Pull request closed without merging**
