### PR TITLE
feat(admin-ui): Implement allocations on draft orders

### PR DESCRIPTION
**Pull request by StephixOne**
**What**

Implements allocations UI components on draft orders. 

**Why**

As Draft Orders do not have sales channels, we cannot automatically create reservations. Adding the UI allows admins to create these reservation when working with a draft order.

Resolves CORE-1303

### CODE REVIEW

**Review by fPolic — APPROVED** [review]
LGTM!

**Comment by srindom** [comment]
I tried allocating a Draft Order with 3 items and ended up with this result:

CleanShot 2023-04-12 at 11 59 11@2x

**Comment by StephixOne** [comment]
> I tried allocating a Draft Order with 3 items and ended up with this result:
> 
> CleanShot 2023-04-12 at 11 59 11@2x

Yeah, seems that line item status there is not correct at all. Good spot, fixing 👍

**Comment by StephixOne** [comment]
@srindom Took a minute, but found where the problem was 😅. Good to re-check.

**Review by srindom — APPROVED** [review]
LGTM!

**Pull request merged**
