### PR TITLE
feat(dashboard): add customers domain

### PR DESCRIPTION
**Pull request by kasperkristensen**
**What**
- Adds customers domain with the following pages: list overview, details, edit, create, update password.

**Note**
Some things are in-complete and will be followed up in future PRs:

  - Table loading state
    - Awaiting design, will implement for all Tables once ready. 
  - Table filters
    - Will implement in separate PR and add to all table that uses queries that support it
  - Customer group section on the details page 
    - There is currently no good way to fetch customer groups related to a customer without overfetching, eg. expanding groups and fetching potentially 100s of groups in a single query. Will add section, with the ability to bulk remove and add from groups once this can be none in a less expensive way.
  - Metadata
    - Will add this across admin in a separate PR

CLOSES CORE-1647

### CODE REVIEW

**Comment by olivermrbl** [comment]
very nit: Any chance we can have the _copy to clipboard_ icon in-line instead of under?
image

**Comment by olivermrbl** [comment]
thought: Should we leave this out in the first iteration? I could imagine the flow of resetting customers' passwords would involve more steps e.g. sending out an email.

image

**Comment by olivermrbl** [comment]
todo: I can't exit the "double cancel conf." flow:

https://github.com/medusajs/medusa/assets/59018053/706df2e4-aa5a-4df7-a9e6-800f3fd13c71

**Comment by olivermrbl** [comment]
todo: I can't update customers with a registered account, because we pass the email:

https://github.com/medusajs/medusa/assets/59018053/3906e619-40bc-4a2f-b881-9a8aa4ddbfa8

**Comment by olivermrbl** [comment]
question: The navbar is off on mobile, but not sure if this will be addressed in a separate PR. I know we agreed not to put effort into a responsive design, but thought I'd call it out: 
CleanShot 2024-01-16 at 10 17 48

**Comment by kasperkristensen** [comment]
> question: The navbar is off on mobile, but not sure if this will be addressed in a separate PR. I know we agreed not to put effort into a responsive design, but thought I'd call it out: CleanShot 2024-01-16 at 10 17 48

This will be handled in a separate PR, Ludvig has done a responsive design for the topbar, just haven't gotten around to implementing it. 

> very nit: Any chance we can have the _copy to clipboard_ icon in-line instead of under? image

Yes, the JSON view is very placeholder right now will fix it in a separate PR

> thought: Should we leave this out in the first iteration? I could imagine the flow of resetting customers' passwords would involve more steps e.g. sending out an email.
> 
> image

I agree, which is why I also added the confirmation that stresses that you need to communicate this to the customer. I included it since I would argue this is a pretty essential CM feature so even though it is not that well fleshed out in Medusa it might still make sense to include it as it. Just to prevent store owners from having to do direct DB changes to help customers that struggle to reset their password.

**Comment by olivermrbl** [comment]
> I included it since I would argue this is a pretty essential CM feature so even though it is not that well fleshed out in Medusa it might still make sense to include it as it.

I agree it's an essential feature. But as long as we don't have a sophisticated RBAC, an email flow, or something similar, I would argue it could cause more harm than good, as anyone with access to admin can update other customers' passwords. 

The fact that you need to do it in the DB right now is actually perhaps a good layer of security until something else is in place. And since this is not supported in our admin right now, we won't be robbing existing users' of a feature.

Update: fwiw, I checked with Shopify and Magento, and they both eliminated the feature in their recent versions in favor of an email flow

**Review by olivermrbl — APPROVED** [review]

**Pull request merged**
