### PR TITLE
fix(utils): Symbol for Indian Currency

### PR DESCRIPTION
**Pull request by Faiyyaz**
The symbol for Indian currency seems to be incorrect.

Please merge the PR for the fix.

Thanks!

### CODE REVIEW

**Review by sradevski — APPROVED** [review]
Looks good, thanks! @Faiyyaz can you just please make the commit message more descriptive (eg. similar to the title of the PR)? Thanks!

**Comment by Faiyyaz** [comment]
@sradevski Can you let me know how to change the commit message?

**Review by sradevski — APPROVED** [review]

**Comment by sradevski** [comment]
> @sradevski Can you let me know how to change the commit message?

@Faiyyaz check https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History on how to make it so that you have a single commit. 

Alternatively you can do
```
git reset HEAD~3
```
add the new commit, and do 
```
git push --force-with-lease
```

**Comment by Faiyyaz** [comment]
@sradevski when this will be merged and available for usage?

I cannot use above git commands anymore since the develop has been recently updated

**Comment by Faiyyaz** [comment]
@sradevski Sorry i will raise a new PR with updated repository

**Pull request closed without merging**
