### PR TITLE
feat(admin-ui, medusa): Remove feature flag

### PR DESCRIPTION
**Pull request by pKorsholm**

### CODE REVIEW

**Comment by olivermrbl** [comment]
Isn't it fine to keep this flag until the reservations UI has been battle-tested?

**Comment by srindom** [comment]
> Isn't it fine to keep this flag until the reservations UI has been battle-tested?

Since this is an improvement to the inventory module which is already behind a feature flag, I would argue it's best to ship as is and treat bugs as things to be fixed on the inventory module and remove the reservations flag.

**Comment by olivermrbl** [comment]
> inventory module which is already behind a feature flag

We don't have a FF on the inventory module. Unless you mean the configuration of the module serves as an FF?

**Comment by pKorsholm** [comment]
> Unless you mean the configuration of the module serves as an FF?

it does. all modules registered are also registered in the featureflag router. We use the `inventoryService` key for the inventory routes and panels in admin

**Pull request merged**
