### PR TITLE
feat(medusa, inventory, stock-location): Remove unnecessary transaction usage in the modules and the list product end points

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
list, retrieve method shouldn't wrap themselves into a transaction automatically but instead should use the provided transaction if present and otherwise run outside a transaction. This improves the overall performances by a little factor but remove some bottleneck that transactions can create.

In the below example the set of data is composed of 300+ products with each 50 variants (15k+ variants) in totals 

Screenshot 2023-06-01 at 16 48 47

### CODE REVIEW

**Comment by carlos-r-l-rodrigues** [comment]
Nice improvement. 💯 

There are just a few other places where we have to pass the context to the read methods of the plugins. That's why the integration tests plugins are failing.

**Comment by adrien2p** [comment]
> Nice improvement. 💯 
> 
> 
> 
> There are just a few other places where we have to pass the context to the read methods of the plugins. That's why the integration tests plugins are failing.

Nice, I ll find them and fix them 💪

**Review by pKorsholm — APPROVED** [review]
LGTM!

**Review by pKorsholm — APPROVED** [review]
LGTM!

**Review by olivermrbl — APPROVED** [review]
LGTM, just need tests to pass :)

**Pull request merged**
