### PR TITLE
feat(orchestration, workflows-sdk): Add events management and implementation to manage async workflows

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
Add the missing implementation to enable events management for workflow processing as well as some fixes.
This is preliminary work to support long-running workflows and shouldn't impact the existing workflow.

this is an extract from [this](https://github.com/medusajs/medusa/compare/develop...feat/transaction-orchestrator-options)

### CODE REVIEW

**Comment by olivermrbl** [comment]
Can I get you to add a little more about what's included in the PR? 🙏

**Comment by adrien2p** [comment]
done @olivermrbl

**Comment by adrien2p** [comment]
@olivermrbl if you could give this one a review so that we can proceed and merge develop to our other pr's

**Comment by olivermrbl** [comment]
will do first thing in the morning :)

**Review by olivermrbl — APPROVED** [review]
Sorry, I can't provide much feedback to this. If it doesn't change the current state of workflows and the DX, we can move forward with this PR. 

I think it will be easier to discuss and review when we start to play around with it.

**Comment by adrien2p** [comment]
yes @olivermrbl it doesn't impact the current DX.

**Comment by adrien2p** [comment]
@carlos-r-l-rodrigues ready to proceed with this?

**Comment by olivermrbl** [comment]
🚢 ?

**Pull request merged**
