### PR TITLE
fix: allow null updates in discounts

### PR DESCRIPTION
**Pull request by pKorsholm**
**What**
- allow nulls in the update dto for promotions for: `ends_at`, `valid_duration` and `usage_limit`

**Why**
- to enable the admin client to remove the previously mentioned properties using the `medusa-react` client

### CODE REVIEW

**Comment by adrien2p** [comment]
@pKorsholm could you update the types in the entity as well please 😊

**Comment by adrien2p** [comment]
@pKorsholm could we add an integration test for that please :)

**Review by adrien2p — APPROVED** [review]
LGTM

**Comment by olivermrbl** [comment]
Fixed in #1545 but we might as well include these tests :)

**Review by olivermrbl — APPROVED** [review]

**Pull request merged**
