### PR TITLE
fix(medusa-payment-stripe): missing transaction on create payment

### PR DESCRIPTION
**Pull request by adrien2p**
**What**

Add missing transaction in the new stripe base service.
Also, now there is a number of intents equal to the number of expected sessions based on the number of providers instead of for example 3 payment intents for 2 providers.
The number of customers created on stripe is still equal to the number of intent when they are meant for different payment providers such as stripe + stripe blik

FIXES CORE-787

### CODE REVIEW

**Comment by adrien2p** [comment]
ready just to trigger the snap

**Comment by olivermrbl** [comment]
@adrien2p Snapshot is ready 💪

**Comment by LWJerri** [comment]
Hello! Can this PR resolve the possible errors from this issue? https://github.com/medusajs/medusa/issues/2601

**Comment by olivermrbl** [comment]
> Can this PR resolve the possible errors from this issue?

Yes, that is very likely! We are currently testing in staging. Feel free to give the snapshot version a go - the more tests, the merrier.

**Comment by LWJerri** [comment]
> > Can this PR resolve the possible errors from this issue?
> 
> Yes, that is very likely! We are currently testing in staging. Feel free to give the snapshot version a go - the more tests, the merrier.

Okay. We talk about it here - https://discord.com/channels/876835651130097704/1041669823043731466

**Comment by LWJerri** [comment]
No, it's still giving me errors.

**Comment by LWJerri** [comment]
image

image

image

**Comment by adrien2p** [comment]
@LWJerri can you try the last snap

**Review by olivermrbl — APPROVED** [review]
LGTM! Waiting for @LWJerri to run a test as well 💪

**Comment by LWJerri** [comment]
> LGTM! Waiting for @LWJerri to run a test as well 💪

No, still get this error ;(

**Comment by LWJerri** [comment]
```
lwjerri@LWJerri:~/medusa/medusa-store$ npm list
medusa-starter-default@0.0.1 /home/lwjerri/medusa/medusa-store
├── @babel/cli@7.19.3
├── @babel/core@7.20.2
├── @babel/preset-typescript@7.18.6
├── @medusajs/medusa-cli@1.3.4
├── @medusajs/medusa@0.0.0-snapshot-20221114182648
├── babel-preset-medusa-package@1.1.19
├── medusa-file-minio@1.1.1
├── medusa-file-s3@1.1.7
├── medusa-fulfillment-manual@1.1.31
├── medusa-interfaces@1.3.3
├── medusa-payment-manual@1.0.16
├── medusa-payment-paypal@1.2.6
├── medusa-payment-stripe@0.0.0-snapshot-20221114182648
└── typeorm@0.2.45
```

**Comment by olivermrbl** [comment]
@LWJerri Have you set up the Stripe webhook for the plugin?

**Comment by LWJerri** [comment]
> @LWJerri Have you set up the Stripe webhook for the plugin?

Yes.

**Comment by LWJerri** [comment]
We can meet in Discord channel and I show you my code.

**Comment by chemicalkosek** [comment]
If he disabled webhook it worked for him.

**Comment by adrien2p** [comment]
Yes the amount capturable updated webhook need to be disabled for now. Is that the one?

**Comment by olivermrbl** [comment]
Alright, let's proceed in Discord. Can I get you to create a fresh entry in the help forum? 

I think we should keep it out of this PR

**Pull request merged**
