### PR TITLE
fix(medusa): Fix hanging inventory item migration script 

### PR DESCRIPTION
**Pull request by pKorsholm**
**What**
- Wrap the batch creation of inventory items with a single transaction pr batch rather than have them each be a separate transaction

**How**
- Wrap each batch in a transaction
- Update interfaces for stock locations and inventory services to support passing contexts

**Why**
- Each variant in the batch would have it's own connection from the connection pool causing the migration to hang. Either running the migration sequentially or with a smaller batch size than the configured connection pool size would solve the issue (batch size would have to be n-1 where n is the size of the connectionpool). @adrien2p has theorized that the issue comes from concurrently creating a new transaction and overwhelming the connection pool. 100 transaction creating concurrently will try to get 100 connection from the pool which is higher than the number of available connections

**Discussion point**
How should the operation be wrapped in a transaction?
The solution for now wraps each batch in a transaction, meaning a partial migration is possible. However, It was also possible beforehand, but where it would causing a single variant to not be migrated, here a batch would fail.
A different take would be to wrap it all in a single transaction making the operation entirely atomic. 
wdyt?

### CODE REVIEW

**Review by adrien2p — APPROVED** [review]
LGTM

**Comment by olivermrbl** [comment]
@adrien2p did you have anything for the discussion point? If not, I will merge.

**Comment by adrien2p** [comment]
One thing, since a bbatch can succeed and the next one fail, it should be taken i to account it the query. We might want to only migrate the variants that have not inventory items no? So that if you re run, it will restart where it failed

Cc @pKorsholm

**Comment by pKorsholm** [comment]
@adrien2p I added a check to validate if product variant inventory items exist for the variant (i.e. attach has completed and not been reverted). I think that should suffice since, even if and I have no clue how, it fails to create the level but the attachement is persisted, levels can be created manually 😄 

wdyt?

**Review by adrien2p — APPROVED** [review]

**Pull request merged**
