### PR TITLE
feat(product): Add extra fields to product-collection model

### PR DESCRIPTION
**Pull request by imash96**
Many ecommerce website required to showcase there product collection on there homepage with description and thumbnail also allow to make collection active and inactive.

### CODE REVIEW

**Comment by imash96** [comment]
@adrien2p @fPolic @sgirones any one??

**Comment by imash96** [comment]
@adrien2p @fPolic @sgirones any one??

**Comment by imash96** [comment]
@adrien2p @fPolic @sgirones any one??

**Comment by imash96** [comment]
@adrien2p @fPolic @sgirones any one??

**Comment by imash96** [comment]
@adrien2p @fPolic @sgirones any one??

**Comment by carlos-r-l-rodrigues** [comment]
Hi @imash96,
thank you for the PR, but there are more things needed to create new fields on core modules.
We will consider to add these in the future, but for now, this kind of customization should be handled by your application using custom modules and links.

**Pull request closed without merging**
