### PR TITLE
Pass cart_id so that prices can be calculated correctly.

### PR DESCRIPTION
**Pull request by Arsenalist**
Fixes https://github.com/medusajs/medusa/issues/7362

### CODE REVIEW

**Comment by Arsenalist** [comment]
@adrien2p - possible to approve this? It's a small change which fixes a clear bug which is easily reproducible.

**Comment by adrien2p** [comment]
@olivermrbl wdyt? it sounds good to me

**Comment by Arsenalist** [comment]
> @olivermrbl wdyt? it sounds good to me

Will this be ported to 2.0 as well or is separate PR needed?

**Review by carlos-r-l-rodrigues — APPROVED** [review]

**Comment by Arsenalist** [comment]
Is this ok to be merged? Its a one line change.

**Comment by olivermrbl** [comment]
@Arsenalist, should be good. Will merge and include in the next release later this week :)

**Comment by Arsenalist** [comment]
@olivermrbl Thank you for merging. Can you please answer this question:

> Will this be ported to 2.0 as well or is separate PR needed?

**Pull request merged**
