### PR TITLE
docs: set rejectUnauthorized based on condition

### PR DESCRIPTION
**Pull request by gursuj**
The general guide for hosting the server tells users to set `ssl.rejectUnauthorized` to false for production environments. However, the provided code snippet doesn't check the environment while setting the value. Directly pasting it into `medusa-config.js` will cause database connection attempts made from a development environment to be rejected and you can't even login to the admin account.

The change only sets the ssl property to false if the environment is a non-development one.  ~I got this code suggestion from the Kapa bot on discord so not sure if this is the best way to do this.~ This code is taken from the [configuration docs](https://docs.medusajs.com/development/backend/configurations#database_extra) themselves.

### CODE REVIEW

**Review by shahednasser — APPROVED** [review]
Nice catch, thanks!

**Review by shahednasser — CHANGES_REQUESTED** [review]
Can I get you to run the `yarn lint:content` command in the `www/apps/docs` directory then commit the changes?

**Comment by gursuj** [comment]
Done. I'll make sure to run it in future PRs.

**Review by shahednasser — APPROVED** [review]
LGTM

**Pull request merged**
