### PR TITLE
feat(medusa): Add events for creating, updating, and deleting users to event bus

### PR DESCRIPTION
**Pull request by dwene**
I needed this feature and it seemed like a good one to contribute back.

### CODE REVIEW

**Comment by srindom** [comment]
Can you please rebase on develop so we get up to date :)

**Comment by srindom** [comment]
Looks like there are a couple of unit tests to check as well - also could I as you to add a changeset? :)

**Review by srindom — APPROVED** [review]
LGTM! Thanks for contributing 💜

**Comment by dwene** [comment]
Sure thing! I think I need help rerunning a flaky test :/

**Pull request merged**
