### PR TITLE
fix(medusa): Load legacy modules entities

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
Fix load default modules entities for legacy modules

### CODE REVIEW

**Comment by adrien2p** [comment]
@carlos-r-l-rodrigues can you double check please and put a review on it

**Review by carlos-r-l-rodrigues — APPROVED** [review]
LGTM

**Comment by olivermrbl** [comment]
OK to merge @adrien2p ?

**Comment by adrien2p** [comment]
Sure @olivermrbl

**Pull request merged**
