### PR TITLE
feat(dashboard): create shipment flow

### PR DESCRIPTION
**Pull request by fPolic**
**What**
- add "Mark shipped" to Fulfillment section

---

CLOSES CORE-2427

### CODE REVIEW

**Comment by olivermrbl** [comment]
It seems the bottom row has a darker background color than the rest:
CleanShot 2024-07-01 at 20 50 06

**Comment by olivermrbl** [comment]
Also, shouldn't the status still be `Fulfilled` and not `Awaiting shipping`? Where did the new status come from?

**Comment by fPolic** [comment]
Both are from [the design](https://www.figma.com/design/6iTfljFmXXsdYJV4mjUXX2/RMA-Flows-Q2-2024?node-id=16724-41754&t=ktDvampSZ6VJDexO-0). Should we use status "Fulfilled" instead?

**Comment by olivermrbl** [comment]
Ah sorry my bad, forget what I said then :D

**Review by olivermrbl — APPROVED** [review]
Nice LGTM

**Pull request merged**
