### PR TITLE
fix(medusa-react): Fix `production.min.js` causing invalid hook usage error in CJS environments

### PR DESCRIPTION
**Pull request by kasperkristensen**
**What**
- Changes the use of `dts-cli` to `tsup` for bundling `medusa-react`
- Removes dependency on `lodash` as it was causing issues with the build running in ESM, and for how little it was used it was easier to re-implement the 3 functions we used.

**Why**
- The previous approach to bundling was causing an issue with the latest version of `@tanstack/react-query` when used in a CJS project.

Looping you in @shahednasser, this also fixes the issue with `medusa-react` in Next.js projects, once this is released we can safely remove the workaround from our docs.

### CODE REVIEW

**Review by fPolic — APPROVED** [review]
LGTM!

**Review by olivermrbl — APPROVED** [review]
LGTM!

**Comment by olivermrbl** [comment]
@kasperkristensen Can I merge this one?

**Comment by kasperkristensen** [comment]
Yea sorry thought I had @olivermrbl

**Pull request merged**
