### PR TITLE
fix(medusa): Avoid unnecessary cart updates upon retrieval

### PR DESCRIPTION
**Pull request by dwene**
Fetch-cart was always updating the cart when a user was logged in, because there was a missing select for email. See the lines below:

```
// If there is a logged in user add the user to the cart
  if (req.user && req.user.customer_id) {
    if (
      !cart.customer_id ||
      !cart.email ||
      cart.customer_id !== req.user.customer_id
    ) {
      await cartService.update(id, {
        customer_id: req.user.customer_id,
      })
    }
  }
```

### CODE REVIEW

**Comment by olivermrbl** [comment]
Nice catch @dwene! Appreciate the contribution 💪

**Comment by olivermrbl** [comment]
Can I get you to add a changeset with a patch bump? 

To do so, you'll have to run:
1. `yarn changeset`
2. Choose `@medusajs/medusa`
3. Hit enter, hit enter
4. Write a short summary of the change
5. Commit + push

**Comment by olivermrbl** [comment]
@dwene Can I get you to update the PR?

**Comment by dwene** [comment]
@olivermrbl done!

**Review by olivermrbl — APPROVED** [review]
LGTM, waiting for the CI to pass 💪

**Comment by riqwan** [comment]
Hey, thanks for the PR! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket.

**Pull request closed without merging**
