### PR TITLE
fix(medusa): Ordering management using joins and pagination

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
In the example of the products, when listing the product and ordering by a deep relation, we end up having duplicated tuples. This is because in the product case when they have multiple variants and prices, indeed a product can appear at different levels of the pagination depending on the different prices ordering. In our case, we are trying to circumvent that by deduplicating each product ordered by attributing a row number and always getting the first one.

FIXES https://github.com/medusajs/medusa/issues/5800 https://github.com/medusajs/medusa/issues/5539

### CODE REVIEW

**Review by carlos-r-l-rodrigues — APPROVED** [review]
LGTM

**Comment by olivermrbl** [comment]
LGTM, let's hear the outcomes out of the snapshot testing before merging :)

**Review by pKorsholm — APPROVED** [review]
LGTM nice implementation and deduping of the query

**Comment by adrien2p** [comment]
For reference https://github.com/typeorm/typeorm/issues/6294

**Pull request merged**
