### PR TITLE
fix(medusa-interfaces, medusa-file-*): flag for streaming to a private bucket

### PR DESCRIPTION
**Pull request by fPolic**
**Why**
_Issue 1_
If we want to stream a file to a public bucket we have to use different API for different providers:
```
// MinIO
fileService.getUploadStreamDescriptor({..., usePrivateBucket: false})

// S3 & Spaces
fileService.getUploadStreamDescriptor({..., acl: "public-read"})
```

_Issue 2_
MinIO has different defaults when reading and writing a stream:
```
fileService.getUploadStreamDescriptor({fileKey: "tst"} // -> would upload to the private bucket
fileService.getDownloadStream({fileKey: "tst"} // -> would look for the file in the public bucket
```

**What**
- add `isPrivate` flag for streaming methods to be consistent across file plugins
- read and write streams from/to private buckets by default across file plugins

### CODE REVIEW

**Comment by pevey** [comment]
Would you want to maybe incorporate the changes from https://github.com/medusajs/medusa/pull/4756 in this PR while you are working on these file services?

**Comment by fPolic** [comment]
> Would you want to maybe incorporate the changes from #4756 in this PR while you are working on these file services?

This PR will only focus on aligning private/public bucket flags while your PR has a bit broader scope so think it's fine if we merge them separately.

**Review by olivermrbl — APPROVED** [review]
LGTM!

**Comment by olivermrbl** [comment]
Please add a changeset bumping all the packages :)

**Pull request merged**
