### PR TITLE
feat(utils): dml to graphql

### PR DESCRIPTION
**Pull request by carlos-r-l-rodrigues**
What:
 * Generates GraphQL schema from DML definition

CLOSES: FRMW-2683, FRMW-2684

### CODE REVIEW

**Review by adrien2p — APPROVED** [review]

**Review by riqwan — APPROVED** [review]
Nice! Can we also now generate types from this?

**Comment by riqwan** [comment]
Also, whats the goal with gql here?

**Comment by adrien2p** [comment]
> Nice! Can we also now generate types from this?

There is another pr for that 🤣

**Comment by adrien2p** [comment]
And the fields are typed https://github.com/medusajs/medusa/compare/feat/gql-to-types?expand=1

**Comment by riqwan** [comment]
@adrien2p that is 🔥

**Pull request merged**
