### PR TITLE
fix: Migration generator and generated migrations

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
Fix the migration generator as well as the generated migrations.
I havent noticed any other places where the same mistake was applied in our other migrations though 🤔 

FIXES: FRMW-2581

### CODE REVIEW

**Comment by thetutlage** [comment]
Do we have to fix existing migrations that has `alter column if exists`?

**Comment by adrien2p** [comment]
> Do we have to fix existing migrations that has `alter column if exists`?

as I mentioned in the description, I didn't find any other one, did you find some?

**Comment by adrien2p** [comment]
@thetutlage @olivermrbl do you think the changes to the down should be considered a breaking change? I dont think so but I d like to ask just in case

**Comment by thetutlage** [comment]
@adrien2p Nope. Also, in this case its a bug fix. I don't think that specific migration would have been reverted ever

**Review by olivermrbl — APPROVED** [review]

**Comment by olivermrbl** [comment]
Agree with @thetutlage

**Pull request merged**
