### PR TITLE
chores(medusa): cleanup registrations life time

### PR DESCRIPTION
**Pull request by adrien2p**
FIXES CORE-1302

### CODE REVIEW

**Comment by adrien2p** [comment]
@olivermrbl is that alright if i update the doc in that pr?

**Review by shahednasser — CHANGES_REQUESTED** [review]
@adrien2p we also need to change in the Create Service guide in the Service Life Time section that the default of custom services is scoped and not transient

**Comment by adrien2p** [comment]
@shahednasser done 👍

**Review by shahednasser — APPROVED** [review]
Docs LGTM

**Comment by adrien2p** [comment]
@olivermrbl could I get you to give a review on this one please

**Comment by olivermrbl** [comment]
@adrien2p Tests are failing.

**Comment by adrien2p** [comment]
> @adrien2p Tests are failing.

Sorry havn't seen that. Weird let me see

**Comment by adrien2p** [comment]
It was green before I merge develop in that pr @olivermrbl

**Comment by adrien2p** [comment]
@olivermrbl it is green

**Review by olivermrbl — APPROVED** [review]
LGTM!

**Pull request merged**
