### PR TITLE
chore: Make scheduled job tests reliable

### PR DESCRIPTION
**Pull request by sradevski**
Testing against a real service is a pain, so we can't do better unless we mock/fake some of the components

### CODE REVIEW

**Comment by carlos-r-l-rodrigues** [comment]
I believe instead of setting the timeout to wait, you could have a counter and only check the expect after that.
This way we avoid any issue if there is any delay executing the job because it is busy, etc...

```
function ExternalPromise(num) {
  let externalResolve;
  let externalReject;
  let counter = 0
  const promise = new Promise((resolve, reject) => {
    externalResolve = resolve;
    externalReject = reject;
  });

  return {
    next: () => {
       if(++counter === num) {
          externalResolve()
       }
    },
    promise,
    resolve: externalResolve,
    reject: externalReject
  };
}

it("should execute a scheduled workflow", async () => {
   const wait = ExternalPromise(3)
   const spy = createScheduled("standard", wait)
   await wait.promise
   expect(spy).toHaveBeenCalledTimes(3)
   WorkflowManager.unregister("standard")
})
```
and in `createScheduled` you execute `wait.next()`

**Comment by sradevski** [comment]
> I believe instead of setting the timeout to wait, you could have a counter and only check the expect after that. This way we avoid any issue if there is any delay executing the job because it is busy, etc...
> 
> ```
> function ExternalPromise(num) {
>   let externalResolve;
>   let externalReject;
>   let counter = 0
>   const promise = new Promise((resolve, reject) => {
>     externalResolve = resolve;
>     externalReject = reject;
>   });
> 
>   return {
>     next: () => {
>        if(++counter === num) {
>           externalResolve()
>        }
>     },
>     promise,
>     resolve: externalResolve,
>     reject: externalReject
>   };
> }
> 
> it("should execute a scheduled workflow", async () => {
>    const wait = ExternalPromise(3)
>    const spy = createScheduled("standard", wait)
>    await wait.promise
>    expect(spy).toHaveBeenCalledTimes(3)
>    WorkflowManager.unregister("standard")
> })
> ```
> 
> and in `createScheduled` you execute `wait.next()`

@carlos-r-l-rodrigues nice, I did something similar for waiting for the events, but I didn't think of using the same approach here 👍  Let me try it out

**Comment by sradevski** [comment]
@carlos-r-l-rodrigues done, much better

**Comment by carlos-r-l-rodrigues** [comment]
Nice... it looks good.

**Review by carlos-r-l-rodrigues — APPROVED** [review]

**Pull request merged**
