### PR TITLE
feat(medusa-react): Add custom hook factory to `medusa-react`

### PR DESCRIPTION
**Pull request by kasperkristensen**
**What**
- Adds custom `retrieve`, `list`, `create`, `update`, and `delete` endpoints to admin class of `medusa-js`
- Adds a custom hook factory to `medusa-react`
- Adds more `domain.details` injection zones
- Add more WidgetProps types

**Why**
- The hook factory makes it easier for developers creating admin extensions to interact with the Medusa server and provides developers with a way to invalidate queries across the admin for domains that are related to their custom logic. 

**How**
- `medusa-react` exports a new helper function: `useAdminCreateMutation`
- The function accepts the following props: `path: string`, `queryKey: QueryKey`, and `relatedDomains: RelatedDomains`
  - `path` is the base path to the custom endpoint. An example would be `/products/${product.id}/custom-relation`, the `/admin` prefix will be added automatically.
  - `queryKey` will be used to generate query keys for all of the `GET` hooks, and will be automatically invalidated when one of the mutation hooks succeeds. It uses the pattern as the remaining hooks in `medusa-react`.
  - `relatedDomains` is an object that users can use to specify related domains that should also be invalidated on successful mutations. An example would be if the custom logic is related to a product, and for that reason, it would also be beneficial to re-fetch products, which can be achieved by passing `{ product: true }`. This will invalidate `adminProductKeys.all` which will result in all products being re-fetched, while this may seem a bit excessive `@tanstack/react-query` is smart enough to only re-fetch the queries that are currently active, so it won't result in all queries being re-fetched simultaneously.
- The hooks returned by the helper function are generic, allowing developers to improve their DX by providing types for the functions and receive IntelliSense for the `query` param, the `payload`, and return data.

**Example usage**
```tsx
import { PostMyCustomRelationReq, MyCustomRelationRes } from "../../types"

const MyWidget = ({ product, notify }: ProductWidgetProps) => {
  const { useAdminCreateMutation } = createCustomAdminHooks(`/products/${product.id}/custom-relation`, "admin_custom_relation", { product: true })

  const { mutate } = useAdminCreateMutation<PostMyCustomRelationReq, MyCustomRelationRes>()

  const handleCreate = () => {
    mutate({
      name: "Test",
      isValid: true
    }, {
      onSuccess({ custom_relation }) {
        notify.success("Relation created", `A new relation ${custom_relation.name} was created`)
      }
    })
  }

  // ...
}

```

Closes CORE-1370, CORE-1383, CORE-1391

### CODE REVIEW

**Comment by molhar** [comment]
It looks like the docs referencing createCustomAdminHooks are live however the supporting code is not yet released?
https://docs.medusajs.com/medusa-react/overview#custom-hooks

**Comment by kasperkristensen** [comment]
Hi @molhar, it has been released on the beta version of medusa react. It’s missing a beta tag in the docs, thanks for pointing that out 😄

cc: @shahednasser

**Comment by molhar** [comment]
Thanks @kasperkristensen, that makes sense now :smiley:

**Pull request merged**
