### PR TITLE
chore: Use workspace deps to resolve local versions

### PR DESCRIPTION
**Pull request by olivermrbl**
- Brings back the optimizations introduced in #2727
- Prevents all packages from being published on every release

### CODE REVIEW

**Comment by olivermrbl** [comment]
@patrick-medusajs I would appreciate if you could give this a review

**Review by patrick-medusajs — COMMENTED** [review]
I like the `workspace:` prefix. I didn't know it existed, pretty neat. I would've assume that all local dependencies would be using `workspace:*`. This spawn the following questions:

* What would be the decision tree for using `workspace:*` vs `workspace:^x.y.z` when declaring a dependency, devDependency or peerDependency? 
* What would be the event that would require changing `workspace:^x.y.z` to `workspace:*`?

**Comment by patrick-medusajs** [comment]
@olivermrbl, friendly ping about the [comment above](https://github.com/medusajs/medusa/pull/3784#pullrequestreview-1379539982).

**Comment by olivermrbl** [comment]
> What would be the decision tree for using workspace:* vs workspace:^x.y.z when declaring a dependency, devDependency or peerDependency?

I went with:
- `devDependencies` always resolves the local workspace package -> `workspace:*`
- `dependencies` resolves the latest package within the semver range -> `workspace:^1.8.0`
- `peerDependencies` resolves the latest package within the semver range -> `workspace:^1.8.0`
- `integration-tests/*` `dependencies` always resolves the local workspace package -> `workspace:*`

But honestly, I don't think using one or the other matters too much. What is important is that we move away from fixed versions, and that requires a bump across all packages everytime a change has been made.

**Comment by patrick-medusajs** [comment]
If we don't think it matters much, I would keep it simple and recommend that we use `workspace:*` for all types of inter-dependencies within our monorepo. Less mental charge when working with dependencies.

**Pull request closed without merging**
