### PR TITLE
feat(admin-ui): add Tamil translation

### PR DESCRIPTION
**Pull request by prajjwalkumar17**
##Description

-> Tamil translation Admin UI.

Resolves: https://github.com/medusajs/medusa/issues/5346

### CODE REVIEW

**Review by VariableVic — CHANGES_REQUESTED** [review]
Please add your language to the `supportedLanguages` array in `packages/admin-ui/ui/src/i18n/index.ts`

**Comment by prajjwalkumar17** [comment]
I have added it please have a look @VariableVic

**Review by VariableVic — APPROVED** [review]
Nice work! Thanks

**Comment by prajjwalkumar17** [comment]
Don't know why but it shows not accepted in hactoberfest :) my second pr as well can i make more pr ?

**Comment by VariableVic** [comment]
> Don't know why but it shows not accepted in hactoberfest :) my second pr as well can i make more pr ?

That's weird, might take some time? Or do you get some error message? I've added the `hacktoberfest-accepted` label, lmk if that works.

**Comment by prajjwalkumar17** [comment]
Yeah it just came can you please add this label in this [PR](https://github.com/medusajs/medusa/pull/5461) as well thanks :)

**Pull request merged**
