### PR TITLE
feat(medusa): Option to override existing cron job

### PR DESCRIPTION
**Pull request by olivermrbl**
By default, creating a new cron job should override the existing one. 

Some users might want to have several jobs registered under the same name; in that case, we allow you to pass an option to keep the existing one.

Solves #2461

### CODE REVIEW

**Comment by adrien2p** [comment]
It looks good, few points i am thinking though:
- if we pass keepExisting, each time an instance restart, it will accumulate cron right?
- in case of multi process, if keepExisting, it will also create multiple cron right?
- also, it looks like no matter the options, the registerHandler will append the handler. So when the cron job is run, even if there is no duplicate, the handlers will be duplicated if i am right.

There is other issues as well. It might be easier to discuss that later?

**Comment by olivermrbl** [comment]
> I have few points i am thinking though:
> 
> * if we pass keepExisting, each time an instance restart, it will accumulate cron right?
> * in case of multi process, if keepExisting, it will also create multiple cron right?
> * also, it looks like no matter the options, the registerHandler will append the handler. So when the cron job is run, even if there is no duplicate, the handlers will be duplicated if i am right.

Valid points, but it is worth noting that these issues exist with the current implementation. I realise this is not perfect, but it is a step in the right direction without having to redo the entire concept of job scheduling. 

On point three, nice catch! I'll address that right away :)

**Review by adrien2p — APPROVED** [review]
LGTM it is working on my side. Only point 3 from the previous comment to integrate

**Comment by olivermrbl** [comment]
@adrien2p I am merging this PR - will keep your three comments for a follow-up iteration. Okay? :)

**Comment by adrien2p** [comment]
> @adrien2p I am merging this PR - will keep your three comments for a follow-up iteration. Okay? :)

Okay no problem

**Review by carlos-r-l-rodrigues — APPROVED** [review]

**Pull request merged**
