### PR TITLE
fix: missing relation when calculating total for cart, item.adjustments

### PR DESCRIPTION
**Pull request by dwene**
This was incorrectly calculating item prices with discounts applied when creating order from cart.

### CODE REVIEW

**Comment by dwene** [comment]
Hmmm, our issue was that free orders weren't skipping the payment process when completing the cart. When I added that line using the medusa extender, it solved our issue. What isn't working?

**Comment by dwene** [comment]
Or are you just saying there's an issue with the unit tests?

**Comment by dwene** [comment]
Aha, found the issue and fixed.

**Comment by dwene** [comment]
You cant fetch a cart with `line_items.adjustments`, insert the adjustments manually, and then save the cart without setting those adjustments on the line items. TypeORM gets confused.

**Comment by dwene** [comment]
At some point, it would be good to pick one pattern or another. Either update all the entites off `cart` in memory, or update them using their individual repositories, not both. I think might be doubling the number of updates called on the database.

**Comment by riqwan** [comment]
Hey, thanks for the PR! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket.

**Pull request closed without merging**
