### PR TITLE
feat(admin-ui): Add Bangla translations

### PR DESCRIPTION
**Pull request by bhNibir**
Added Bangla translation

### CODE REVIEW

**Comment by bhNibir** [comment]
resolved merge conflicts

**Review by VariableVic — APPROVED** [review]
LGTM, thanks!

**Review by olivermrbl — APPROVED** [review]

**Comment by olivermrbl** [comment]
@bhNibir can I get you to update your branch with latest from `develop`?

**Comment by bhNibir** [comment]
> @bhNibir can I get you to update your branch with latest from `develop`?

@olivermrbl thank you very much, I updated the latest version, now check and let me know if anything else.

**Comment by olivermrbl** [comment]
We are reworking how translations in admin are handled, so this will not be merged. However, we appreciate the contribution. Keep an eye out for our upcoming releases to know more about this update, and if you are still interested, we'd love to see a new PR then :)

**Pull request closed without merging**
