### PR TITLE
fix(medusa-telemetry): Fix import of InMemConfig

### PR DESCRIPTION
**Pull request by MortadaAK**
There is an issue with the import where the file exports the class as `exports.InMemoryConfigStore` not `exports.default`

and the output is 
```
/app/medusa/node_modules/medusa-telemetry/dist/store.js:37
      this.config_ = new _inMemoryConfig["default"]();
                     ^
TypeError: _inMemoryConfig.default is not a constructor
    at new Store (/app/medusa/node_modules/medusa-telemetry/dist/store.js:37:22)
    at new Telemeter (/app/medusa/node_modules/medusa-telemetry/dist/telemeter.js:42:19)
    at Object.<anonymous> (/app/medusa/node_modules/medusa-telemetry/dist/index.js:20:17)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Object.require.extensions.<computed> [as .js] (/app/medusa/node_modules/ts-node/src/index.ts:1445:43)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

### CODE REVIEW

**Comment by olivermrbl** [comment]
Thanks for the contribution and nice spotted. Can I get you to rebase off `develop`? I've changed the base branch.

**Comment by Guillaume-Dufour** [comment]
Any works around. We are impacted in version 1.4.1 when we lauch `medusa migrations run`

**Review by olivermrbl — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by olivermrbl** [comment]
Will be part of [next release](https://github.com/medusajs/medusa/releases/tag/untagged-cd8d41e4fca73096f7aa) 👍

**Comment by olivermrbl** [comment]
For some reason, the PR wont pass the CI. I will have to close and open a new one. But many thanks for the contribution 💪

**Pull request closed without merging**
