### PR TITLE
hotfix(medusa-js): bundle axios correctly and remove incorrect usage of dependency

### PR DESCRIPTION
**Pull request by kasperkristensen**
**What**
- Remove `form-data` dependency from `@medusajs/medusa`
- Tweak `rollup.config.js` so `axios` HTTP adapters are included when `@medusajs/medusa` is imported in a node environment (eg. build step or server side logic in a Next.js project).
- Rollback version of `axios` to `0.24.0`, as the updated version introduced a bug related to `headers: {
      'Content-Type': 'multipart/form-data'
    }`. Should be fixed in newer versions, but since those version introduces changes to the types, we will rollback the update for now.
- Adds a new type to `@medusajs/medusa-js` for the payload used by `admin.uploads.create` and `admin.uploads.createProtected` as they were incorrect. The new type is `File | File[]` allowing users to upload 1 or more files at a time, which is supported by the API but the JS client would throw a TS error. 

**Why**
Until this PR we have used `import FormData from "form-data"` in our JS client for handling file uploads. The dependency is a node package and should not be used in a browser environment, where the browser native FormData class should be used instead. This has previously not been an issue that caused errors because Axios corrected the mistake for us under the hood. 

When we switched to bundling the JS client with Rollup, I added the flag `browser: true` which prevented the axios adapters for node envs from being included in the bundle. As a result the misuse of `form-data` began throwing an error that `window is not defined` when code using the client was run in a node envionment.

This PR removes the dependency and instead uses the browser native capabilities, and tweaks the Rollup config so that both axios node and browser code is bundled, as this is needed when using the client in projects where parts of the code will be run in a node environment (eg. Next).

### CODE REVIEW

**Review by olivermrbl — APPROVED** [review]
LGTM, tested file upload + build ✅

**Comment by nekszt** [comment]
🙏 Thanks
Without this fix I can't use medusa-js@1.3.6 from the nextjs-starter (with deps upgraded)

Waiting for this fix to be merged in the next version.

For now I have to use
`yarn add @medusajs/medusa-js@1.3.7-snapshot-20230113142846`
`yarn add medusa-react@4.0.2-snapshot-20230112194226`
but I'm not sure about the snapshots

**Comment by kasperkristensen** [comment]
Closed in favor of #3038

**Pull request closed without merging**
