### PR TITLE
Chore: Fix typos

### PR DESCRIPTION
**Pull request by deining**
This PR fixes several typos I spotted in the project.

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Thanks for your contributions! Can I get you to remove all changes under `www/docs/content/references`? These are generated from the comments in the core, so making changes there is enough.

**Comment by deining** [comment]
> Thanks for your contributions!

You are welcome!

> Can I get you to remove all changes under `www/docs/content/references`?

Reverted all these changes, as requested.

**Review by shahednasser — APPROVED** [review]
LGTM!

**Review by shahednasser — COMMENTED** [review]
@deining can you run `yarn build` in the root of the monorepo and commit the changes you find under `packages/generated`?

**Comment by deining** [comment]
> @deining can you run `yarn build` in the root of the monorepo and commit the changes you find under `packages/generated`?

I did that, see my second commit to this PR with two changes in one single file.

**Pull request merged**
