### PR TITLE
fix(admin-ui): Remove t() on product.status update

### LINKED ISSUE #5388: Admin : translated status causes product publishing errors for non-english
### Describe the bug

When the user's language setting is set to a language other than English (in this case, French), it becomes impossible to publish/unpublish a product from the admin panel. An error message appears stating: "Erreur: status must be one of the following values: draft, proposed, published, rejected."

### System information

Medusa version (including plugins): 
```
    "@medusajs/admin": "^7.1.4",
    "@medusajs/cache-inmemory": "^1.8.7",
    "@medusajs/cache-redis": "^1.8.7",
    "@medusajs/event-bus-local": "^1.9.6",
    "@medusajs/event-bus-redis": "^1.8.9",
    "@medusajs/file-local": "^1.0.2",
    "@medusajs/inventory": "^1.10.0",
    "@medusajs/medusa": "^1.17.1",
    "@medusajs/stock-location": "^1.10.0",
    "@medusajs/ui": "^2.2.0",
    "medusa-file-minio": "^1.3.0",
    "medusa-fulfillment-manual": "^1.1.37",
    "medusa-interfaces": "^1.3.7",
    "medusa-payment-manual": "^1.0.23",
    "medusa-payment-paypal": "^6.0.2",
    "medusa-payment-stripe": "^6.0.3",
    "medusa-plugin-algolia": "^0.2.20",
```
Node.js version: 18
Database: pg

### Steps to reproduce the behavior

1. Go to the admin panel
2. Set the user's language to French
3. Attempt to publish or unpublish a product
4. See error message

### Expected behavior

I expect to be able to publish or unpublish a product regardless of the user's language setting.

### Additional context

It seems like the language setting is affecting the validation for product statuses, possibly due to localization issues. This is limiting the usability for non-English speaking users.

Additionally, upon inspecting the network traffic, it's evident that the POST request payload is sending the translated status. For instance, sending `"{status: "Brouillon"}"` instead of the expected enum values like `"draft"`. This might be the root cause of the issue.

### PR DESCRIPTION
**Pull request by olivermrbl**
Closes #5388

### CODE REVIEW

**Review by adrien2p — COMMENTED** [review]
LGTM, ahah the translation was applied on the property to update nice catch

**Review by adrien2p — APPROVED** [review]

**Review by fPolic — APPROVED** [review]
LGTM

**Pull request merged**
