### PR TITLE
chore: Add issue template for bug reports

### PR DESCRIPTION
**Pull request by olivermrbl**

### CODE REVIEW

**Review by srindom — APPROVED** [review]
LGTM!

**Comment by shahednasser** [comment]
@olivermrbl @srindom just a suggestion: I think using a `yml` file with a form format is a better experience. Check out my PR #1665 for an example of what I mean. You can also see [an example of the experience in Gatsby's repo](https://github.com/gatsbyjs/gatsby/issues/new?assignees=&labels=type%3A+bug&template=BUG_REPORT.yml).

**Comment by olivermrbl** [comment]
> I think using a `yml` file with a form format is a better experience.

Yeah, I was a bit on the fence irt. what format to use for the templates but ended up with a very simple skeleton. My take on the purpose of these templates is, that they should only set loose guidelines for the min. required information needed for us to respond to an issue because they vary so much in nature. Imo. the Gatsby one is quite strict and requires too many details for all issues to be applicable - could imagine that people would refrain from opening an issue as a result of this. I don't know if this is actually the case, but let's maybe give these a go?

**Comment by shahednasser** [comment]
I think that makes sense actually especially since bug reports can be more complex than documentation issues, so maybe these different formats make sense for these 2 use cases. I agree let's test it out and see if it works or not 🙂

**Pull request merged**
