### PR TITLE
Fix: Make total of cart minus any discounts gift cardable

### PR DESCRIPTION
**Pull request by Arsenalist**
This updates the gift cardable amount to equal the total of the cart minus any discounts. 

When the order is created from the cart, the existing logic works fine and applies the gift card to the whole amount. It is only when displaying the cart where the amount isn't being applied to all the totals in the cart.

Customers who are applying gift card expect the card to cover all balances since gift cards are a form of payment.

### CODE REVIEW

**Comment by Arsenalist** [comment]
Can I please get some feedback on whether this can be merged? This is my first contribution so I don’t know if I’m following the right process. Apologies if I am not. @chemicalkosek @adrien2p

**Comment by Arsenalist** [comment]
Anyone able to comment on this?

**Comment by adrien2p** [comment]
@Arsenalist Thanks for the pr, we will have a look and discuss about it, I just want to be sure the changes are the right one

**Comment by Arsenalist** [comment]
> @Arsenalist Thanks for the pr, we will have a look and discuss about it, I just want to be sure the changes are the right one

Hi, is there an ETA when this could be potentially merged? I'm ready to release gift cards to my customers but don't want to have the cart showing the wrong information (even though the order part works as expected).

**Comment by adrien2p** [comment]
I ve open a more complete pr here https://github.com/medusajs/medusa/pull/5075 and we just need to discuss it to be sure se don't introduce any unforeseen bug and then we will merge it.

**Comment by riqwan** [comment]
Hey, thanks for the PR! Since v2 brought a lot of architectural changes, we will be closing this PR since it no longer applies to our new setup.

If you would still like to open this PR, please rebase with the v1 branch and re-request a review & we'll get back on it quickly.

**Pull request closed without merging**
