### PR TITLE
feat: Add http integration tests and enable them in pipeline

### PR DESCRIPTION
**Pull request by sradevski**

### CODE REVIEW

**Review by olivermrbl — APPROVED** [review]
LGTM, but would also like buy-in from the rest 😄

**Comment by sradevski** [comment]
@olivermrbl yup agreed, I'll wait before merging and ask people again to leave feedback :)

**Review by carlos-r-l-rodrigues — APPROVED** [review]

**Review by adrien2p — APPROVED** [review]
Completely fine with the approach 💪

**Review by thetutlage — APPROVED** [review]

**Review by riqwan — APPROVED** [review]
lgtm!

Just as an alternate thought - since modules contain mostly http specs, should we just rename the modules tests to http?

**Pull request merged**
