### PR TITLE
fix(dashboard): Tab behaviour in DataGrid

### PR DESCRIPTION
**Pull request by kasperkristensen**
**What**
- Fixes "Tab" behaviour in DataGrid component.
- Removes FocusTrap dependency, and prop-types dependency as it is no longer needed now that we have removed FocusTrap.
- Adds hotkeys for moving the focus outside of the grid. `Ctrl + Alt + ,` to move focus to before the grid, and `Ctrl + Alt + .` to move it to after the grid.

Resolves CC-414, CC-397

### CODE REVIEW

**Review by olivermrbl — COMMENTED** [review]
Tab behavior works nicely, but I couldn't get the other new keys to work with the instructions provided in the PR description 🤔

**Review by olivermrbl — COMMENTED** [review]
Anyway, I don't think that should block the PR necessarily

**Comment by kasperkristensen** [comment]
@olivermrbl should be good now

**Review by olivermrbl — APPROVED** [review]
LGTM

**Pull request merged**
