### PR TITLE
Refactor(medusa): Create a base entity for common columns

### PR DESCRIPTION
**Pull request by adrien2p**
**Goal**
- Creating a new `BaseEntity` that holds the common column such as `id`, `created_at`, `updated_at` as well as the id generation method
- Add `SoftDeletableEntity` that will extends the above `BaseEntity` and hold everything related to soft deletion (at the moment only the `deleted_at` column

### CODE REVIEW

**Review by zakariaelas — APPROVED** [review]
Very nice! Love the idea! LGTM 😄 

Also curious to know if you thought about mixins along the way, I think it could fit nicely with our use case. I've noticed that some entities (`GiftCardTransaction`, `IdempotencyKey`, etc.) do not make use of the `generateId` method .. I suppose this is because `created_at` and/ore `updated_at` are not defined in the entity, so it might have felt too awkward to extend `BaseEntitity`. I think mixins might solve this neatly because it would allow us to compose different utility classes (and as a result get around the single inheritance constraint of typescript) in a way similar to this one:

```typescript

interface ClassType<T = any> {
  new (...args: any[]): T;
}

function WithId<TBase extends ClassType>(BaseEntity: TBase) {
  class IDEntity extends BaseEntity {
    @PrimaryColumn()
    id: string

    generateId(prefix: string): void | false {
      if (this.id) {
        return false
      }
      const id = ulid()
      if (!prefix) {
        throw new Error(
          `Missing static property prefixId from the model ${this.constructor.name}`
        )
      }
      this.id = `${prefix}_${id}`
    }
  }

  return IDEntity
}

function WithTimestamps<TBase extends ClassType>(BaseEntity: TBase) {
  class TimestampClass extends BaseEntity {
    @CreateDateColumn({ type: resolveDbType("timestamptz") })
    created_at: Date

    @UpdateDateColumn({ type: resolveDbType("timestamptz") })
    updated_at: Date
  }

  return TimestampClass
}

// in usage

@Unique("gcuniq", ["gift_card_id", "order_id"])
@Entity()
class GiftCardTransaction {
  @PrimaryColumn()
  id: string

  @Column()
  gift_card_id: string

  @ManyToOne(() => GiftCard)
  @JoinColumn({ name: "gift_card_id" })
  gift_card: GiftCard

  @Index()
  @Column()
  order_id: string

  @ManyToOne(() => Order)
  @JoinColumn({ name: "order_id" })
  order: Order

  @Column("int")
  amount: number

  @CreateDateColumn({ type: resolveDbType("timestamptz") })
  created_at: Date
}

export default class GiftCardTransactionId extends WithId(GiftCardTransaction) {
  @BeforeInsert()
  private beforeInsert(): void {
    this.generateId('gc')
  }
}

```

Definitely a bit verbose and plain inheritance is much simpler to reason and think about, so we definitely don't have to use this, just interested to hear your thoughts on a similar approach/pattern 😄

**Comment by adrien2p** [comment]
Ahah yeah @zakariaelas I indeed though about the mixin approach but I am not sure it is yet relevant for us at the moment. But this is the approach I used to be able to allow the users of the extender to extend the repositories from medusa core (with a custom impl so ce it is a specific case) 😊 but definitely something to keep in mind for future use like auth strategies or customisation.

At the moment, I think the mixin are superfluous in the sens of it would be a lot of classes that only add one thing which in the end you can just add as a column. 

Generally, the only common thing in entities are the timestamps since the id generation can be handled by the database, but I will suggest that later since it is not a priority and works well at the moment.

But really glad that you thought about that 😉 I hope what I said make sense.

**Comment by zakariaelas** [comment]
Thanks a lot @adrien2p for the detailed answer ❤️! What you said makes a lot of sense. I also think extracting the function for generating the ids would be a good idea 👍

**Comment by adrien2p** [comment]
> Thanks a lot @adrien2p for the detailed answer ❤️! What you said makes a lot of sense. I also think extracting the function for generating the ids would be a good idea 👍

I will move that PR to require changes and make the changes then. thank you @zakariaelas ❤️

**Comment by adrien2p** [comment]
@zakariaelas i ve extracted the method but I hesitate between what Ive done and Something like

this.id = generateEntityId(this.id, "prefix")

Wdyt?

**Comment by adrien2p** [comment]
@zakariaelas I will finally go for the second options which give us more control

**Review by olivermrbl — APPROVED** [review]
LGTM, this is so nice! 🙌 Will let @srindom have a glance as well

suggestion: We don't have a section in our docs on how to add models to your Medusa project, so I think it would be great to accompany this refactor with that. Wdyt @shahednasser?

**Comment by adrien2p** [comment]
@olivermrbl this is a great idea a documentation would be very nice with it

**Comment by adrien2p** [comment]
@shahednasser where should I add this part about how to create custom entities as part of the documention?

**Comment by shahednasser** [comment]
@adrien2p you can create an issue and assign it to me

**Pull request merged**
