### PR TITLE
feat(medusa): Performance improvement of listing shipping options

### PR DESCRIPTION
**Pull request by adrien2p**
Prod response time (named "rp" below): 7s
Local rp: 4.5s

After changes

Local rp: 16-60ms

Overall improvement up to x250

The side effect of this should be felt on every endpoint rp

FIXES CORE-813

### CODE REVIEW

**Comment by adrien2p** [comment]
Screenshot 2022-11-19 at 00 42 51

**Comment by adrien2p** [comment]
New results

Screenshot 2022-11-20 at 00 35 45

**Comment by olivermrbl** [comment]
@adrien2p Can I get you to add a changeset and update the PR description to include the change made in the `TransactionBaseService`?

**Review by olivermrbl — APPROVED** [review]
LGTM, absolutely amazing performance improvements - great work 😍

**Pull request merged**
