### PR TITLE
Feat/define mikro orm configuration dev

### PR DESCRIPTION
**Pull request by adrien2p**
FIXES CORE-2357

### CODE REVIEW

**Review by olivermrbl — APPROVED** [review]
LGTM

**Review by riqwan — APPROVED** [review]
🥇

**Review by sradevski — APPROVED** [review]
Nice 👍 Would it make sense to add the migration generation to our CLI, considering the DML is controlled by us anyway?

**Comment by adrien2p** [comment]
@sradevski it has been breifly discussed this morning and for now we didn't see the need but it can be reavulated later on when we move forward and have a better idea/understanding of each pieces

**Pull request merged**
