### PR TITLE
feat(orchestration,workflows-sdk): Skip step

### PR DESCRIPTION
**Pull request by carlos-r-l-rodrigues**
What:
 - Transaction Orchestrator `skipStep`
 - new response object for workflows-sdk: `StepResponse.skip()`

### CODE REVIEW

**Review by adrien2p — APPROVED** [review]

**Comment by adrien2p** [comment]
As discussed we can add it to the WHEN when it is false to have the info it has been skipped

**Comment by adrien2p** [comment]
CC @thetutlage we can return `StepResponse.skip` from our placeholder step once this pr is merged 👍 
ref: feat/workflow-hooks

**Comment by thetutlage** [comment]
What's the purpose of skip? Is it to ignore the return value or to create a dummy step without any invokeFn?

**Comment by adrien2p** [comment]
> What's the purpose of skip? Is it to ignore the return value or to create a dummy step without any invokeFn?

Mostly to have its real state and being able to display it properly. Instead of marking it as run and success but nothing really ran. Same when you apply the when conditional util

**Review by olivermrbl — APPROVED** [review]

**Pull request merged**
