### PR TITLE
Docs: add git as in the prerequisites section of the Quickstart Guide

### PR DESCRIPTION
**Pull request by akarsh-jain-790**
- What - Fixes: #2850 

- Why - git in the prerequisites section of the Quickstart Guide needed to be added.

- How - Following the guideline in the issue made the changes to medusa/docs/content/quickstart/quick-start.md

- Testing - No test written because it's a markup file.

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Thank you for your contribution @akarsh-jain-790 ! Instead of adding all the steps, can you just add that git is required with a link to how to install it from the [Set up your dev environment](https://docs.medusajs.com/tutorial/set-up-your-development-environment) documentation?

**Comment by akarsh-jain-790** [comment]
> Thank you for your contribution @akarsh-jain-790 ! Instead of adding all the steps, can you just add that git is required with a link to how to install it from the [Set up your dev environment](https://docs.medusajs.com/tutorial/set-up-your-development-environment) documentation?

@shahednasser I have updated the PR, you can re-review now.

**Review by shahednasser — CHANGES_REQUESTED** [review]
Since you added a subheader "Git" can you add one for Node.js as well?

**Comment by akarsh-jain-790** [comment]
> Since you added a subheader "Git" can you add one for Node.js as well?

Sure, will add a subheader for Node.js as well.

**Comment by akarsh-jain-790** [comment]
> Click here to learn what changesets are, and how to add one

Done, you can review now.

**Review by shahednasser — APPROVED** [review]

**Comment by shahednasser** [comment]
Thanks! @akarsh-jain-790

**Pull request merged**
