### PR TITLE
docs(development): update typescript code examples

### PR DESCRIPTION
**Pull request by ikhvost**
### Overview
This PR includes updates and corrections to the TypeScript code examples in the Medusa.js documentation. The aim is to enhance clarity, accuracy, and usability for developers who rely on these examples for implementing Medusa.js in their projects.

### Changes Made
Corrected syntax errors in TypeScript code snippets.

### Reason for Changes
The previous TypeScript examples contained several syntax errors that could lead to confusion or errors for developers. By updating these examples, we ensure that the documentation remains a reliable and up-to-date resource.

### Additional Notes:
* All changes were made in the /docs directory.
* No impact on the actual codebase or functionality of Medusa.js.

### CODE REVIEW

**Review by shahednasser — APPROVED** [review]
LGTM! Thank you for your contribution @ikhvost

**Comment by riqwan** [comment]
@shahednasser are these still relevant? Looks like the merge didn't pan out

**Comment by shahednasser** [comment]
Yea this should've been merged but should be rebased to `v1.x` branch instead.

**Comment by riqwan** [comment]
Hey @ikhvost, can you point this to v1 branch instead and resolve any conflicts? We can get this one merge right after 🤞🏻

**Pull request merged**
