### PR TITLE
chore: Ignore `admin-ui` in core test pipeline

### PR DESCRIPTION
**Pull request by olivermrbl**

### CODE REVIEW

**Review by pKorsholm — APPROVED** [review]
LGTM!

**Comment by kasperkristensen** [comment]
@olivermrbl Why are we ignoring `admin-ui`? It needs to be build. The `yarn build` command only builds the API in `/src`, and is needed as `@medusajs/admin` uses this API when building the dashboard found in `/ui`.

**Comment by olivermrbl** [comment]
@kasperkristensen I am ignoring it in the test workflows. Do we need to build it for those to pass? 🤔

**Comment by olivermrbl** [comment]
Merging this now, as we will have many UI PRs being opened in the coming days.

**Pull request merged**
