### PR TITLE
added missing keys and rearranged the json file according to en

### PR DESCRIPTION
**Pull request by its-kunal**
Added missing keys and rearranged the JSON file according to the English translation JSON file.

Fixes - #5491

### CODE REVIEW

**Comment by its-kunal** [comment]
@VariableVic please review my pull request, fixes issue #5491

**Comment by its-kunal** [comment]
@olivermrbl please review my pull request, fixes issue #5491

**Comment by its-kunal** [comment]
@VariableVic, @olivermrbl or any one from maintainers please review my pull request.

**Comment by its-kunal** [comment]
@VariableVic, @olivermrbl please review my pull request

**Comment by olivermrbl** [comment]
We are reworking how translations in admin are handled, so this will not be merged. However, we appreciate the contribution. Keep an eye out for our upcoming releases to know more about this update, and if you are still interested, we'd love to see a new PR then :)

**Pull request closed without merging**
