### PR TITLE
feat(dashboard): manage groups from customer details

### PR DESCRIPTION
**Pull request by fPolic**
**WHAT**
- add support for adding customers to multiple customer groups from the customer details page
- remove customer from a group on the customer details page
- fix issue with unresponsive UI after prompt disaply

### CODE REVIEW

**Comment by olivermrbl** [comment]
Should the row be selectable?
CleanShot 2024-05-16 at 12 56 02

**Comment by olivermrbl** [comment]
After removing the customer, I can''t interact with anything. We've had this many times by now. Do we know what is going on? And can be fix it more generally, so we don't miss it in the future 😄

**Comment by fPolic** [comment]
> After removing the customer, I can''t interact with anything. We've had this many times by now. Do we know what is going on? And can be fix it more generally, so we don't miss it in the future 😄

~~Yep it's the issue with prompt rendering in a different root~~ , I'll look into it now

EDIT: should be fixed

**Review by olivermrbl — APPROVED** [review]
LGTM!

@kasperkristensen would be good to have you look through it too

**Pull request merged**
