### PR TITLE
Product in multiple collections

### PR DESCRIPTION
**Pull request by maxpanakov**
Hi, i started work on  this  feature: https://github.com/medusajs/medusa/issues/2165, not finished yet, i'm waiting for your feedback,if everything is fine, I'll continue working on that.

### CODE REVIEW

**Comment by srindom** [comment]
Hi @maxpanakov! Thanks for contributing - we would be happy to accept a PR for this a couple of things to make sure is covered:

- DiscountConditions on collections
  - Should be modified to work similarly to DiscountConditions for product tags
- Importing and Exporting products 
  - Should be possible to import a product and associate it with multiple collections; similar to what is done with Sales Channels
  - When exporting there should be a full overview of collections
- This change can likely not be made backward compatible, but you should consider adding a data migration that takes care of changing data for users who have existing products/collections in their DB
- Finally, this will also require changes in medusajs/admin

If we can get all this into good shape we'd love to include it :)

**Comment by maxpanakov** [comment]
@srindom, I'm not sure about the migration command.
In the script file, I'm thinking of something like this:
1) add a new table
2) update the relationship from collection_id to collections
3)remove the collection_id column from the products table
is it possible not to create a migration file ? What is the best way for users who have existing products/collections?

**Comment by srindom** [comment]
@maxpanakov - we place data migration scripts here: https://github.com/medusajs/medusa/tree/master/packages/medusa/src/scripts

It is then the user's responsibility to run the script after they have upgraded; we will include this step in the upgrade guide for the version.

**Comment by maxpanakov** [comment]
@srindom  any further comments on pr ?  Can you review ?

**Comment by maxpanakov** [comment]
Hi, can  you check my branch, there is still a lot of work left to rewrite the test and meta. I want to make sure I'm going in the right direction before I continue working

**Comment by riqwan** [comment]
Hey, thanks for the PR! Since v2 brought a lot of architectural changes, we will be closing this PR since it no longer applies to our new setup.

If you would still like to open this PR, please rebase with the v1 branch and re-request a review.

**Pull request closed without merging**
