### PR TITLE
Fix mark draft order endpoint wrong in medusa js

### PR DESCRIPTION
**Pull request by RishiKumarRay**
#1038

### CODE REVIEW

**Comment by RishiKumarRay** [comment]
I don't know even the with the new request also these all commits got added

**Comment by srindom** [comment]
It is most likely because you have branched out from the master branch.

The right flow is:

```
git checkout develop
git checkout -b fix/mark....
```

**Comment by RishiKumarRay** [comment]
@srindom Actually i have done as you stated first i checkout out to develop branch then cut a new branch from develop but it is still there

**Comment by srindom** [comment]
Hmm.. alright that is a bit weird

**Comment by srindom** [comment]
A rebase should do the job though. Otherwise you can try:

```
git checkout develop
git checkout -b fix/...
git cherry-pick 422f91c
```

And then create a new PR from the resulting branch :)

**Comment by srindom** [comment]
And then please remember to open the PR against the develop branch :)

**Comment by RishiKumarRay** [comment]
ok let me try this , thanks

**Pull request closed without merging**
