### PR TITLE
chore: Internal medusa service proper typings with DML

### PR DESCRIPTION
**Pull request by adrien2p**
FIXES CORE-2372

### CODE REVIEW

**Comment by thetutlage** [comment]
Will DML types be imported from a subpath like?

```ts
import { Infer } from '@medusajs/types/dml'
```

**Review by sradevski — APPROVED** [review]
Nice 👍

**Comment by adrien2p** [comment]
> Will DML types be imported from a subpath like?
> 
> ```ts
> import { Infer } from '@medusajs/types/dml'
> ```

We can do that later if we want (which I like and would prefer, but the convention is different 😄 ) but for now the usage is 
- `import { Infer } from "@medusaj/types`
- `import { DmlType } from "@medusaj/types`
  - `DmlTypes.Infer`

**Comment by thetutlage** [comment]
> We can do that later if we want (which I like and would prefer, but the convention is different 😄 ) but for now the usage is

Okay, but then our naming is too generic for now. So maybe, I another PR we can make these names more specific to DML

**Review by thetutlage — APPROVED** [review]

**Comment by adrien2p** [comment]
Yes @thetutlage I think about that everytime but you can still import from the bundle export alias so i think it is ok for now and it will only be used internally as of now right? At least for most cases. But at some point it would be noce to short to subpaths instead for all bundles export

**Pull request merged**
