### PR TITLE
feat: Csv cell formatter should take into account coma and semicolon

### PR DESCRIPTION
**Pull request by adrien2p**
Same as with new lines, if there is a coma or semicolon, wrap/unwrap the cell in order to avoid separator collision

FIXES CORE-906

### CODE REVIEW

**Comment by RegisHubelia** [comment]
@adrien2p - which csv did you use for the import?  I get the error:  "errors": [
    "Cannot mark a batch job as pre processed if it is not in created status"
  ], when trying with the csv file with the collections...

**Comment by adrien2p** [comment]
@RegisHubelia I used the export_from_medusa....csv

**Comment by adrien2p** [comment]
what is your job status at the moment?

**Comment by RegisHubelia** [comment]
Failed - and looking at the jsonb field result in the table batch_job - I get the above error array...

**Comment by RegisHubelia** [comment]
Looking at the batch process from:
BATCHJOB BatchJob {
  dry_run: true,
  id: 'batch_01GM5TYCZS3GM1NAFYMH6R82EM',
  created_at: 2022-12-13T13:31:49.620Z,
  updated_at: 2022-12-13T13:31:51.304Z,
  deleted_at: null,
  type: 'product-import',
  created_by: 'usr_01GK9BQTK05BZ3NRKQHA5QSMAZ',
  context: { fileKey: 'product-export-Price_No_Formula_Dec12_intact.csv' },
  result: {
    count: 37040,
    operations: {
      PRODUCT_CREATE: 0,
      PRODUCT_UPDATE: 14497,
      VARIANT_CREATE: 0,
      VARIANT_UPDATE: 22543
    },
    stat_descriptors: [ [Object] ],
    advancement_count: 0
  },
  pre_processed_at: 2022-12-13T13:33:35.624Z,
  processing_at: null,
  confirmed_at: null,
  completed_at: null,
  canceled_at: null,
  failed_at: null,
  status: 'pre_processed'
}
::1 - - [13/Dec/2022:13:33:39 +0000] "POST /admin/batch-jobs/batch_01GM5TYCZS3GM1NAFYMH6R82EM/confirm HTTP/1.1" 200 854 "http://localhost:7000/" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
QUERYYYYYY { where: { id: 'batch_01GM5TYCZS3GM1NAFYMH6R82EM' } }
BATCHJOB BatchJob {
  dry_run: true,
  id: 'batch_01GM5TYCZS3GM1NAFYMH6R82EM',
  created_at: 2022-12-13T13:31:49.620Z,
  updated_at: 2022-12-13T13:33:39.891Z,
  deleted_at: null,
  type: 'product-import',
  created_by: 'usr_01GK9BQTK05BZ3NRKQHA5QSMAZ',
  context: { fileKey: 'product-export-Price_No_Formula_Dec12_intact.csv' },
  result: {
    count: 37040,
    operations: {
      PRODUCT_CREATE: 0,
      PRODUCT_UPDATE: 14497,
      VARIANT_CREATE: 0,
      VARIANT_UPDATE: 22543
    },
    stat_descriptors: [ [Object] ],
    advancement_count: 0
  },
  pre_processed_at: 2022-12-13T13:33:35.624Z,
  processing_at: null,
  confirmed_at: 2022-12-13T13:33:39.891Z,
  completed_at: null,
  canceled_at: null,
  failed_at: null,
  status: 'confirmed'
}
::1 - - [13/Dec/2022:13:33:39 +0000] "GET /admin/batch-jobs?failed_at=null HTTP/1.1" 200 890 "http://localhost:7000/" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
::1 - - [13/Dec/2022:13:33:39 +0000] "GET /admin/batch-jobs/batch_01GM5TYCZS3GM1NAFYMH6R82EM HTTP/1.1" 200 854 "http://localhost:7000/" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
::1 - - [13/Dec/2022:13:33:40 +0000] "GET /admin/product-tags HTTP/1.1" 304 - "http://localhost:7000/" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
::1 - - [13/Dec/2022:13:33:40 +0000] "GET /admin/store/ HTTP/1.1" 304 - "http://localhost:7000/" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
::1 - - [13/Dec/2022:13:33:40 +0000] "GET /admin/collections?offset=0&limit=500 HTTP/1.1" 304 - "http://localhost:7000/" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
::1 - - [13/Dec/2022:13:33:40 +0000] "GET /admin/products?fields=id%2Ctitle%2Cthumbnail%2Cstatus%2Chandle%2Ccollection_id&expand=variants%2Coptions%2Cvariants.prices%2Cvariants.options%2Ccollection%2Ctags%2Ctype%2Cimages&is_giftcard=false&offset=0&limit=50 HTTP/1.1" 200 282681 "http://localhost:7000/" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
info:    Processing batch.confirmed which has 1 subscribers
QUERYYYYYY { where: { id: 'batch_01GM5TYCZS3GM1NAFYMH6R82EM' } }
BATCHJOB BatchJob {
  dry_run: true,
  id: 'batch_01GM5TYCZS3GM1NAFYMH6R82EM',
  created_at: 2022-12-13T13:31:49.620Z,
  updated_at: 2022-12-13T13:33:39.891Z,
  deleted_at: null,
  type: 'product-import',
  created_by: 'usr_01GK9BQTK05BZ3NRKQHA5QSMAZ',
  context: { fileKey: 'product-export-Price_No_Formula_Dec12_intact.csv' },
  result: {
    count: 37040,
    operations: {
      PRODUCT_CREATE: 0,
      PRODUCT_UPDATE: 14497,
      VARIANT_CREATE: 0,
      VARIANT_UPDATE: 22543
    },
    stat_descriptors: [ [Object] ],
    advancement_count: 0
  },
  pre_processed_at: 2022-12-13T13:33:35.624Z,
  processing_at: null,
  confirmed_at: 2022-12-13T13:33:39.891Z,
  completed_at: null,
  canceled_at: null,
  failed_at: null,
  status: 'confirmed'
}
QUERYYYYYY { where: { id: 'batch_01GM5TYCZS3GM1NAFYMH6R82EM' } }
BATCHJOB BatchJob {
  dry_run: true,
  id: 'batch_01GM5TYCZS3GM1NAFYMH6R82EM',
  created_at: 2022-12-13T13:31:49.620Z,
  updated_at: 2022-12-13T13:33:39.891Z,
  deleted_at: null,
  type: 'product-import',
  created_by: 'usr_01GK9BQTK05BZ3NRKQHA5QSMAZ',
  context: { fileKey: 'product-export-Price_No_Formula_Dec12_intact.csv' },
  result: {
    count: 37040,
    operations: {
      PRODUCT_CREATE: 0,
      PRODUCT_UPDATE: 14497,
      VARIANT_CREATE: 0,
      VARIANT_UPDATE: 22543
    },
    stat_descriptors: [ [Object] ],
    advancement_count: 0
  },
  pre_processed_at: 2022-12-13T13:33:35.624Z,
  processing_at: null,
  confirmed_at: 2022-12-13T13:33:39.891Z,
  completed_at: null,
  canceled_at: null,
  failed_at: null,
  status: 'confirmed'
}
QUERYYYYYY { where: { id: 'batch_01GM5TYCZS3GM1NAFYMH6R82EM' } }
BATCHJOB BatchJob {
  dry_run: true,
  id: 'batch_01GM5TYCZS3GM1NAFYMH6R82EM',
  created_at: 2022-12-13T13:31:49.620Z,
  updated_at: 2022-12-13T13:33:42.570Z,
  deleted_at: null,
  type: 'product-import',
  created_by: 'usr_01GK9BQTK05BZ3NRKQHA5QSMAZ',
  context: { fileKey: 'product-export-Price_No_Formula_Dec12_intact.csv' },
  result: {
    count: 37040,
    operations: {
      PRODUCT_CREATE: 0,
      PRODUCT_UPDATE: 14497,
      VARIANT_CREATE: 0,
      VARIANT_UPDATE: 22543
    },
    stat_descriptors: [ [Object] ],
    advancement_count: 0
  },
  pre_processed_at: 2022-12-13T13:33:35.624Z,
  processing_at: 2022-12-13T13:33:42.573Z,
  confirmed_at: 2022-12-13T13:33:39.891Z,
  completed_at: null,
  canceled_at: null,
  failed_at: null,
  status: 'processing'
}
QUERYYYYYY { where: { id: 'batch_01GM5TYCZS3GM1NAFYMH6R82EM' } }
BATCHJOB BatchJob {
  dry_run: true,
  id: 'batch_01GM5TYCZS3GM1NAFYMH6R82EM',
  created_at: 2022-12-13T13:31:49.620Z,
  updated_at: 2022-12-13T13:33:39.891Z,
  deleted_at: null,
  type: 'product-import',
  created_by: 'usr_01GK9BQTK05BZ3NRKQHA5QSMAZ',
  context: { fileKey: 'product-export-Price_No_Formula_Dec12_intact.csv' },
  result: {
    count: 37040,
    operations: {
      PRODUCT_CREATE: 0,
      PRODUCT_UPDATE: 14497,
      VARIANT_CREATE: 0,
      VARIANT_UPDATE: 22543
    },
    stat_descriptors: [ [Object] ],
    advancement_count: 0
  },
  pre_processed_at: 2022-12-13T13:33:35.624Z,
  processing_at: null,
  confirmed_at: 2022-12-13T13:33:39.891Z,
  completed_at: null,
  canceled_at: null,
  failed_at: null,
  status: 'confirmed'
}

I see the field processing_at with a value - but after the status changes to confirmed, the processing_at value is null.  not sure if this is normal, I'm waiting for the error and will send the output.

**Comment by adrien2p** [comment]
no the confirmation of the batch_job should not reset the processing_at

**Comment by adrien2p** [comment]
also, since your batch job is in dry_run, setting the pre processed at will not confirm

**Comment by RegisHubelia** [comment]
I think the error is due to the admin ui when the notifications are opened...  I left it closed and the batch job in the database itself shows


batch_01GM5TYCZS3GM1NAFYMH6R82EM | product-import | usr_01GK9BQTK05BZ3NRKQHA5QSMAZ | {"fileKey": "product-export-Price_No_Formula_Dec12_intact.csv"} | {"count": 37040, "operations": {"PRODUCT_CREATE": 0, "PRODUCT_UPDATE": 14497, "VARIANT_CREATE": 0, "VARIANT_UPDATE": 22543}, "stat_descriptors": [{"key": "product-import-count", "name": "Products/variants to import", "message": "There will be 0 products created (14497  updated).\n             0 variants will be created and 22543 updated"}], "advancement_count": 0} | True | 2022-12-13 13:31:49.620569+00 | 2022-12-13 13:33:35.624+00 | 2022-12-13 13:33:39.891+00 | NULL | NULL | NULL | NULL | 2022-12-13 13:33:39.891244+00 | NULL

But it doesn't seem like anything is happening...  DB is sleeping and 0 cpu on the node process...

**Comment by RegisHubelia** [comment]
It didn't work actually.  I ended up writing a script to update the collections in the database directly.   I will need to get this fixed tough, as we need the import to work - it's easier for them to do it in a excel/export csv than going 1 by 1.  Basically what happened with the file that has the collections, the upload/pre-processing worked fine, but the job would just stick and not do anything - left it for about 6 hours without any luck...  The file without the collections worked after about an hour.  So exporting from medusa - and re-importing without changing anything in the file works with this PR whereas before it wouldn't.

**Comment by adrien2p** [comment]
Alright, just to be sure I did understand correctly, 
When exporting and re-importing without any modification of the content, it is now working where it wasn't previously. CC @olivermrbl 

In the other-hand, when importing a new file or an export with modification, the job stays stuck and nothing happen.

Is that correct?

**Comment by RegisHubelia** [comment]
> Alright, just to be sure I did understand correctly,
> 
> When exporting and re-importing without any modification of the content, it is now working where it wasn't previously. CC @olivermrbl
> 
> In the other-hand, when importing a new file or an export with modification, the job stays stuck and nothing happen.
> 
> Is that correct?

Yes - you can test with the files I sent you - 1 is the raw export, the other is with the collections - saved from the raw export file

**Comment by adrien2p** [comment]
I have tested on about 10k product on the untouched file. I will do the same tests with the other one and come back to you

**Review by fPolic — APPROVED** [review]
LGTM

**Review by srindom — APPROVED** [review]
LGTM!

**Comment by adrien2p** [comment]
@RegisHubelia just a random question. Does the collection in the file already exist in medusa?

**Comment by adrien2p** [comment]
@RegisHubelia could I get you to import the file with [that pr](https://github.com/medusajs/medusa/pull/2812) please.
You should see the error in the db in the result column of the corresponding batch job. I let you report me the result in the other pr 👍

**Comment by RegisHubelia** [comment]
Will do that ASAP.

**Comment by adrien2p** [comment]
@RegisHubelia I will let you report on the other mentioned pr

**Pull request merged**
