### PR TITLE
fix(medusa): Create migration to ensure correct variant inventory column

### PR DESCRIPTION
**Pull request by pKorsholm**
**What**
- Add migration to ensure that quantity is called `required_quantity`
- redo change to migration

### CODE REVIEW

**Comment by adrien2p** [comment]
@pKorsholm any reason why we don't create a new migration that change the comuln name? We should avoid updating existing migrations otherwise it can create issues. The rule should be that if a migration file has been merged in develop, we should create a new migration for the changes we want to make

**Comment by olivermrbl** [comment]
@pKorsholm Will you get back to adrien when time allows for it?

Also, I believe this should be against `master` to resolve issues with forcing people to update to v1.8

**Review by adrien2p — COMMENTED** [review]
After discussing, LGTM 🚀

**Review by adrien2p — APPROVED** [review]

**Comment by olivermrbl** [comment]
What did you discuss and what was your conclusion? :)

**Comment by pKorsholm** [comment]
just for context, this undoes a change to a migration that was previously merged into develop and deployed by accident and add's a new migration that tries to rename the column but doesn't fail if the column doesn't exist in order to align the tables of people who are in an in-between state

**Comment by adrien2p** [comment]
@olivermrbl I was missing the context to why we are doing something we shouldn't. In fact we are doing it because the mistake has already be done ahah

**Pull request merged**
