### PR TITLE
Allow exports/imports of medusa ui ui folder and subfolders

### PR DESCRIPTION
**Pull request by agustif**
In order to be able to import and reuse `admin-ui` components when creating new medusa plugins with the new admin widgets and routes

I want to import:
```jsx
import TableViewHeader from "@medusajs/admin-ui/ui/src/components/organisms/custom-table-header"
```

This change in package.json, should make it possible, otherwise the webpack build halts telling you the import path is not allowed. 

```diff
  "exports": {
    ".": "./dist/index.js",
-    "./ui": "./ui",
+    "./ui/*": "./ui/*",
    "./package.json": "./package.json"
  },
```

The asterisks makes anything under the path game, instead of just only import stuff being exported under `@medusajs/admin-ui/ui` only

### CODE REVIEW

**Comment by agustif** [comment]
Another question is if we might want to also provide them on dist but right now it only imports/provides utils and types

**Comment by olivermrbl** [comment]
Appreciate the contribution @agustif, but we are hesitant to accept the PR, as we are currently working on a UI library that will serve the purpose of exporting reusable and on-design components.

The core UI components are due for a larger rework, so using those in plugins now could lead to issues with breaking changes in the near future.

We expect to ship a set of foundational components within the coming two-three weeks, which should give you the starting point you are looking for. This should include a table component :)

**Comment by agustif** [comment]
Thanks Oliver, appreciate the explanation and not an issue at all, I'll be following the new UI components to re-use when launched.

Totally random anecdata from me, but I got a bit confused (and I am aware/have read of Atomic Habits), but I couldn't remember anytime if what I was looking for was a molecule/organism/whatever, so it would be nice if those words are skipped on the imports and just uses the component name, rally hard to know if you need an organism/molecule/etc when starting to play out with them!

**Comment by scriptcoded** [comment]
Hey @olivermrbl, sorry for reviving old threads.

Sounds really exciting with a dedicated UI library for admin customizations! You mentioned a 2-3 week timeline, but I can't seem to find anything in the docs nor the release notes. Could we expect this to release soon, or am I better off spending time implementing custom components?

Thanks a lot, and keep up the good work!

**Pull request closed without merging**
