### PR TITLE
chore: remove container registration name

### PR DESCRIPTION
**Pull request by carlos-r-l-rodrigues**
What:
* Deprecated `ModuleRegistrationName` in favor of `Modules` enum
* Modules are always registered in the container using their `key`
* Modules' key name normalized to PascalCase and `Service` suffix was removed (breaking change if module is resolved using strings)

### CODE REVIEW

**Review by adrien2p — APPROVED** [review]
LGTM, we might need a release note for that :D

**Review by sradevski — APPROVED** [review]
Really nice cleanup! Q: Are we also cleaning up the `ContainerRegistrationKeys`?

**Comment by carlos-r-l-rodrigues** [comment]
> Really nice cleanup! Q: Are we also cleaning up the `ContainerRegistrationKeys`?

Yeah, I think we need. I haven't done in this PR because I dont have any good naming suggestion.

**Comment by carlos-r-l-rodrigues** [comment]
@olivermrbl, let me know if we can merge this one.

**Comment by olivermrbl** [comment]
Yes, all good

**Comment by olivermrbl** [comment]
Maybe `ContainerRegistrationKeys` could be split into something like `Resources` and `Tools`:
```
const query = container.resolve(Tools.QUERY)
const logger = container.resolve(Tools.LOGGER)
const linker = container.resolve(Tools.REMOTE_LINK) // might want to rename this at some point?

const pgConnection = container.resolve(Resources.PG_CONNECTION)
const config = container.resolve(Resources.CONFIG)
```

Hard to find a single term that encapsulates all, because of how different these all are.

**Pull request merged**
