### PR TITLE
feat(admin-ui, admin-sdk, medusa, medusa-react, medusa-js, stripe-plugin): Support Admin Extensions

### PR DESCRIPTION
**Pull request by kasperkristensen**
**What**
- Introduces support for extending the Admin dashboard using two types of extensions: `Admin Widgets` and `Admin UI Routes`.
- Changes `@medusajs/admin-ui` from using `vite` to `webpack`.
- Introduces new factory method to `medusa-react` for creating custom API hooks.

**Breaking changes**

Admin Extensions are now supported. This means that the Admin UI can be extended with custom React components. See the docs for more information. This also means that the `medusa-admin eject` command has been removed, as it is no longer needed.

Users that have previously ejected the Admin UI will find that their ejected code is no longer compatible with new versions of `@medusajs/admin-ui`, due to the move from `vite` to `webpack`. We recommend that you port any customizations to Admin Extensions instead.

### CODE REVIEW

**Comment by andriinuts** [comment]
Looks very cool! Are you also planning to add the possibility to add a new page for admin, new settings elements, etc., and override some existing functionality like draft order creation, etc.?

**Comment by kasperkristensen** [comment]
> Looks very cool! Are you also planning to add the possibility to add a new page for admin, new settings elements, etc., and override some existing functionality like draft order creation, etc.?

Hi @andriinuts, 

Yes to all of them. The first iteration will be `Widgets` only, as we are mainly focusing on ironing out the DX around creating admin extensions. The next step will be pages, such as new settings pages, or adding entirely new domains. Eventually, we want to also support replacing existing parts of the admin, but can't speak to when that will be exactly.

**Comment by zhangpengchen** [comment]
Hi @kasperkristensen ,

Thanks for the great work making the admin extension possible, just wondering if you have any suggestions on how we can import components from the admin ui e.g. `import Table from "@medusajs/admin-ui/ui/src/components/molecules/table"`. It doesn't seem to work at this moment.

Curious about `Introduces new factory method to medusa-react for creating custom API hooks.` but couldn't find any documents around that.

**Pull request closed without merging**
