### PR TITLE
fix(order): return migration enum

### PR DESCRIPTION
**Pull request by carlos-r-l-rodrigues**

### CODE REVIEW

**Comment by olivermrbl** [comment]
Did the previous changes cause issues?

**Comment by carlos-r-l-rodrigues** [comment]
> Did the previous changes cause issues?

Yeah,
someone reported on Discord an issue saying that it couldn't run inside a transaction block.

**Comment by carlos-r-l-rodrigues** [comment]
image

**Review by olivermrbl — COMMENTED** [review]
Instead of creating a new type with the new-suffix, should we just drop the type first and recreate it?

**Comment by olivermrbl** [comment]
> > Did the previous changes cause issues?
> 
> 
> 
> Yeah,
> 
> someone reported on Discord an issue saying that it couldn't run inside a transaction block.
> 
> 

Interesting. Didn't experience this.

**Comment by carlos-r-l-rodrigues** [comment]
> Instead of creating a new type with the new-suffix, should we just drop the type first and recreate it?

sure. just did it.

**Review by olivermrbl — APPROVED** [review]

**Pull request merged**
