### PR TITLE
feat(admin-ui): add Hindi Translation

### PR DESCRIPTION
**Pull request by its-kunal**
- Added Hindi Translation for admin-UI
- Has to do with #5346

### CODE REVIEW

**Comment by its-kunal** [comment]
Hi, @VariableVic please review my pull request. Also add Hacktoberfest labels in this pull request

**Comment by VariableVic** [comment]
@its-kunal Please add your language to the `supportedLanguages` array in `packages/admin-ui/ui/src/i18n/index.ts`

**Comment by its-kunal** [comment]
@VariableVic Added locale in the `index.ts` file.

**Comment by its-kunal** [comment]
@VariableVic please merge my pull request.

**Comment by its-kunal** [comment]
Please merge this pull request, @VariableVic 

Fixes - #5346

**Pull request merged**
