### PR TITLE
fix(utils): bignumber util considers nullable options when setting value

### PR DESCRIPTION
**Pull request by riqwan**
what:

- when setting null for nullable columns, big number utils should not throw error
- remove circular soft delete depenedencies for cart module
- trims zeros on big number values

### CODE REVIEW

**Comment by carlos-r-l-rodrigues** [comment]
I am doing [similar changes](https://github.com/medusajs/medusa/pull/6467/files#diff-830d2d12fe2a3f7a17746929bbee34a91eff9e45845eccb19042b097cfda8efc) to it + some additional ones.
do you mind to bring that to this PR?

**Comment by riqwan** [comment]
@carlos-r-l-rodrigues sounds good, I can do that once I'm back. 👍🏻

**Comment by riqwan** [comment]
@carlos-r-l-rodrigues added them in here, let me know if i missed anything.

**Review by carlos-r-l-rodrigues — APPROVED** [review]
LGTM

**Pull request merged**
