### PR TITLE
feat: Adds redis options

### PR DESCRIPTION
**Pull request by olivermrbl**
Ability to add all possible [Redis options](https://www.npmjs.com/package/redis#:~:text=options%20object%20properties)

**Usage**
In `medusa-config.js` add `redis_config` to the project config:
```
module.exports = {
  projectConfig: {
    redis_url: REDIS_URL,
    redis_config: {
      prefix: "medusa",
    },
    database_url: DATABASE_URL,
    database_type: "postgres",
    store_cors: STORE_CORS,
    admin_cors: ADMIN_CORS,
  },
  plugins,
};
```

Solves #823

### CODE REVIEW

**Comment by dwene** [comment]
@olivermrbl thinking about merging this soon? :)

**Comment by dwene** [comment]
@olivermrbl @srindom any chance we can merge this soon? :)

**Comment by olivermrbl** [comment]
> @olivermrbl thinking about merging this soon? :)

Sorry for the slow response here @dwene. Have been looking at it today and it seems, that there's a thing we need to consider before merging it in. The way `redis` and `ioredis` (the two libraries we use) prefix keys differ. Last mentioned suffixes the prefix with `:` while the first-mentioned does not.

E.g. a project config with `{ prefix: "medusa" }`, would result in the two types of events in Redis:
```
medusasomething (redis)
medusa:something (ioredis)
```

I haven't played that much around with Redis key prefixes before, so I don't know what's best practice here, but I would assume, that we should have to go with one or the other to have consistency for keys in our Redis server, but please let me know if you think otherwise. 

So both approach requires us to do work on the prefix for one or the other Redis library. Unless we choose to not care. 

What do you think? :)

**Comment by adrien2p** [comment]
Just seen that pr, i also did one cause i needed it 🤣 #1402

**Pull request closed without merging**
