### PR TITLE
feat(dashboard,core,medusa,promotion): add campaigns UI

### PR DESCRIPTION
**Pull request by riqwan**
what:

- adds campaigns UI to create/update/list/view campaigns and budgets

missing:

- adding promotions to campaign from campaign UI because of missing APIs. 

Screenshot 2024-05-08 at 00 26 58
Screenshot 2024-05-08 at 00 27 08
Screenshot 2024-05-08 at 00 27 16
Screenshot 2024-05-08 at 00 27 23
Screenshot 2024-05-08 at 00 27 31

### CODE REVIEW

**Comment by olivermrbl** [comment]
@riqwan, datepicker is not working for me:

https://github.com/medusajs/medusa/assets/59018053/b634c0ef-dca7-4117-af71-22a55ecaad4f


I think it doesn't respond to cursor events. If you look at the video, you can see that I am actually interacting with the component underneath on clicks.

**Comment by olivermrbl** [comment]
We should not set these dates by default:

CleanShot 2024-05-08 at 16 12 01

**Comment by olivermrbl** [comment]
The currency row is not following the design. 

In Figma:
CleanShot 2024-05-08 at 16 13 23

In Admin:
CleanShot 2024-05-08 at 16 13 46

**Comment by olivermrbl** [comment]
Status indicator is missing in the top right next to the ellipsis:
CleanShot 2024-05-08 at 16 14 10

**Comment by olivermrbl** [comment]
Font should not be bold here:

CleanShot 2024-05-08 at 16 14 42

**Comment by riqwan** [comment]
@olivermrbl - the date picker doesn't seem to work in other places with modals as well. I tried to figure it out, but can't seem to pinpoint what the issue is. I can open a different PR with after a deeper debugging sess

**Comment by riqwan** [comment]
@olivermrbl addressed the others 🤞🏻

**Review by olivermrbl — APPROVED** [review]

**Pull request merged**
