### PR TITLE
chore(): Remove default limit from the build query

### PR DESCRIPTION
**Pull request by adrien2p**
TRI-281

**What**
Remove the repository layer default limit which lead to miss understanding and issues when working with deep relations etc. Instead, rely on higher level default limit provided to the module (e.g the default limit in our API).

### CODE REVIEW

**Comment by olivermrbl** [comment]
Just adding @srindom's [comment](https://linear.app/medusajs/issue/TRI-281/inventoryservice-takes-only-first-15-items#comment-b19994ed), so we won't proceed without addressing it

**Comment by adrien2p** [comment]
> Just adding @srindom's [comment](https://linear.app/medusajs/issue/TRI-281/inventoryservice-takes-only-first-15-items#comment-b19994ed), so we won't proceed without addressing it

@olivermrbl I dont understand, this pr addresses this issues as well many other issues it creates

**Comment by olivermrbl** [comment]
> > Just adding @srindom's [comment](https://linear.app/medusajs/issue/TRI-281/inventoryservice-takes-only-first-15-items#comment-b19994ed), so we won't proceed without addressing it
> 
> @olivermrbl I dont understand, this pr addresses this issues as well many other issues it creates

What I was trying to say was I just want to make sure we address the comment before moving forward

**Comment by adrien2p** [comment]
@olivermrbl it should be good now :)

**Review by carlos-r-l-rodrigues — APPROVED** [review]

**Comment by olivermrbl** [comment]
@adrien2p, will just give @srindom a chance to get back to your comment in Linear :)

**Comment by adrien2p** [comment]
sure @olivermrbl just to add a bit more context to it.

We currently have the default limit managed through the API and sent to the module query and then to the modules. Currently, the issue is that we have hidden conditions at the repository level to also manage a default limit, those conditions built up in  with time and became hard to use and are completely hidden. When consuming a module or a query or a repository inside a module, you always have to pass take: null in order to not have this default repository limit applied. This has caused many issues during the modules implementation and keeps coming back.

The main idea here is to lighten this repository layer, it does not manage any default limit and give back this behaviour to the consumer. In our case the default limit that we already apply in our end points for example

**Comment by srindom** [comment]
LGTM 👍

**Comment by srindom** [comment]
Can you update https://github.com/medusajs/medusa/issues/9247 to explain what should be done (if anything)

**Comment by adrien2p** [comment]
@srindom done I ve informed him, also he doesnt have to do anything on his side

**Pull request merged**
