### PR TITLE
feat(medusa): Adds validator pipe for Sales Channel existence

### PR DESCRIPTION
**Pull request by olivermrbl**
**What**
After having discussed w. @adrien2p and @srindom on how to solve the [circular dependency issue](https://github.com/medusajs/medusa/pull/1870#discussion_r923561528), we came up with an entirely different approach that works with the following premise:

_Our service layer should not take care of validating the existence of related entities. E.g. the ProductService should not validate that SaelsChannels exist upon creation and update._

Instead, we should perform the validation work using pipes in the API layer. In case the pipe throws, we'll concatenate error messages to the request object as `req.errors`. Finally, we'll check if any errors exist and respond to the end-user accordingly. 

Note, this is a naive first take. We could surely refactor this to be more generic, but we'd like everyone's opinion on the general approach.

Pitch in!

@fPolic @pKorsholm @kasperkristensen

We've intentionally left out testing until it has been approved by everyone :)

### CODE REVIEW

**Comment by olivermrbl** [comment]
This approach also allows us to provide much more elaborate error messages to the end user

**Review by pKorsholm — COMMENTED** [review]
I'm down for this approach as well, makes sense to add "guards" as a notion.

Could we find a way to apply check-errors more "globally" though? I'm thinking if we choose this approach it would be useful in many different scenarios for validating invariants. 

One approach could be using a `*` route and calling `next("route")` if errors occur in the middleware.

wdyt?

**Comment by olivermrbl** [comment]
> Could we find a way to apply check-errors more "globally" though?

Would it make sense to add it to our current error handler? Could be a first check for `req.errors?.length` and have a nicely formatted response. Like you mention, I could imagine, that we'll be able to follow this pattern for not only validation, hence why I think it could make sense.

**Comment by adrien2p** [comment]
> > Could we find a way to apply check-errors more "globally" though?
> 
> Would it make sense to add it to our current error handler? Could be a first check for `req.errors?.length` and have a nicely formatted response. Like you mention, I could imagine, that we'll be able to follow this pattern for not only validation, hence why it might be reasonable to add it to our global middleware.

Don’t think that adding it to the current error handler would work as we would have to specify when it is the last error to be added. Which means that if we add a new validator then we would have to change something. What if the wrap middlewares check for req.errors?.length before calling the actual handler? And if there is some then it can directly call the next with the errors. And then we would have to update  a bit the error handler.

**Comment by srindom** [comment]
> @adrien2p: What if the wrap middlewares check for req.errors?.length before calling the actual handler? 

Think this is a great idea

**Review by srindom — COMMENTED** [review]
Looks good! Think it would be great to move the checkErrorsOrContinue into the `wrap` middleware and then maybe also delete the addition of the `validateAllItemExistsOrThrow` in the base repo :)

**Comment by adrien2p** [comment]
> Looks good! Think it would be great to move the checkErrorsOrContinue into the `wrap` middleware and then maybe also delete the addition of the `validateAllItemExistsOrThrow` in the base repo :)

The other approach (for later) would be to apply it globally (it could also be done for the wrap middleware) using that approach: (just tried it and it works)
```ts
const methods = ["get", "post", "put", "delete"]

methods.concat("all").forEach(function (method) {
  Router[method] = function (path, ...handlers) {
    const route = this.route(path)
    const finalHandler = handlers.pop()
    handlers = [...handlers, checkErrorsOrContinue, finalHandler]
    console.log(JSON.stringify(handlers))
    route[method].apply(route, handlers)
    return this
  }
})
```

**Review by srindom — APPROVED** [review]
LGTM

**Comment by adrien2p** [comment]
@srindom just waiting for the tests and then i ll merge it. Wdyt of the proposal to generalise it, for the next phase?

**Comment by olivermrbl** [comment]
> just waiting for the tests and then i ll merge it

Seem to have an issue with the pipeline. The failing tests are completely unrelated to the PR here. Should we merge into your branch and fix it there, so we don't end up doing double work (potentially) @adrien2p ?

**Comment by adrien2p** [comment]
> > just waiting for the tests and then i ll merge it
> 
> Seem to have an issue with the pipeline. The failing tests are completely unrelated to the PR here. Should we merge into your branch and fix it, so we don't end up doing double work (potentially) @adrien2p ?

Agree, it seams to be the order.

**Comment by adrien2p** [comment]
@olivermrbl funny, the order tests didn't failed once on the order migrations. Usually they failed one time at least 😂

**Comment by olivermrbl** [comment]
> Usually they failed one time at least 

Ha! We might just have been lucky 😅

**Pull request merged**
