### PR TITLE
Feat(medusa, admin-ui): Update edit allocation modal

### PR DESCRIPTION
**Pull request by pKorsholm**
**What**
- update the design of the edit-allocation modal adding "description" and "metadata" capabilities
- Make line-item optional in the edit-allocation modal in prep for reservation management

Fixes CORE-1385

### CODE REVIEW

**Review by olivermrbl — CHANGES_REQUESTED** [review]
I've added comments to the edit allocation modal in #4081. Let me know, if you want me to move them here :)

**Comment by pKorsholm** [comment]
>I've added comments to the edit allocation modal
@olivermrbl I think it's fine, I'll port over the changes

**Review by riqwan — APPROVED** [review]
lgtm!

**Review by olivermrbl — APPROVED** [review]
LGTM!

**Pull request merged**
