### PR TITLE
fix(medusa-js):Use correct payload type in resetPassword method(Issue # 2019)

### PR DESCRIPTION
**Pull request by sabakhilji**
fixed issue#2019 ,changed and imported payload type to StorePostCustomersResetPasswordReq in resetPassword method.

### CODE REVIEW

**Comment by olivermrbl** [comment]
Looks like the PR is still including files from `master`. Can I get you to either rebase off of `develop`? Alternatively, create a new branch from `develop` and open a new PR. The latter might be the easier approach tbh.

**Comment by adithyaakrishna** [comment]
@sabakhilji Could you please let me know if there's any update on this PR? If not, can I take it up?

**Comment by sabakhilji** [comment]
> @sabakhilji Could you please let me know if there's any update on this PR? If not, can I take it up?

Hi @adithyaakrishna I am working on it will let you know if I am not able to do it .Thanks!

**Comment by olivermrbl** [comment]
@sabakhilji Any update on the requested changes?

**Pull request closed without merging**
