### PR TITLE
fix(inventory): cannot migrate existing products (#6877)

### PR DESCRIPTION
**Pull request by gempain**
Fixes the errors encountered in #6877.

### CODE REVIEW

**Review by sradevski — APPROVED** [review]
Can you please add a changeset per the contribution guide and rebase to the latest changes? I'll get it merged after that

**Comment by gempain** [comment]
Hm, I guess those guidelines have changed since [my last PRs](https://github.com/medusajs/medusa/pulls?q=is%3Apr+author%3Agempain+is%3Aclosed).

**Comment by gempain** [comment]
@sradevski should be good now. Let me know if I need to change something. I'm not used to using changeset.

**Comment by sradevski** [comment]
@gempain Should be good now, thanks! I'll get it merged as soon as the pipeline passes

**Comment by gempain** [comment]
> @gempain Should be good now, thanks! I'll get it merged as soon as the pipeline passes

Thanks very much 🙏

**Pull request merged**
