### PR TITLE
feat(dashboard): Regions domain

### PR DESCRIPTION
**Pull request by kasperkristensen**
**What**
- Implements new Region domain design
- Adds new SplitView component for managing adding nested relations in FocusModals, eg. adding countries to a region.
- Adds new Combobox component for multi select fields in forms

**medusajs/ui**
- Fix styling of RadioGroup.Choicebox component

CLOSES CORE-1650, CORE-1671

### CODE REVIEW

**Comment by srindom** [comment]
There's something with long country names that needs some attention:

CleanShot 2024-02-28 at 9  28 20@2x

**Comment by srindom** [comment]
If I open the create shipping option modal I am not able to scroll

**Comment by srindom** [comment]
Saving doesn't close the modal:

CleanShot 2024-02-28 at 9  32 56

**Comment by kasperkristensen** [comment]
@srindom should be good now

**Review by srindom — APPROVED** [review]
LGTM

**Pull request merged**
