### PR TITLE
Mark draft order endpoint wrong in medusa-js

### LINKED ISSUE #1038: [BUG] Mark draft order endpoint wrong in `medusa-js`
**What**
The endpoint to mark a draft order paid is `/pay`, but in `medusa-js` we currently have `/register-payment`.

**How**
Change [this line](https://github.com/medusajs/medusa/blob/80e86ca08c6d825797bbb783484c21fb92a33a9c/packages/medusa-js/src/resources/admin/draft-orders.ts#L86) to be `/pay`

### PR DESCRIPTION
**Pull request by RishiKumarRay**
fixes #1038

### CODE REVIEW

**Review by olivermrbl — CHANGES_REQUESTED** [review]
Thanks, but it's actually the route in `medusa-js` that needs to change and not the naming of the import here. 

So specifically [this line](https://github.com/medusajs/medusa/blob/80e86ca08c6d825797bbb783484c21fb92a33a9c/packages/medusa-js/src/resources/admin/draft-orders.ts#L86) need to be `/pay` and not `/register-payment`.

Hope it makes sense

**Comment by RishiKumarRay** [comment]
@olivermrbl please check now , is it correct

**Comment by RishiKumarRay** [comment]
@olivermrbl i did the changes but i have this errors can you tell me how to resolve this

**Review by olivermrbl — APPROVED** [review]
The pipeline seems to be working fine. Thanks for the contribution 👍

**Comment by RishiKumarRay** [comment]
@olivermrbl how to fix this?

**Comment by zakariaelas** [comment]
Hey there @RishiKumarRay, thanks for the contribution! 

Can we please get you to change the mocked server route we use for our test suites so that we can fix the failing test? I believe all it takes is to change the `register-payment` below to `pay` so that it matches the fixed route :smile:  https://github.com/medusajs/medusa/blob/07ce61dc759265530eca279bdd9bd3ecae99a2b9/packages/medusa-react/mocks/handlers/admin.ts#L714

Let me know if you need help!

**Comment by RishiKumarRay** [comment]
@zakariaelas I did the Fix and ran the test , There is one more test that is failing
Screenshot from 2022-02-16 10-28-34

**Comment by RishiKumarRay** [comment]
@zakariaelas i have also pushed the commit with fix

**Review by olivermrbl — APPROVED** [review]
LGTM, thanks for your contribution 👍

**Pull request merged**
