### PR TITLE
chore: Remove typeORM

### PR DESCRIPTION
**Pull request by riqwan**
What:

- removes typeorm from the workspace.
- I'm unsure what the plans for the API integration tests are, so I just turned them to txt files temporarily. If there's consensus to remove them, let's do that.

### CODE REVIEW

**Comment by thetutlage** [comment]
Always wondered why do we have `TypeORM` as a dependency 😇

**Comment by riqwan** [comment]
> Always wondered why do we have `TypeORM` as a dependency 😇

Mostly just PTSD 😄

**Review by carlos-r-l-rodrigues — APPROVED** [review]
🔥

**Review by adrien2p — APPROVED** [review]

**Review by sradevski — APPROVED** [review]
Nice :)

**Review by olivermrbl — APPROVED** [review]
Niice

**Pull request merged**
