### PR TITLE
fix(medusa): Export data should always provide a file_key

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
If there is no data to export, the file_key and the file_size are not saved in the job result

**How**

Always update the batchjob result with the file_key and size at the end

**Tests**

Update existing tests to validate that the value are defined in the result of the job after processing

### CODE REVIEW

**Review by pKorsholm — APPROVED** [review]
LGTM! 
thought: should we remove the filekey from the export in every iteration so we just set it in the end?

**Review by pKorsholm — APPROVED** [review]
LGTM! small suggestion: in the case that the batch job is cancelled and the file deleted, should we remove the filekey for consistency?

**Review by srindom — APPROVED** [review]
LGTM - @pKorsholm should we include as-is for now and then add your suggestions in separate tasks later on?

**Comment by adrien2p** [comment]
@pKorsholm @srindom ill do the changes just after launch if thats fine 👌

**Comment by srindom** [comment]
@adrien2p - alright excellent!

**Pull request merged**
