### PR TITLE
fix(product): fix product variant update price with min_quantity and max_quantity

### PR DESCRIPTION
**Pull request by BeyondOT**
## What : 
The issue is updating the variant price with min_quantity and max_quantity  always returned null for both these attributes. Which is not the expected behaviour based on the admin api reference. https://docs.medusajs.com/api/admin#products_postproductsproductvariantsvariant

## How : 
Make sure to include all the attributes when updating the variant price.

## Testing: 
Update variant price through api including min_quantity and max_quantity.

### CODE REVIEW

**Review by adrien2p — APPROVED** [review]

**Comment by BeyondOT** [comment]
I just added a commit that fixes the unit test error.

The price update fix was made by spreading the price object in money amount so the test should expect the currency code to be there as well if it was included in the price object.

**Review by carlos-r-l-rodrigues — APPROVED** [review]

**Comment by BeyondOT** [comment]
Hi @adrien2p, this is my first pull request, and it's been open for over two weeks now. The tests have passed, and it has already been approved. Could you let me know if there's anything preventing it from being merged?

**Review by riqwan — APPROVED** [review]
nice work! 💪🏻

**Comment by riqwan** [comment]
Apologies for the delay @BeyondOT, merging this in now! 💪🏻

**Pull request merged**
