### PR TITLE
chore: use node 21 for github actions

### PR DESCRIPTION
**Pull request by riqwan**
I've personally had great boost in local dev time and memory consumption moving from 16 to 21.

Let me know if there might be issues with release actions with the bump to 21

### CODE REVIEW

**Comment by riqwan** [comment]
@olivermrbl @adrien2p works with some minor changes!

**Review by olivermrbl — COMMENTED** [review]
pretty awesome! 

only thing I can think of is whether the github actions should be run with the minimum node version we support to ensure we are not accidentally approving changes that are only compatible with the latest version of node

that said, if this reduces CI time, I think we can solve this concern elsewhere, e.g. with a release pipeline

**Comment by adrien2p** [comment]
In the ci, we can also specify multiple versions of node and the ci will run for each of them, but then it will be longer but ensure it works for all the versions tested

**Comment by olivermrbl** [comment]
We are currently experiencing an issue related to an old node version in our CI, so I think we should try to make this land on develop soon.

My suggestion for the above "issue" would be to include a separate workflow, we can dispatch every time we release with our minimum required node version as input. It can be the same workflow with defaulting to v21 unless specified otherwise.

I am not comfortable running our actions with one version, while officially supporting a different one. We need to ensure the minimum required version is stable.

What do you think?

**Comment by adrien2p** [comment]
@olivermrbl why dont we provide an array of versions with min and 21 in the current workflow?

**Comment by olivermrbl** [comment]
> why dont we provide an array of versions with min and 21 in the current workflow?

Wouldn't that make the pipeline take significantly longer time to complete?

Update: I am keen to give this a try, but if it extends the CI time too much, I'd rather go with a different approach.

**Comment by adrien2p** [comment]
> > why dont we provide an array of versions with min and 21 in the current workflow?
> 
> 
> 
> Wouldn't that make the pipeline take significantly longer time to complete?

They should run in parallel, at least from my experience with the extender, all versions ran at the same time.

We just need to provide the matrix

**Comment by riqwan** [comment]
If we are experiencing an issue with our current version, would the other workflow even run successfully?

**Comment by olivermrbl** [comment]
> They should run in parallel, at least from my experience with the extender, all versions ran at the same time

Nice, I didn't know that. But I guess that makes the whole idea of the PR redundant?

**Comment by adrien2p** [comment]
The only left question is the one from riqwan, the 16.14 will likely create memory issues (jest + v8 update) and 16.10 is currently creating issues with some packages.

**Comment by adrien2p** [comment]
Yes this pr would slight change to use strategy: matrix: node: []

**Comment by olivermrbl** [comment]
> If we are experiencing an issue with our current version, would the other workflow even run successfully?

No, you're right – this would have to be fixed. From what I can tell, [updating the Node version used in one of our workflows](https://github.com/medusajs/medusa/pull/5993) resolves the issue, we are facing. It seems to be a dependency requiring a minimum Node version of 16.14 and we default to 16.10. 

Did you experience issues with 16.14 specifically @riqwan or would this be an OK change to resolve it here and now?

**Comment by adrien2p** [comment]
There is the jest memory issues above 16.10 and under 20 something. Because of a v8 update that occurs at that time

**Comment by olivermrbl** [comment]
> There is the jest memory issues above 16.10 and under 20 something

But since this workflow is not testing anything with jest, it should be fine no? We are just cloning our starter to ensure our CLI works as expected.

**Comment by adrien2p** [comment]
The integration tests are likely to fail often 

Override: you mean for the specific cli workflow. Should be fine 👌

**Comment by olivermrbl** [comment]
> Override: you mean for the specific cli workflow. Should be fine 👌

Yes exactly. I am only using 16.14 for [this specific workflow](https://github.com/medusajs/medusa/blob/develop/.github/workflows/test-cli-with-database.yml). None of the integration test flows should be affected.

**Comment by riqwan** [comment]
No issues with 16.14, this would be fine. I was more interested in the integration tests for the performance gains.

**Comment by olivermrbl** [comment]
> I was more interested in the integration tests for the performance gains.

Do you have an idea of how much it cuts off? If it's significant, I think it's worth trying to find a way to make it land.

**Comment by riqwan** [comment]
@olivermrbl I could only run it without cache to test, and it was only about a minute faster.

**Pull request closed without merging**
