### PR TITLE
feat: Make the Module require the service name

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
The `Module` util will now require the service name. As part of the work, the Links returned by the `Module` will have a proper type inference of the service name as well as the field the end data will be attached to.

Screenshot 2024-07-03 at 14 29 08
Screenshot 2024-07-03 at 14 37 12

**NOTE**
This pr is preliminary step towards the `defineLink` util

FIXES CORE-2463

### CODE REVIEW

**Comment by adrien2p** [comment]
@shahednasser after discussing w @olivermrbl we decided that the service name would become required when using the `Module` util as it is a required value to possess in order to generate the link between modules

**Comment by shahednasser** [comment]
@adrien2p sounds good, will update it in the docs

**Review by sradevski — APPROVED** [review]
LGTM!

**Review by riqwan — APPROVED** [review]
🥇

**Pull request merged**
