### PR TITLE
feat: add default remove options for scheduled jobs

### PR DESCRIPTION
**Pull request by u11d-bartlomiej-galezowski**
**What** - Added default options for removing BullMQ jobs.
**Why** - Currently, scheduled jobs do not have removeOnComplete and removeOnFail options configured. As a result, frequent scheduled jobs can fill the Redis instance with thousands of hashes containing insignificant information about completed or failed jobs, which can slow down the Redis instance. We need to limit the number of retained hashes.
**How** - Added default removeOnComplete and removeOnFail options to jobs.
**Test** - Testing this feature with unit or integration tests is challenging. I tested it by linking the package to an existing Medusa project and monitoring the JobSchedulerService:scheduled-jobs:queue:completed ZSET in Redis to ensure it contains elements no older than the specified age value. For testing purposes, I set the age to 60 seconds. I also tested the removeOnFail configuration with both count and age settings, and it worked correctly.

Effect of the default configuration:
- All completed jobs older than 24 hours will be removed.
- All failed jobs older than 7 days will be removed, and the total number of retained failed jobs will not exceed 5000.

Based on: https://github.com/medusajs/medusa/pull/8145

### CODE REVIEW

**Review by sradevski — APPROVED** [review]
LGTM. Would you be up to also applying these changes to `v2 (develop)`? That would be done [here](https://github.com/medusajs/medusa/blob/1d40b3cc98faaaf5c2b5ff9601a16f01d970d95e/packages/core/orchestration/src/workflow/scheduler.ts#L20)

**Comment by u11d-bartlomiej-galezowski** [comment]
@sradevski sure, I will apply the changes for v2. Could you give me another approve? I had to fix unit tests...

**Comment by olivermrbl** [comment]
@shahednasser, should we update our 1.0 docs to reflect this change?

**Comment by shahednasser** [comment]
@olivermrbl sure I'll open a ticket for it 👍🏻

**Comment by olivermrbl** [comment]
@shahednasser, also, it looks like all the docs checks are not running. Given this is not touching any documentation, is it safe to merge without those passing?

**Comment by shahednasser** [comment]
Yes go ahead, the vercel checks requires authorization and even if given the checks will be canceled anyway since the PR doesn't have documentation changes

**Comment by olivermrbl** [comment]
@u11d-bartlomiej-galezowski, thanks for the contribution. We will put out a new release tomorrow afternoon :)

**Comment by olivermrbl** [comment]
@u11d-bartlomiej-galezowski, released in https://github.com/medusajs/medusa/releases/tag/v1.20.8

**Comment by u11d-bartlomiej-galezowski** [comment]
Thanks @olivermrbl 🖐️

**Pull request merged**
