### PR TITLE
feat: delete product image

### PR DESCRIPTION
**Pull request by bacarybruno**
Details: https://github.com/medusajs/medusa/discussions/5149

This PR intends to remove product images and thumbnail when a product is updated or deleted.

Tasks:
- [x] Unit tests
- [x] Update documentation
- [x] Manual test the behaviour with `medusa-file-local`
- [x] Manual test the behaviour with `medusa-file-s3`
- [ ] Manual test the behaviour with `medusa-file-minio`: need testers
- [ ] Manual test the behaviour with `medusa-file-spaces`: need testers

### CODE REVIEW

**Review by olivermrbl — COMMENTED** [review]
As this is a feature that includes updating our core project config, please create a GitHub Discussions, so we can discuss the approach. We'd like to avoid having long-running PRs open.

**Comment by pevey** [comment]
This has long been a pain point.  I would love to see this implemented.  The approach makes sense to me.  It gives people the option to keep existing behavior if for some reason they want to keep images on delete.

**Comment by bacarybruno** [comment]
Done here https://github.com/medusajs/medusa/discussions/5149 @olivermrbl 👍 do not hesitate to tell me if something else need to be done

**Comment by riqwan** [comment]
Hey, thanks for the PR! Since v2 brought a lot of architectural changes, we will be closing this PR since it no longer applies to our new setup.

If you would still like to open this PR, please rebase with the v1 branch and re-request a review & we'll get back on it quickly.

**Pull request closed without merging**
