### PR TITLE
Feat/plugin details

### PR DESCRIPTION
**Pull request by SGFGOV**
An Attempt address #5087

### CODE REVIEW

**Comment by tsvetann** [comment]
What about info log for the failed plugins with possible error?

**Comment by SGFGOV** [comment]
> What about info log for the failed plugins with possible error?

That is an interesting idea, let me think about it

**Comment by SGFGOV** [comment]
> What about info log for the failed plugins with possible error?

Done .. I've enclosed the plugin loading in try catch, that should provide some granularity if an the error

**Comment by riqwan** [comment]
Hey, thanks for the PR! Since v2 brought a lot of architectural changes, we will be closing this PR since it no longer applies to our new setup.

If you would still like to open this PR, please rebase with the v1 branch and re-request a review & we'll get back on it quickly.

**Pull request closed without merging**
