### PR TITLE
docs: v1.17.0 upgrade guide

### PR DESCRIPTION
**Pull request by olivermrbl**

### CODE REVIEW

**Comment by olivermrbl** [comment]
@shahednasser, do you have time to give this a review? 🙏

**Review by shahednasser — APPROVED** [review]
LGTM! @olivermrbl does bearer authentication not work anymore? If so we need to update the API examples in the OAS comments to reflect this

**Comment by olivermrbl** [comment]
> bearer authentication not work anymore

Bearer authentication still works, but it now uses a different token type. Previously, we used Bearer for our API token auth. With the recent changes, the Bearer scheme is used for JWT auth. 

You can read more about it in the release notes [here](https://github.com/medusajs/medusa/releases/tag/untagged-740616873f020d35227d) and the pull request [here](https://github.com/medusajs/medusa/pull/4064).

Let me know if I can help with anything. I've added an example in the release notes.

**Comment by olivermrbl** [comment]
I believe David also included this in his documentation PR #5156. I'll run through it once more

**Comment by shahednasser** [comment]
@olivermrbl I'll open a PR that fixes the OAS, should be fairly straightforward. Don't forget to merge #5156 as well once the release is out!

**Comment by olivermrbl** [comment]
> I'll open a PR that fixes the OAS

Great, thanks! 🙏

**Pull request merged**
