### PR TITLE
chore(medusa): Cart service/repo cleanup

### PR DESCRIPTION
**Pull request by adrien2p**
Proposal for discussion

Probably require the migration to typeorm 0.3 to continue and validate this one around a discussion

**What**

After discussing with @olivermrbl I got the information that in the custom cart repository, the way the find with relations has been re implemented was due to the fact that the generated sql query was too big.

After interrogating  my self i was wondering how a query can be more that 1GB [which is the limit of the allocated memory for a query string](https://github.com/postgres/postgres/blob/master/src/common/stringinfo.c#L28). 

I also find out that in the same cart service, the list method was using the `find` method without using the internal re implementation and that as of now we did not get any problem.

So I decided to test it and everything is working as expected, which also re allow the original features that typeorm provides such as being able to filter on the relations as well as on the entity itself.

Also, the usage of custom methods, does not allow to filter the query against the relations, or just selecting some columns on those relations to not increase the memory with data that are not used, or other internal feature provided by typeorm

**Test**

The actual integration tests for the totals service already tests that, it includes 16 relations and select all the fields of the cart as well as of all the relations

**Feedback**

I might miss some other information or context that I would like to be aware of if that is the case.

Include FIXES CORE-428

### CODE REVIEW

**Comment by olivermrbl** [comment]
comment: Note, this does not solve the issue with long generate table name aliases, which was why we chose to build our way of retrieving relations. See [this issue](https://github.com/typeorm/typeorm/issues/1785) for more details.

(Also, have described it in CORE-428)

**Comment by srindom** [comment]
There is an additional reason for creating `findWithRelations`. We encountered OOM errors when the default TypeORM query, could imagine the reason being that there was an enormous amount of data being returned when many relations were joined (due to the cartesian product of one to many relations).

**Comment by adrien2p** [comment]
> There is an additional reason for creating `findWithRelations`. We encountered OOM errors when the default TypeORM query, could imagine the reason being that there was an enormous amount of data being returned when many relations were joined (due to the cartesian product of one to many relations).

I suppose that this behaviour would also happen in the actual usage since we do not reduce the amount of data when we aggregate them? wdyt?

**Comment by adrien2p** [comment]
Also, another interesting point is that we are using `find` in the list method and the custom one in the `retieve`. I would have assumed that the `list` method would fetch more data than the `retrieve` method.

**Comment by adrien2p** [comment]
Since newer version of typeorm, it is now possible to specify the loading strategy

- relationLoadStrategy https://github.com/typeorm/typeorm/pull/8616

**Comment by adrien2p** [comment]
Close in favour of the migration to typeorm 3 + the architecture changes

**Pull request closed without merging**
