### PR TITLE
feat(medusa-react, medusa-js): Rework custom hooks

### PR DESCRIPTION
**Pull request by kasperkristensen**
**What**
- Makes custom hooks more flexible, and simpler.

**How**
- Instead of using a factory method that accepts a path, we expose the "raw" hooks, meaning that the user can specify the path of their choosing, such as `/product/:p_id/custom/:c_id`, etc.
- This allows for more flexibility, but also removes some of the under the hood magic in the form of queryKeys.
- Users will now have to manage queryKeys manually since we have removed the factory method.

**Note**
- The factory method was also removed because it caused issues with non-portable types in pnpm projects, and I was not able to resolve this. I will look into how to ease managing the queryKeys can be achieved in a way that does not cause TS errors, but given that this is a feature for more advanced users, I believe some requirements of understanding queryKeys in `@tanstack/react-query` is an okay trade-off for the time being.

**Usage**

Base types for examples:

```ts
// Single post
type AdminBlogPostReq = {
  title: string,
  content: string,
  author_id: string,
}

type AdminBlogPostRes = {
  post: BlogPost,
}

type AdminBlogPostQuery = {
  expand: string,
  fields: string
}

// Multiple posts
type AdminBlogPostsRes = {
  posts: BlogPost[],
  count: number
}

type AdminBlogPostQuery = {
  author_id,
  created_at: string,
  expand: string,
  fields: string
}

// Delete
type AdminBlogPostDeleteRes = {
  id: string,
  type: string
}
```

**useAdminCustomQuery**

```tsx
// src/admin/routes/blog/posts/[id]/page.tsx
import { useAdminCustomQuery } from "medusa-react"
import { useParams } from "react-router-dom"

const BlogPost = () => {
  const { id } = useParams() 

  const { data: { post }, isLoading } = useAdminCustomQuery<AdminBlogPostQuery, AdminBlogPostRes>(
    `/blog/posts/${id}`,  // path
    ["blog-post", id], // queryKey
    {
      expand: "author" // query
    }
   )

  // render something
}

// src/admin/routes/blog/author/[id]/posts/page.tsx
import { useAdminCustomQuery } from "medusa-react"
import { useParams } from "react-router-dom"

const AuthorsBlogPosts = () => {
  const { id } = useParams() 

  const { data: { posts }, isLoading } = useAdminCustomQuery<AdminBlogPostsQuery, AdminBlogPostsRes>(
    `/blog/posts`,  // path
    ["blog-posts", "list", id], // queryKey
    {
      expand: "author" // query
      author_id: 
    }
   )

  // render something
}
```

**useAdminCustomPost**

```tsx
// src/admin/routes/blog/posts/[id]/page.tsx
import { useAdminCustomPost } from "medusa-react"
import { useNavigate } from "react-router-dom"

const CreateBlogPost = () => {
  const navigate = useNavigate() 

  const { mutate, isLoading } = useAdminCustomPost<AdminBlogPostReq, AdminBlogPostsRes>(
    `/blog/posts`,  // path
    ["blog-posts"], // queryKey - we want to refetch the previous list queries
    ["products"], // related domains - in this example blog posts are related to products, and therefore we also want to invalidate those
   )

  const handleCreate = (args: AdminBlogPostReq) => {
    return mutate(args, {
      onSuccess: (data) => {
        navigate(`blog/posts/${data.post.id})
      }
    })
  }
}
```

**useAdminCustomDelete**

```tsx
// src/admin/routes/blog/posts/[id]/page.tsx
import { useAdminCustomPost } from "medusa-react"
import { useNavigate, useParams } from "react-router-dom"

const BlogPost = () => {
  const { id } = useParams()
  const navigate = useNavigate() 

  const { mutate, isLoading } = useAdminCustomDelete<AdminBlogPostDeleteRes>(
    `/blog/posts/${id}`,  // path
    ["blog-posts"], // queryKey - we want to refetch the previous list queries
    ["products"], // related domains - in this example blog posts are related to products, and therefore we also want to invalidate those
   )

  const handleDelete = () => {
    return mutate(undefined, {
      onSuccess: () => {
        navigate("..")
      }
    })
  }
}
```

### CODE REVIEW

**Comment by TuringJest** [comment]
Looks like you removed the 'id' argument from the deleteMutation, this is a step back from using `createCustomAdminHooks`. 

Also why remove `createCustomAdminHooks` instead off deprecating it? This is an unnecessary breaking change and requires a refactor which won't help users. 

I think these kind of changes should be discussed more with the community to avoid potential frustration. 
There are quite a lot of breaking changes every other month, some of which probably introduce unnecessary work and can be avoided.

**Comment by kasperkristensen** [comment]
@TuringJest `createCustomAdminHooks` was never released outside of the `beta` version of `medusa-react`, so it can't really be described as a breaking change. I am sorry if it caused you any issues, but using a version of a dependency that is not stable always comes at the risk of the API changing before release.

And yes the `id` param was removed, which was done in response to feedback we got during the beta, as people wanted in to be more flexible. 

You can still initiate it with a path, and if you are deleting something via an ID, then you can initiate it with `/my-custom/delete/<some-id>`. By not not having `id` as a required prop, you can also create a hook that allows bulk deleting entities, with path `/my-custom/delete`, and then pass `ids: string[]` in the body of the request instead.

**Comment by TuringJest** [comment]
@kasperkristensen Thanks for the reply. My bad, I thought it was realised before that. Should have checked. 
Can you point me to where you guys usually discuss future changes?

> By not not having id as a required prop, you can also create a hook that allows bulk deleting entities, with path /my-custom/delete, and then pass ids: string[] in the body of the request instead.<
Wouldn't you want to do that with the `post` hook? 

Don't want to nitpick but I see no purpose of the delete hook. It's the same post request. The mutation doesn't take a resource now, so setup and usage in react is also the same.

What's more of an issue is that it adds confusion. It looks like you can have REST endpoints but actually you are stuck with this  `/<action>/<some-id>`

BTW moving away from the hardcoded actions is definitely better. I'm just not a react guy and you can't do this with hooks in react:
 ```
 function deleteMyResource(id: string) {
    const delete= useAdminDeletePageMutation(id) // useAdminCustomPost/Delete wrapper
  }
  ```
so simple things became a bit less simple on the react side. Now you either have to use state for ID or wrap everything in ID separated components and setup the hook there... which is fine but I guess more cumbersome in some cases than before.

**Pull request merged**
