### PR TITLE
refactor(medusa-interfaces): Migrate baseService to TS + improve the service it self

### PR DESCRIPTION
**Pull request by adrien2p**
The idea with the `withTransaction` update is that now there is no need to implement that method in the child class unless  there is a custom requirement. In that case, the child class can override the default `withTransaction` method.

I did that because most of the time if not all the time, the `withTransaction` is always implemented the same way
passing the container values plus updating the manager.

@srindom what is the strategy at the moment to be able to update all the packages that depend on this package? Waiting the new version ?

### CODE REVIEW

**Comment by adrien2p** [comment]
@srindom any chance to look at it please :) ?

**Review by srindom — CHANGES_REQUESTED** [review]
Lmk what you think about slowly moving things away from `medusa-interfaces`?

**Comment by adrien2p** [comment]
@srindom is there a really example of using withTransaction without passing the manager?

**Comment by adrien2p** [comment]
When the PR will be merged then I will start moving the core services

**Comment by adrien2p** [comment]
@srindom I will wait for that Pr to be merged before starting the migration

**Review by srindom — COMMENTED** [review]
LGTM! @olivermrbl just want to be sure you agree with this change - please take a look and approve on behalf of @medusajs/core

**Comment by olivermrbl** [comment]
> LGTM! @olivermrbl just want to be sure you agree with this change - please take a look and approve on behalf of @medusajs/core

I like it! The separation of interfaces and core does more harm than good for us 👍

**Review by olivermrbl — APPROVED** [review]
LGTM! Great work @adrien2p

**Review by srindom — APPROVED** [review]

**Pull request merged**
