### PR TITLE
Feat/medusa plugin reviews

### PR DESCRIPTION
**Pull request by edihasaj**
added customer reviews for products ###

https://github.com/medusajs/medusa/issues/1869

### CODE REVIEW

**Comment by olivermrbl** [comment]
@edihasaj Many thanks for the contribution! Can I get you to add build-files to `.gitignore` and rebase off `develop` as a few preliminary steps to review?

**Comment by olivermrbl** [comment]
> Can I get you to add build-files to .gitignore and rebase off develop as a few preliminary steps to review?
It actually seems, that you've only included the build-files and not the actual implementation in the PR.

**Comment by edihasaj** [comment]
I will check this and make necessary changes. Thanks

**Comment by edihasaj** [comment]
@olivermrbl I did rebase from master branch to develop, but I think probably it should be recreated from the beginning as a PR, let me know if you want to do that.

**Comment by kaushalyap** [comment]
I welcome new plugin review support, Medusa plugin for reviews is better than using third party providers like Yopto.

**Pull request merged**
