### PR TITLE
chore(): start moving some packages to the core directory

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
Move to core the following packages, more might still move depending on future decision
- core|tooling
  - workflows-sdk
  - modules-sdk
  - orchestration
  - types
  - utils
  - test-utils
- cli
  - create-medusa-app
  - medusa-cli
  - medusa-dev-cli
  - oas

**NOTE**
The medusa package will not be moved as part of that pr, I would do that once I have finalized the refactoring to not have to many conflicts with the current work on the api

will wait to remove the generated dir until everything else is moved and react/js packages are refactored somehow

### CODE REVIEW

**Comment by sradevski** [comment]
@adrien2p the only one I am not so sure of is the `core-flows` package. I think `core` should not contain any business logic, and as such, `core-flows` might be better of staying at the top level, similar to `medusa`. Let's see what others think though.

**Comment by adrien2p** [comment]
> @adrien2p the only one I am not so sure of is the `core-flows` package. I think `core` should not contain any business logic, and as such, `core-flows` might be better of staying at the top level, similar to `medusa`. Let's see what others think though.

I agree and I wasn't sure as well, this one needs some discussion I agree

**Comment by adrien2p** [comment]
My thinking was more that the core-flows is our core opinionated business logic and maybe in that case it can go to the core dir.

**Comment by sradevski** [comment]
> My thinking was more that the core-flows is our core opinionated business logic and maybe in that case it can go to the core dir.

Yeah let's see, maybe we can split them in 2 different folders, one that is business-agnostic, and one that has business logic. I guess `types` would also fall into the business logic bucket rather than the core

**Pull request merged**
