### PR TITLE
fix: Remove `region_id` from countries upon deleting a region

### PR DESCRIPTION
**Pull request by olivermrbl**

### CODE REVIEW

**Comment by adrien2p** [comment]
Should’t it be an update on the foreign key? Set null on delete?

**Comment by olivermrbl** [comment]
> Should’t it be an update on the foreign key? Set null on delete?

Yeah, much better. Will fix and open a new one 👍 Thanks @adrien2p

**Comment by adrien2p** [comment]
Maybe worth to see if there is the same pattern in other places? 😊

**Comment by srindom** [comment]
Does that work with soft deletes?

**Comment by olivermrbl** [comment]
> Should’t it be an update on the foreign key? Set null on delete?

Having done some digging (and testing), it seems, that cascading and soft-removals do not really go hand in hand. So the issue is, that `softRemove` is actually not an `onDelete` event, but an `onUpdate` event. We can't really use `onUpdate: "SET NULL"`, since this would remove countries from regions on all kinds of updates to the regions.

Did you have a specific approach in mind @adrien2p ? Otherwise, I am gonna reopen the PR 🙂

**Comment by adrien2p** [comment]
Ok, there is a PR open for cascading soft remove. In the mean time, I would suggest to add an event on the entity, that check if deleted_at as been changed. If it is and has a value then set the relation id to null. What do you think ? That way, it does the same job and there is only the entity that does know what to do when it is deleted

**Comment by olivermrbl** [comment]
The first approach would dedicate the responsibility to a background job, which can fail very rarely. In those cases, we would have inconsistencies in our db. I would rather add it as part of a transaction to ensure the integrity of our data.

The second approach is not supported in Typeorm as far as I can see.

**Comment by adrien2p** [comment]
For the second approach, it is a migration, you write a psql trigger. It is then managed by the database itself. But the event handler should be fine.

**Comment by olivermrbl** [comment]
@adrien2p  @srindom 
Have added an alternative approach to the one included here on branch `fix/region-on-delete-listener`. 

The branch introduces Typeorm's entity listeners which allows us to listen to update events directly on entities in the database. In this case, I've used it to remove countries on region soft removals by listening to the `afterUpdate` event.

To use this new subscriber pattern, we have to add subscribers to our Typeorm config similar to how we do with models and repositories. 

Let me know what you think of this approach.

**Comment by adrien2p** [comment]
I think it is pretty nice 😊 

You can have a look of what Ive done in order to be able to handle the event in a service or workflow in order to keeps things related together https://github.com/adrien2p/medusa-extender/blob/main/src/decorators/onMedusaEntityEvent.decorator.ts

Because as a developer, the event management is often something hidden in the code that you do not find that easily when you don't know the code base. With that approach you also get the possibility to scoped the subscriber from the requests. Maybe something to keep in mind for another time?

**Comment by adrien2p** [comment]
Another question, does removing the region_id from the country has another impact on the product, shipping or anything else ?

**Comment by jzatarain** [comment]
ETA of when this can be reviewed?

**Comment by olivermrbl** [comment]
> ETA of when this can be reviewed?

We've proposed an alternative way of solving this [here](https://github.com/medusajs/medusa/pull/1112/files). Would be great to hear your thoughts on this. But to answer your questions, I will try to push for it this week :)

**Comment by jzatarain** [comment]
> > ETA of when this can be reviewed?
> 
> We've proposed an alternative way of solving this [here](https://github.com/medusajs/medusa/pull/1112/files). Would be great to hear your thoughts on this. But to answer your questions, I will try to push for it this week :)

I feel that as long as medusa only supports deleting regions from that code, it is ok.
Otherwise, it may fall under things like "it is not well documented", or "I made this other code that also deletes regions, but I forgot we had to remove the region_id".

**Comment by olivermrbl** [comment]
> Otherwise, it may fall under things like "it is not well documented", or "I made this other code that also deletes regions, but I forgot we had to remove the region_id".

You make a valid point. I'll revisit the PR in the coming week, since I also need to fix integration tests. I think we could solve it quite nicely by extracting it into a repository method that takes care of it in a single operation.

**Comment by olivermrbl** [comment]
@jzatarain See #1330

**Comment by olivermrbl** [comment]
Solved in #1330

**Pull request closed without merging**
