### PR TITLE
fix(gatsby-source-medusa): Use correct offset

### PR DESCRIPTION
**Pull request by r1cs1**
### What - what changes are in this PR
fixing gatsby source plugin that have wrong offset value when populating data from medusa

### How - how have the changes been implemented
- fixed how offset value is set
- refactored medusaRequest function to be able to mock it

### Testing - how has the changes been tested or how can the reviewer test the feature
added jest tests for the issue

### CODE REVIEW

**Review by olivermrbl — APPROVED** [review]
LGTM - thanks for the contribution! Can I get you to update your branch before we merge?

**Comment by r1cs1** [comment]
Sure, will do tonight

**Comment by r1cs1** [comment]
@olivermrbl I've made the updates.

**Comment by adrien2p** [comment]
@r1cs1 could you update your pr with the latest develop please. The pipeline failed and thats why this pr has not been merged automaticallly

**Pull request closed without merging**
