### PR TITLE
fix(medusa, medusa-admin): Tax Rates API: replace legacy way of accepting expand / fields params

### PR DESCRIPTION
**Pull request by josetr**
From arrays to comma-separated values

### CODE REVIEW

**Comment by olivermrbl** [comment]
@josetr thanks for the contribution ... can I get you to run `yarn build` at root and push files to ensure the changes are reflected in the OAS

**Comment by josetr** [comment]
Can you do it for me?

I have tried to do that before, but I'm getting the following error:

image

Perhaps it's my windows machine that's causing the problem

**Comment by srindom** [comment]
I would argue that the  - it should actually be all the other endpoints that should accept `expand[]=...` and not the other way around.

**Comment by srindom** [comment]
Would prefer that we move to a model where both comma separated and `[]`s work. I personally like the `[]` notation better, but more importantly this change here would break existing implementations if they are currently using `[]`.

Would suggest a change to the `FindParams` instead that transforms both `[]` and comma-separated values to arrays internally.

**Comment by riqwan** [comment]
Hey, thanks for the PR! Since v2 brought a lot of architectural changes, we will be closing this PR since it no longer applies to our new setup.

If you would still like to open this PR, please rebase with the v1 branch and re-request a review & we'll get back on it quickly.

**Pull request closed without merging**
