### PR TITLE
fix: Add default cookie and jwt

### PR DESCRIPTION
**Pull request by olivermrbl**
**What**
Adds a default cookie and jwt secret

**Why**
Make `medusa develop` run without any environment variables making the quickstart even more frictionless.

### CODE REVIEW

**Review by srindom — COMMENTED** [review]
Should we maybe make this configurable from `medusa-config.js` instead? 

If we import the Medusa project's `medusa-config` we can use `projectConfig.[cookie_secret|jwt_secret]`

**Comment by olivermrbl** [comment]
Good point. This kinda limits the use of secrets in all other envs. than production. Will make the requested changes here, and add default values to the `medusa-starter-default` project 👍

**Comment by adrien2p** [comment]
@olivermrbl @srindom - I think we can close that one?

**Comment by srindom** [comment]
Yes - believe the new approach with the config fixes this right

**Comment by adrien2p** [comment]
Yes indeed 🙏

**Pull request closed without merging**
