### PR TITLE
Add async functionality and Awilix container argument to the meilisearch transformer function

### PR DESCRIPTION
**Pull request by tsvetann**
### Description:
This Pull Request introduces significant enhancements to the medusa-plugin-meilisearch plugin by making the config transformer function asynchronous and by adding a second argument to the function which is the Awilix container. These changes are aimed at empowering developers with greater flexibility and customization capabilities, specifically for those looking to heavily invest in MeiliSearch as a search engine.

### Changes:
Async Config Transformer Function: The config transformer function has been modified to be asynchronous. This modification provides developers with the capability to make remote calls within the function, thereby making the function more versatile.

Awilix Container Argument: The config transformer function now takes a second argument: the Awilix container. This gives developers access to all registered services, repositories, and utilities in the Medusa container. As a result, developers can now make the most of the power of dependency injection to customize their meilisearch index, thus enabling a much broader range of options.

### Benefits:
Increased Flexibility: Developers can now make remote calls within the config transformer function, thereby providing additional flexibility when setting up their search functionality.

Enhanced Customization: By having access to the Awilix container, developers can leverage all registered services, repositories, and utilities to fully customize their MeiliSearch setup.

Adaptability: These changes make the medusa-plugin-meilisearch more adaptable to complex scenarios where a simple static product mapper is very often insufficient.

I believe these changes will be beneficial to the Medusa community and I look forward to your feedback.

### CODE REVIEW

**Comment by RegisWeduLabs** [comment]
I suggest changing the function getTransformedDocuments to this:
```
  async getTransformedDocuments(type: string, documents: any[]) {
    if (!documents?.length) {
      return []
    }

    const transformer =
      this.config_.settings?.[type]?.transformer ??
      (type === SearchTypes.indexTypes.PRODUCTS ? transformProduct : (document) => document)

    const results = await Promise.allSettled(documents.map(transformer));
    const rejected = <T,>(p: PromiseSettledResult<T>): p is PromiseRejectedResult => p.status === 'rejected';

    const errors = results.filter(rejected);
    if (errors.length) {
        console.error('An error occurred while transforming some documents:', errors, `for index ${type}`);
    }

    const fulfilled = <T,>(p:PromiseSettledResult<T>): p is PromiseFulfilledResult<T> => p.status === 'fulfilled';
    return results.filter(fulfilled).map((r) => r.value);
  }
```
This will catch and output any errors, and also make it so that custom indexes would also work as with the switch case atm - I don't think it will.

I've also added some other concerns (especially sending the container as a second arguments) in the discussion:
https://github.com/medusajs/medusa/discussions/4274#discussioncomment-6155017

I was going to send a PR - but might as well not "duplicate" and use this one.

**Comment by tsvetann** [comment]
@RegisHubelia thanks for your ideas. Please correct me if wrong, but I don't see how removing the switch statement will allow other indexes to be handled, given that searchService only listens for product events.

**Comment by tsvetann** [comment]
closes #4274

**Comment by RegisWeduLabs** [comment]
I've created a separate repository and will publish the package on npm shortly.  As there are quite a few changes, I prefered doing a separate package so I don't have to wait for medusa devs to merge the PR before being able to use it in multiple projects

https://github.com/Hubelia/medusa-plugin-meilisearch-multi-indexes

Feel free to do whatever you want with it.  This illustrate the idea so you can add custom indexes.   I'll need to add custom subscribers so to update the indexes if data changes so it automatically trigger reindexing of custom indexes.  I haven't tested toroughly, so probably not use it in production yet.

**Comment by tsvetann** [comment]
Yeah nice move mate. I decided to move to algolia but essentially did the same .... created a custom plugin. Nice work anyway thanks for sharing

**Comment by riqwan** [comment]
Hey, thanks for the PR! Since v2 brought a lot of architectural changes, we will be closing this ticket since it no longer applies to our new setup.

**Pull request closed without merging**
