### PR TITLE
docs: Add links in the Payment Architecture Overview documentation to the entities in the Entities Reference

### LINKED ISSUE #2148: Docs: add links in the Payment Architecture Overview documentation to the entities in the Entities Reference
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

In the [Payment Architecture Overview](https://docs.medusajs.com/advanced/backend/payment/overview) documentation, the entities `PaymentProvider`, `PaymentSession`, and `Payment` are mentioned but not linked.

### How can this issue be resolved?

1. Link to each of the entities mentioned earlier under the "Entity Overview" of each. For example, Add a link to the `PaymentProvider` entity under the "PaymentProvider Entity Overview" section. Make sure to only add it to the first time the entity is mentioned in that section.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

### PR DESCRIPTION
**Pull request by gefgu**
### What

Add links the [Payment Architecture Overview](https://docs.medusajs.com/advanced/backend/payment/overview) documentation:

1. The entities `PaymentProvider`, `PaymentSession`, and `Payment` are linked under the "Entity Overview" of each.

Fixes #2148 

### Why
Look: #2148 

### How
* Adding links using relative paths in markdown.

### Testing
None.

### CODE REVIEW

**Comment by shahednasser** [comment]
There are files in the PR that are not part of the PR. Can you either remove unrelated changes, or if it's easier fork the master branch again, make your changes, then send the PR?

**Comment by gefgu** [comment]
Ok

**Comment by gefgu** [comment]
@shahednasser I think everything is working now. Huge thanks for the patience :+1:

**Review by shahednasser — APPROVED** [review]

**Comment by shahednasser** [comment]
Thanks again! @gefgu

**Pull request merged**
