### PR TITLE
feat(admin-ui, medusa, medusa-react, medusa-js): Price List UI revamp

### PR DESCRIPTION
**Pull request by kasperkristensen**
### What
- Revamps the Pricing domain to improve workflow when creating, editing, and deleting Price Lists.
  - Introduces Bulk Editing for creating and editing Price List prices
  - Allows setting min/max requirements on Price List prices (requires #5137 to work)
- Adds new Form primitive for creating forms with proper labelling and error messaging.
- Adds new FilterMenu primitive for creating Table filters.
- Bumps `@medusajs/ui`, `@medusajs/icons`, and `@medusajs/ui-preset`
 
### What
- Adds new endpoint for bulk removing prices by product id's.

### What
- Adds new bulk endpoint to client

###
- Adds mutation hook for new bulk endpoint
- Fixes an issue where creating new Price List prices would not invalidate the Price List query cache

### CODE REVIEW

**Comment by srindom** [comment]
In stores with many regions you can't scroll the dropdown for configuring the bulk editor columns 

CleanShot 2023-09-28 at 3 25 27

**Comment by srindom** [comment]
I am unsure that the min/max quantity prices make sense in their current form. You need to be able to specify under which quantity conditions the prices quick in which is not supported in the bulk editor right now as far as I can tell. Also you would likely want to add multiple quantity breaks. E.g., from 1-10 price should be X, from 10-* price should be Y. 

Don't think we should include min/max pricing right now - it will require an entire new project to figure out the proper UI for that.

**Comment by srindom** [comment]
Table Header in Edit Prices - show **VariantVariant**

CleanShot 2023-09-28 at 3 32 30@2x

**Comment by srindom** [comment]
Would be optimal if we could invert colors on this fella:
CleanShot 2023-09-28 at 3 40 27@2x

**Comment by kasperkristensen** [comment]
@srindom I have fixed the double "Variants" and added some styling to prevent the Column selector menu from extending beyond the view. I have also opened a PR to fix it properly in the component over in medusajs/ui.

Ludvig was planning to invert the colors on the CommandBar anyways, so I'll push for that getting done and update and release a new version of the ui package.

Regarding the min/max quantity, I am not entirely sure I get what it is you think isn't supported here: for each region and currency price we also render a min and max quantity field, so for Price EUR I enter 10.00 in the amount, 1 in Min Quantity, and 10 in Max Quantity, that will create a price in list for variant_x with that amount and those requirements. 
I get your point with properly needing to be able to create multiple prices for each variant with different min/max requirements. It's something that a lot of people are requesting we get working, so if we could come up with some solution that can be included now I think that would great, one suggestion could be to do something along the the lines of this:

Group 1

Here you right click the variant title, which will display a menu that allows you to either insert a copy of it, or delete the row. Clicking Insert will create a new row for the same variant, which would allow you to set a new set of prices with different min/max quantities

Edit Prices 2

We could also add a slight color change of the duplicate rows or some other kind of indicator to make it more clear that this is a duplicate row.

Wdyt?

**Comment by olivermrbl** [comment]
Minor thing, but it looks as if the clickable/selectable area of the Price List type is limited to the height of the title: 

https://github.com/medusajs/medusa/assets/59018053/ffa1dc58-4177-4c73-a866-e92fee03b8c9


I realise, this is not super clear from the video. Let me know if it doesn't make sense

**Comment by kasperkristensen** [comment]
@olivermrbl Yea, Seb already mentioned it, and it's because the RadioGroup.Item and it's label is the only parts that are clickable. I have added a new component in medusajs/ui that I will replace this with. I am just waiting for Ludvig to wrap up updating the colors and shadows of a bunch of components and then I'll release that and use the new component instead.

PR for reference: https://github.com/medusajs/ui/pull/94

**Comment by olivermrbl** [comment]
The font size of the "value" of the divider section, e.g. Tue 3, Oct 2023, in the top card seems out of proportion. What do you think about decreasing the size to match the section's title? Think the difference in color does a good enough job of differentiating the two

CleanShot 2023-10-03 at 13 30 29@2x

**Comment by olivermrbl** [comment]
PriceList status dropdown item is missing its action and a pointer cursor:

https://github.com/medusajs/medusa/assets/59018053/2fffcc82-ccfd-4b38-b7d4-e25218dbcf56

**Comment by kasperkristensen** [comment]
@olivermrbl I have added the missing update function, and decreased the size of the details text, so it's only one size larger than the header. I think that is enough to make it a bit more harmonious, while still maintaining the visual hierarchy.

image

The missing pointer cursor has also been fixed over in @medusajs/ui

**Comment by olivermrbl** [comment]
> decreased the size of the details text, so it's only one size larger than the header. I think that is enough to make it a bit more harmonious, while still maintaining the visual hierarchy.

Looks good!

> The missing pointer cursor has also been fixed over in @medusajs/ui

Superb!

**Comment by olivermrbl** [comment]
@kasperkristensen can you add back the changeset, so we can publish a new snapshot? 😄

**Review by olivermrbl — APPROVED** [review]
🚢 🚢

**Pull request merged**
