### PR TITLE
 Fix() fix optional properties

### PR DESCRIPTION
**Pull request by adrien2p**
On product creation some fields was miss used
in the tests the type of a product was a string instead of an Object of type `ProductTypeReq`

### CODE REVIEW

**Comment by adrien2p** [comment]
Is that possible to re run the pipeline please 🙂

**Comment by srindom** [comment]
Can I ask you to use develop as base branch - you will probably have to rebase as well :)
Also there seems to be some weird linting fixes in some of the files.

**Comment by adrien2p** [comment]
All the integration tests are passing on my local machine, @srindom could you have a look please
Screenshot 2021-12-08 at 18 25 00

**Comment by adrien2p** [comment]
@srindom followup

**Comment by adrien2p** [comment]
@srindom do you think it will be merged ?

**Comment by srindom** [comment]
@adrien2p looks like something got mixed up in a merge..

**Comment by adrien2p** [comment]
Ill look into it, I did get a lot of conflict

**Comment by adrien2p** [comment]
@srindom its fixed and cleaned up

**Comment by srindom** [comment]
I am still seeing quite a lot of docs changes that I don't think should be part of this PR

**Comment by srindom** [comment]
Would it be better to maybe just checkout the files that relate to this change and create a new PR with those?

**Comment by adrien2p** [comment]
I will remove the doc changes from that pr

**Comment by adrien2p** [comment]
@srindom done, Ive rollback the doc changes, There must have been a character that was hidding.
Is the PR still adequate from your point of view? Since there was a lot of changes from the first opening 😂

**Comment by srindom** [comment]
@adrien2p - I think we can close this right?

**Comment by adrien2p** [comment]
Yes probably @srindom it is very old now

**Pull request closed without merging**
