### PR TITLE
feat(dashboard) admin 3.0 claims

### PR DESCRIPTION
**Pull request by fPolic**
**What**
- create a claim flow

---

**Depends on**
- [x] #6713

### CODE REVIEW

**Comment by olivermrbl** [comment]
Shipping for replacement items should not be return shipping:

image

**Comment by olivermrbl** [comment]
The subtitle is incorrectly positioned for "Shipping for replacement items":

image

**Comment by olivermrbl** [comment]
Question: What do we plan to add here and when?

image

**Comment by fPolic** [comment]
> Question: What do we plan to add here and when?

I've added a placeholder UI, the other issues should be resolved as well.

**Pull request closed without merging**
