### PR TITLE
feat: Move userpass default definition to defineConfig instead of a hard-coded value

### PR DESCRIPTION
**Pull request by sradevski**
https://github.com/medusajs/medusa-starter-default/pull/1408 should be merged first.

FIXES #8452 
CLOSES CC-334

### CODE REVIEW

**Review by carlos-r-l-rodrigues — APPROVED** [review]
LGTM

**Comment by carlos-r-l-rodrigues** [comment]
you might need a changeset

**Review by olivermrbl — APPROVED** [review]
LGTM – nice one

**Pull request merged**
