### PR TITLE
Docs/issue 2324

### PR DESCRIPTION
**Pull request by appledora**
- What - Solving PR #2324 
- Why - The [Gatsby storefront quickstart documentation](https://docs.medusajs.com/starters/gatsby-medusa-starter)'s title can be improved to avoid confusion, especially when multiple tabs are open. The same goes for the [Next.js Storefront](https://docs.medusajs.com/starters/nextjs-medusa-starter). 
- How - updated files `docs/content/starters/gatsby-medusa-starter.md` and `docs/content/starters/nextjs-medusa-starter.md`
- Testing - it's a markup file, so should not require anything other than manual testing.

Happy to hear feedbacks!!

### CODE REVIEW

**Review by shahednasser — APPROVED** [review]

**Comment by shahednasser** [comment]
Hi @appledora I just noticed you opened this PR against the `develop` branch, but it should be against the `master` branch as explained in our contribution guidelines. Can you create a new branch from the `master` branch and make the same changes again? I'll close this PR for now.

**Comment by appledora** [comment]
@shahednasser oh... had checked out the contribution guideline here https://github.com/medusajs/medusa/blob/master/CONTRIBUTING.md which says to open branches against the develop branch. So should I branch out from master instead?

**Comment by shahednasser** [comment]
No worries, but we mention in that document to refer to the documentation for contribution guidelines related to documentation.

Yes that's what you should do

**Comment by appledora** [comment]
@shahednasser considering the confusion I faced regarding the `contribution guideline`, do you think it should be modified to make it more specific for the participants? Although, I am not sure if the confusion i was having happened with other participants as well :face_with_head_bandage:

**Pull request closed without merging**
