### PR TITLE
chore(medusa-payment-stripe): Change transction management

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
At the moment, if there is an error thrown by the completion, the entire transaction is rollback, including the idempotency key.

**How**
With a higher transaction, any errors are catched, the strategy manages the rollback of the nested transactions while the parent transaction does not rollback

### CODE REVIEW

**Comment by adrien2p** [comment]
@olivermrbl would like your opinion before making it ready

**Comment by olivermrbl** [comment]
Curious, what sparked the need for these changes?

**Comment by adrien2p** [comment]
> Curious, what sparked the need for these changes?

The idea is that since the transaction was local to the util method, when it throws the idempotency key gets rollback along side the rest. Now, since the error is catched, we avoid the rollback meaning that the idempotency key will still be there. Let me know if you want to discuss it, i wanted your opinion.

**Comment by adrien2p** [comment]
But before anything, i ve spotted an issue while re reading it. I ll move the idempotency key management at the top level and pass it down to the subsequent calls instead to insure the overall integrity

**Comment by adrien2p** [comment]
ill close this one for now

**Pull request closed without merging**
