### PR TITLE
Turkish language support

### PR DESCRIPTION
**Pull request by ucibar**
Turkish language support for the Admin dashboard.

### CODE REVIEW

**Comment by undercontr** [comment]
I was just working on this :)

**Comment by ucibar** [comment]
Hi @undercontr, I translated the Turkish translation with AI(google bard) and I didn't examine the translation results in detail. I just looked superficially whether it was translated properly or not. If you think your translation is more accurate and handcrafted, I can close the PR and we can use your translation/PR.

**Comment by undercontr** [comment]
> Hi @undercontr, I translated the Turkish translation with AI(google bard) and I didn't examine the translation results in detail. I just looked superficially whether it was translated properly or not. If you think your translation is more accurate and handcrafted, I can close the PR and we can use your translation/PR.

Hey @ucibar, we team of 2, used professional translation techniques to provide translation to Medusa, we used crowdin.com to organize the translation process, we want to take a look to your translation and adopt the parts where's possible, or vice versa. :) We support this PR to be merged for Medusa to have initial Turkish translation.

We are currently in QA phase of the translation. And we are trying to add translation support for Settings page (I have a PR open to change in the code).

**Comment by ucibar** [comment]
@undercontr, Thank you for your effort and professional approach 🙏.  

Then, as you said;  Let's proceed with this PR as the initial phase and correct the areas you see wrong or missing etc.

Thank you also for your contribution to translating the Settings page.

**Comment by ahgsql** [comment]
I also just committed a Turkish translation, what a coincidence to have 2 (+1) pr's in 3 days about Turkish Translation guys :)

**Comment by undercontr** [comment]
@ucibar @ahgsql Guys if you're interested I can invite you to translation project in Crowdin :)

**Comment by olivermrbl** [comment]
@ucibar, we appreciate the contribution. However, our admin system is currently undergoing a redesign that includes improvements to and simplifying of translations and we will therefore not accept this PR. 

We expect to go live with the update next month. If you are still interested in contributing then, we would very much appreciate a new PR with changes that follow the new format.

I apologize for the slow response time.

**Comment by undercontr** [comment]
Hey Oliver, no problem at all. We will be gladly translate based on the new changes on the translation. We'll open PR afterwards.

**Comment by olivermrbl** [comment]
@undercontr, thanks! 🫶

**Comment by undercontr** [comment]
@ucibar Please let me know if you want to be in the translation process in the Crowdin.

**Comment by ucibar** [comment]
Hi @undercontr, I don't have time for the translation contribution at the moment, sorry 😅. thank you for the invitation and your contribution to medusa .

I very excited to the new admin panel and Turkish language support guys 😊

**Comment by undercontr** [comment]
@ucibar Hey no problem :) we are two devs already. I didn't want your labor go to waste. But maybe later we may evaluate the translation

**Pull request closed without merging**
