### PR TITLE
chore(admin-ui): wrap Table.HeadRow with head tag for publishable-api-keys

### PR DESCRIPTION
**Pull request by wangjue666**
resolve console error

image

### CODE REVIEW

**Comment by wangjue666** [comment]
> 他们要推出新的[admin](https://github.com/medusajs/medusa/tree/develop/packages/admin-next)面板了，只是告诉你一声，以防你不知道。另外他们在括号里一般都只写改动对应的package的名字。

image

完成度差很多呢 就一个产品列表页面做了,还很不完善，远远没法二次开发呢

**Comment by wangjue666** [comment]
@chrislaai  兄弟可以加个微信相互交流交流 我的微信: `wxid_5syn3tslrscv22`

**Comment by wangjue666** [comment]
> > wxid_5syn3tslrscv22
> 
> 搜不到啊

额 你加 `15110436770`

**Comment by riqwan** [comment]
Hey, thanks for the PR! Since v2 brought a lot of architectural changes, we will be closing this PR since it no longer applies to our new setup.

If you would still like to open this PR, please rebase with the v1 branch and re-request a review & we'll get back on it quickly.

**Pull request closed without merging**
