### PR TITLE
chore: update package node engines

### PR DESCRIPTION
**Pull request by riqwan**

### CODE REVIEW

**Review by adrien2p — APPROVED** [review]
LGTM

**Review by olivermrbl — COMMENTED** [review]
Should we specify `engines` in other packages too?

**Comment by adrien2p** [comment]
> Should we specify `engines` in other packages too?

Ahah u suggested the same

**Comment by olivermrbl** [comment]
should this be a minor, I am not sure

**Comment by adrien2p** [comment]
> should this be a minor, I am not sure

in theory changing something like that is a breaking change and should only appears during major upgrade. Since our minor works as the major, it should be a minor

**Review by adrien2p — APPROVED** [review]

**Comment by olivermrbl** [comment]
> in theory changing something like that is a breaking change and should only appears during major upgrade. Since our minor works as the major, it should be a minor

This was what I was thinking too. Let's do a minor 👍

**Comment by olivermrbl** [comment]
Duplicate of #5812

**Pull request closed without merging**
