### PR TITLE
fix(admin-ui): Price list domain fixes

### PR DESCRIPTION
**Pull request by kasperkristensen**
**Fixes**
- Fixes an issue where click the Delete button on a table item in the Price List overview would also navigate to the Price Lists page
- Fixes an issue where Region prices were not showing which region they belong to in the Bulk Editor
- Fixes an issue where the wrong widgets were being injected into the Price List domain

**Improvements**
- Align label for Expiry date field
- Add form validation to require setting the prices of at least one product variant when creating or adding prices to a Price List.
- Show a prompt warning if prices have not been set for all selected products in the create and add product flows.

### CODE REVIEW

**Comment by shahednasser** [comment]
@kasperkristensen seems like there's no snapshot for the `admin-ui` generated. Is it because a changeset is missing?

**Review by shahednasser — APPROVED** [review]
LGTM! (didn't get the chance to test the change of the expiry date label, but I don't think it's necessary to create a snapshot just for that).

**Comment by srindom** [comment]
A small todo: Can we add the currency code in the header too. It should align with the bulk editor used for editing prices on a product. See screenshot below.

CleanShot 2023-10-11 at 8  38 22@2x

Currently, the header only shows the name of the Region.

**Pull request merged**
