### PR TITLE
hotfix(medusa): Temporary multi-warehouse support for draft orders

### PR DESCRIPTION
**Pull request by pKorsholm**
**What**
- Remove reservation and quantity validation when creating draft orders

**Why**
- Since we base availability on sales channel and draft orders don't have sales channels, the check would fail when trying to mark a draft order as payed. 
- Choosing to remove the validation is not optimal but allows the DO flow to work properly. Reservations can be made afterwards if necessary.

Would love to hear what you think @srindom

If this is not an acceptable solution we should add sales channels or direct locations on line items when creating draft orders.

### CODE REVIEW

**Review by srindom — COMMENTED** [review]
Please add integration tests

**Comment by juanzgc** [comment]
Personally, I don't think this is the _right_ approach. Instead we should force a selection of the Sales Channel and Stock Location when selecting Products for a Draft Order.

See issue: https://github.com/medusajs/medusa/issues/3681

**Review by olivermrbl — APPROVED** [review]
LGTM

**Comment by pKorsholm** [comment]
@juanzgc 
We're prioritizing this as an initial solution, but we will include allocations for line items in draft-orders in the first release after 1.8. This shouldn't cause errors in stock since inventory module stock is adjusted only on fulfillment and allocations are not strictly required in order to fulfill on order.

**Review by olivermrbl — APPROVED** [review]

**Pull request merged**
