### PR TITLE
Incorrect spelling of word medusa

### PR DESCRIPTION
**Pull request by MistaZidane**
Corrected spelling of medusa in packages/medusa-payment-paypal and packages/medusa-payment-stripe

### CODE REVIEW

**Review by shahednasser — APPROVED** [review]
Thanks for catching that @MistaZidane !

**Comment by MistaZidane** [comment]
> Thanks for catching that @MistaZidane !

Welcome @shahednasser

**Comment by olivermrbl** [comment]
@MistaZidane Please resolve conflicts, so it's ready for merge 💪

**Comment by shahednasser** [comment]
@MistaZidane you need to resolve conflict again and rebase from master because we've had a new release 😄

**Comment by riqwan** [comment]
Hey, thanks for the PR! Since v2 brought a lot of architectural and API changes on the backend, we will be closing this ticket.

**Pull request closed without merging**
