### PR TITLE
chore: Update modules providers configuration with 'identifier' and 'PROVIDER'

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
- standardize provider `identifier` static property. Now all providers must have a static property `identifier` which will be used to register the provider into the module container.
- The `id` in the providers configuration can still be provided in the defineConfig if some provider can have multiple instances (e.g stripe per region)
- All provider id have been fixed in all modules to be properly generated (e.g `pp_stripe_the-given-id` or `pp_stripe` instead of `pp_stripe_` or `pp_stripe_undefined`

**Breaking changes**
- The provide id in `region_provider_id` might be broken after the provider are reloaded since their id have been fixed. You might need to update those manually or regenerate those link
- The auth module providers have been also aligned to the convention of having identifier and eventually an id and their generated id will following the same convention

### CODE REVIEW

**Review by carlos-r-l-rodrigues — APPROVED** [review]

**Comment by adrien2p** [comment]
cc @sradevski @christiananese you might need to take a look at this one, we can discuss if you need any help for the changes

**Review by sradevski — APPROVED** [review]
LGTM. This shouldn't affect us I believe, we don't have any custom providers implemented for now.

**Comment by adrien2p** [comment]
> LGTM. This shouldn't affect us I believe, we don't have any custom providers implemented for now.

It affect the core providers as well, the auth providers have been aligned as well, maybe that can impact you?

**Review by olivermrbl — COMMENTED** [review]
wonder if we should snake_case the IDs for consistency? It will be a breaking change regardless, so thought we might as well

**Comment by olivermrbl** [comment]
I don't think this breaks the auth domain, because the `id`s specified in `medusa-config.js` in the platform project happen to be the same as the provider IDs.

**Comment by adrien2p** [comment]
> I don't think this breaks the auth domain, because the `id`s specified in `medusa-config.js` in the platform project happen to be the same as the provider IDs.

-- In order to normalize and be consistent, now the auth also concatenate the identifier and id which was not the case before, that can be breaking too --

nvm the above, we didn't, but I thought we did 😂

**Review by olivermrbl — APPROVED** [review]
LGTM

**Pull request merged**
