### PR TITLE
feat: Add description prop in stripe provider

### LINKED ISSUE #1401: Feature: Allow description & other params to be passed on stripe plugin
We can't use stripe in India without providing description, so wherever we are creating intents we need to pass a description via config file.

image

```js
const paymentIntent = await stripe.paymentIntents.create({
  amount: 1099,
  currency: 'usd',
  description: 'Software development services',
});
```

### PR DESCRIPTION
**Pull request by ShivamJoker**
Fixes #1401 

Example in config
```js
  {
    resolve: `medusa-payment-stripe`,
    options: {
      api_key: STRIPE_API_KEY,
      webhook_secret: STRIPE_WEBHOOK_SECRET,
      description: "Digital arts/services",
    },
  },
```

### CODE REVIEW

**Comment by adrien2p** [comment]
@ShivamJoker shouldn't the description part of the cart metadata? in order to put anything desired?

**Comment by ShivamJoker** [comment]
I think we can do that as well but ideally someone or some business will have only one industry in the store.

**Comment by ShivamJoker** [comment]
Also I don't know much about metadata so if you could configure it then it might be good as well. But for a quick fix this should do the job.

**Comment by olivermrbl** [comment]
Fixed in #1401

**Pull request closed without merging**
