### PR TITLE
chore(medusa): Update request-ip dependency version

### PR DESCRIPTION
**Pull request by pevey**
This updates the request-ip package dependency in @medusajs/medusa.

This resolves the critical security warnings seen when creating a new medusa backend OTHER THAN medusa-admin related issues.  Because the admin is undergoing an extensive rewrite, I didn't address the older version of node-fetch that is at the root of those issues.

### CODE REVIEW

**Review by olivermrbl — APPROVED** [review]
lgtm, thanks @pevey !

**Comment by olivermrbl** [comment]
@pevey can I get you to resolve conflicts, so we can merge? 🙏

**Comment by pevey** [comment]
I'm not sure I have permission to push a new lockfile.  I'll give it a try.

**Comment by pevey** [comment]
It looks like the lock file in the branch has been added, but it may not be up to date now with the develop branch.  It don't believe I have permission to resolve the conflict.  Or maybe you could point me in the right direction.

Screenshot:
Screenshot 2023-08-02 070727

**Comment by olivermrbl** [comment]
~~If you sync your fork with the latest changes from `develop`, you should be able to merge that into this branch and resolve the conflict~~

~~Let me know if it doesn't work, then I can investigate~~

Nevermind, I will attend to it! :)

**Pull request merged**
