### PR TITLE
fix(medusa): add migration - use numeric type - product

### PR DESCRIPTION
**Pull request by irpic**
**What**

- product migration: use numeric data type for product dimensions(weight, length, height, width).

It is now possible to store dimensions with decimal points rather than being limited to integer numbers.

### CODE REVIEW

**Comment by adrien2p** [comment]
@irpic thanks a lot for the contribution, though, I am not sure the amount should be a numeric type, there are lot of implication to it that are not considered at all in that pr

**Comment by irpic** [comment]
> @irpic thanks a lot for the contribution, though, I am not sure the amount should be a numeric type, there are lot of implication to it that are not considered at all in that pr

Hello @adrien2p . Thank you for building such a GREAT product!

I've tried to set the length of a product 2.4 and I wasn't able to set so. That's why I decided to set it as a numeric value.

In order to accept numeric values I found we need to add a migration and update admin UI. Do I miss anything else?

**Review by adrien2p — APPROVED** [review]
LGTM

**Comment by irpic** [comment]
Due to some changes on my Github, I canceled this PR and [created a new one here](https://github.com/medusajs/medusa/pull/3741).

**Pull request closed without merging**
