### PR TITLE
chore(medusa): Align build query utils

### PR DESCRIPTION
**Pull request by adrien2p**

### CODE REVIEW

**Review by olivermrbl — APPROVED** [review]
Should we deprecate the one in `@medusajs/medusa`?

Also, please add a changeset :)

**Comment by adrien2p** [comment]
@olivermrbl I was thinking, since frane is moving them around for the reorganisation, would it make sense that @fPolic include this changes in his pr?

**Comment by fPolic** [comment]
> @olivermrbl I was thinking, since frane is moving them around for the reorganisation, would it make sense that @fPolic include this changes in his pr?

I can add this to my PR since I've changed a couple of things related to `build-query` :)

**Comment by olivermrbl** [comment]
@fPolic sounds good!

**Pull request merged**
