### PR TITLE
fix: load custom modules by path

### PR DESCRIPTION
**Pull request by carlos-r-l-rodrigues**
What:
medusa-config.js loading custom modules by their path.

```typescript
{
  modules: {
    internalModule: {
      scope: MODULE_SCOPE.INTERNAL,
      resources: MODULE_RESOURCE_TYPE.SHARED,
      resolve: "./internal_module",
      definition: {
        key: "internalModule",
        registrationName: "internalModule",
      },
    },
  }
}
```

### CODE REVIEW

**Review by olivermrbl — APPROVED** [review]
Great!

**Comment by olivermrbl** [comment]
Looks like this broke something in the core @carlos-r-l-rodrigues

**Comment by carlos-r-l-rodrigues** [comment]
can I merged it @olivermrbl ?

**Comment by olivermrbl** [comment]
Yes should be good. Will slap a label on it

**Pull request merged**
