### PR TITLE
fix(create-medusa-app): error in build step

### PR DESCRIPTION
**Pull request by shahednasser**
## What

Resolves error when using `yarn create medusa-app` during build step

## How

yarn v2+ defaults to using `pnp` for `nodeLinker` for the overall yarn create/dlx commands, and we can't control it from within `create-medusa-app`.

So, this PR adds a preliminary step that checks if Yarn is compatible, and if not, shows instructions to the user on setting the `YARN_NODE_LINKER` environment variable.

## Testing

- With a yarn v2+, run the `yarn create` with the latest snapshot in this PR. You'll find an error indicating that you should use `YARN_NODE_LINKER`. 
- Try then running the same command by passing `YARN_NODE_LINKER=node-modules` before it. The error shouldn't be shown and all the steps of create-medusa-app should run successfully.
- Try running the latest snapshot with `npx`. The command should execute normally.

### CODE REVIEW

**Comment by srindom** [comment]
Do we know what it would take to make us compatible with pnp?

**Comment by olivermrbl** [comment]
I am unable to reproduce the error running `yarn create medusa-app@latest` with yarn version 3.6.3 installed

**Comment by shahednasser** [comment]
@srindom honestly not sure, I can look into it but I think there's a lot of references to `node_modules` within the core/starter repo, so we'd have to start there

**Pull request closed without merging**
