### PR TITLE
Fix order tax_rate type

### PR DESCRIPTION
**Pull request by dwene**
fix(order): tax_rate column should be numeric, not integer, since region.tax_rate uses numeric

When I set my region `tax_rate` to 8.25, it failed to create the order due to the order.tax_rate column being an `integer` type.  In Texas we have a tax_rate of 8.25, so it would be nice to support non-integer tax rates.

Fixes: https://github.com/medusajs/medusa/issues/869

### CODE REVIEW

**Review by srindom — APPROVED** [review]
Thanks! Makes a lot of sense :)

**Comment by srindom** [comment]
Can I ask you to make sure that the integration tests pass before I merge :)

**Comment by dwene** [comment]
@srindom Ok, I see what the issue is here now.

Looks like typeorm returns all `decimal` columns to strings because postgres supports storing more precision than javascript number.

https://github.com/typeorm/typeorm/issues/873

I think the `real` postgres type (4 byte float, supporting up to 6 significant figures) would be fine for this, it supports way more precision than should ever be needed for `tax_rate`. If you're good with it, I'll convert both the `order.tax_rate` and `region.tax_rate` to  the `real` postgres type.

**Comment by srindom** [comment]
Looks like a good solution; do you know if this `real` type also works with SQLite? If it does let's go :)

**Comment by dwene** [comment]
@srindom Good thought! I forgot Medusa supports SQLite. 

Looks like It does support the `real` type. They aren't technically the same size (postgres `real` is 4-bytes, SQLite `real` is 8-bytes), but both fit within the javascript number size of 8 bytes, so it should work fine.

**Review by srindom — APPROVED** [review]
Great! Have also tested the migration on a larger data set and it works perfectly 👍

**Pull request merged**
