### PR TITLE
fix(utils): Mikro orm prop filtering should check existence

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
- Should return non decorated but visible properties.
- Should only prevent circular on non scalar fields

### CODE REVIEW

**Comment by adrien2p** [comment]
@olivermrbl for some reason, the previous pr was containing a bug, though, all pipeline were green.

cc @riqwan, I was surprised that they ran in a few sec when you look in details, something link to the cache maybe?

**Comment by adrien2p** [comment]
I ll try to update the test to reflect that

**Review by carlos-r-l-rodrigues — APPROVED** [review]

**Comment by adrien2p** [comment]
@riqwan , If i run the test locally, they are failing, though the pipeline is green

**Comment by riqwan** [comment]
@adrien2p yeah, the cache doesn't seem to be busting. Let me take a look

**Pull request merged**
