### PR TITLE
fix(admin-ui): Add missing SO relation

### PR DESCRIPTION
**Pull request by olivermrbl**
Solves #4561

### CODE REVIEW

**Comment by adrien2p** [comment]
@olivermrbl here the fix https://github.com/medusajs/medusa/pull/4600

**Comment by olivermrbl** [comment]
@adrien2p – shipping option is still missing, so this PR is relevant

**Comment by adrien2p** [comment]
> @adrien2p – shipping option is still missing, so this PR is relevant

yes both pr needs to be integrated right?

**Comment by olivermrbl** [comment]
Yep !

**Pull request merged**
