### PR TITLE
feat(medusa): Improve base-service

### PR DESCRIPTION
**Pull request by adrien2p**
**Goal**

Extract Refactor the `BaseService`
- Create a `TransactionBaseService` that will hold all the methods related to the transaction management around the services.
   - The method implemented by the service are
       - `withTransaction`
       - `shouldRetryTransaction`
       - `atomicPhase_`
   - All the typings has been reworked in order to represent what really is required and described it as best as possible
   - Update methods visibility

- Move utilities methods to there own utils file under the utils directory
    - `buildQuery`
    - `setMetadata`
    - `validateId`

**Information**
As you can see, the example migration in the `CartService` use `arguments[0]` that is passed to the parent constructor.
I choose to do that because it is easy for someone to add a new injected properties from the container and forget to add it to the super call. That way, you can add new injection parameters and they will be preserved and pass to the super automatically. (any suggestions?)

### CODE REVIEW

**Comment by adrien2p** [comment]
@srindom always the same tests that fails no matter the PR 😂

**Comment by adrien2p** [comment]
@srindom could you re run the pipe please?

**Comment by adrien2p** [comment]
@srindom should we merge that in order for you to update the job pr?

**Comment by srindom** [comment]
@adrien2p - I am a bit on the fence about letting the new BaseService handle the container and `withTransaction` logic. 

To me, it seems that there is a bit too much magic going on with the constructor, etc.

Should we maybe stick with the old way of handling constructor + `withTransaction` in the child class and then maybe consider a composition pattern in the future instead?

**Comment by adrien2p** [comment]
From my point of view the baseService can have a default implementation that can be used and override if necessary. At the moment all the service could use the default implementation. Dont see the magic here 🥹

**Comment by adrien2p** [comment]
Also, this approach is a common approach and still respect the Liskov substitution principle 👍

**Comment by srindom** [comment]
My concern comes from things like this: https://github.com/medusajs/medusa/pull/1337/files#diff-66a678bf767f12de5df82d02971b73d1ef190e2dd119041eb773f0ce27ccea95R22-R23

It is not obvious that there is an issue here, but since the manager is not carried over to the super, all the transaction logic would not work. Things like this are harder to catch because you need to know about BaseService and its inner workings to understand why the manager has to be passed down.

Another thing is that it is not necessarily a given that all services have to deal with transactions (or buildQuery for that matter), so it seems like a hack to be stuffing a bunch of "utilities" in the BaseService just because it has been convenient in the past. 

I might be overthinking things a bit, but these are my thoughts atm haha

-- 

Maybe an improvement to the current implementation that would take away some of the magic in the constructor would be to have the BaseService constructor like this:

```
constructor(manager: EntityManager, otherDependencies) {
  this.manager_ = manager
  // keep the otherDependencies
}
```

That would force child classes to do:

```
constructor({ manager, .... }) {
  super(manager, ...)
}
```

**Comment by adrien2p** [comment]
I am agree on certain point with you,
I have a counter proposition for you 😅

We can remove the manager property from the baseService, make the baseService abstract which seams logic since it has no purpose to be instanciate as it is, and just add an abstract protected property manager that can be undefined or EntityManager, what do you think?

**Comment by adrien2p** [comment]
Make the baseService and Abstract class with an abstract protected property manager

**Comment by adrien2p** [comment]
We must think of better naming for that class that indicates that its purpose is around business logic and data manipulation

**Comment by adrien2p** [comment]
@srindom wdyt?

**Review by pKorsholm — COMMENTED** [review]
LGTM, though would love to get @srindom and @olivermrbl to weigh in.

wrt. the `arguments[0]` I think it's fine, I guess the alternative would be to spread the parameters afterward in the constructor which comes to the same.

**Comment by adrien2p** [comment]
> LGTM, though would love to get @srindom and @olivermrbl to weigh in.
> 
> 
> 
> wrt. the `arguments[0]` I think it's fine, I guess the alternative would be to spread the parameters afterward in the constructor which comes to the same.

Ahah yeah it is either use ...args but in the end you end up using the container as a service locator (even if once it use built it is used as that) or just eventually go back to what I did previously which was to pass the injected dependencies one by one. I am open to suggestions and I tried to choice the easiest way to achieve it without having to repeat ourselves over and over 😂

**Review by srindom — APPROVED** [review]
LGTM!

**Pull request merged**
