### PR TITLE
fix(product, types): correct path for migration files + fix types on products service module

### PR DESCRIPTION
**Pull request by riqwan**

### CODE REVIEW

**Review by carlos-r-l-rodrigues — APPROVED** [review]
LGTM

we can remove - `import { Utils } from "@mikro-orm/core"`

**Comment by riqwan** [comment]
@carlos-r-l-rodrigues removed, I've added some type fixes in as well that I came across.

**Comment by olivermrbl** [comment]
> removed, I've added some type fixes in as well that I came across

should be reflected in the changeset 👍

**Pull request merged**
