### PR TITLE
feat(oas): Improve OAS by adding missing type object to schemas

### PR DESCRIPTION
**Pull request by asprouse**
This PR improves the OAS by adding `type: object` to schemas that have `properties` and no `type`. While this attribute is not required for a valid spec, omitting it opens the possibilities of non-object input. See https://stackoverflow.com/a/47390723 for a detailed description of this behavior. When generating code or schemas from an OAS with tools like takeshape.io having `type` attributes is important to get the correct behavior.

### CODE REVIEW

**Comment by srindom** [comment]
@patrick-medusajs did we already do this with your OAS work or would it make sense to include?

**Comment by patrick-medusajs** [comment]
@srindom We did similar work but we didn't fix objects in arrays. We actually have a Linear for it - CORE-1024.  
This would be a great addition to include. I can review the OAS changes in the JSDoc comments.

@shahednasser How would you like to proceed for merging such changes. Should it target `develop`? Would you prefer to exclude changes in `docs` and only merge changes in `api/routes`?

**Comment by patrick-medusajs** [comment]
@asprouse Would would mind rebasing your branch to point to `medusajs:develop` and remove `docs` from the PR?

**Comment by asprouse** [comment]
> @asprouse Would would mind rebasing your branch to point to `medusajs:develop` and remove `docs` from the PR?



> @asprouse Would would mind rebasing your branch to point to `medusajs:develop` and remove `docs` from the PR?

@patrick-medusajs I rebased the PR as re-targeted it to `develop`. The docs changes were dropped in the rebase.

**Review by patrick-medusajs — APPROVED** [review]
LGTM

**Review by olivermrbl — APPROVED** [review]
LGTM! @asprouse before we merge, can I get you to merge in latest from `develop` and push?

**Comment by patrick-medusajs** [comment]
🎉  @asprouse, thank you for your contribution. Cheers!

**Pull request merged**
