### PR TITLE
fix: product module joiner config

### PR DESCRIPTION
**Pull request by adrien2p**
**what**
Fix product module joiner config missing suffix

FIXES FRMW-2600

### CODE REVIEW

**Review by sradevski — APPROVED** [review]

**Comment by adrien2p** [comment]
Not to be merged, the method suffix is computed under the hood automatically. Ill rework this pr to provide the true fox

**Comment by adrien2p** [comment]
@shahednasser you can test the next snapshot 👍 
Just to let you know, the field alias being used for the remote query is the snake case version of the entity name (singular/plural depending on isList). Meaning that in your scenario, you want to add the following field: `product_variant.*`. don't know if that part is documented

**Comment by shahednasser** [comment]
@adrien2p I tried that but got an error that `product_variant` property doesn't exist. Would this be fixed with this change?

**Comment by adrien2p** [comment]
> @adrien2p I tried that but got an error that `product_variant` property doesn't exist. Would this be fixed with this change?

yes it will 👍 keep me in touch, lets generate a snap

**Review by olivermrbl — APPROVED** [review]

**Review by shahednasser — APPROVED** [review]
LGTM issue fixed 🎉

**Pull request merged**
