### PR TITLE
fix/2034 product create profile

### PR DESCRIPTION
**Pull request by richardwardza**
Fixes: https://github.com/medusajs/medusa/issues/2034

# What

If the `profile_id` is not supplied then this adds a lookup for the `shippingProfile` in the `create` in `ProductService`.
This is done in the `api` endpoint but not the service and creating a new product via the service has the the `profile_id` as `optional` so if it's not passed in it should be found else the `create` results in a database error of `profile_id` cannot be null.

# Why 

Prevent database error of "`profile_id` cannot be null".

# Testing

```
Test Suites: 2 failed, 170 passed, 172 total
Tests:       3 failed, 944 passed, 947 total
Snapshots:   4 passed, 4 total
Time:        72.134s
Ran all test suites.
```

The failed tests are related to `feature-flag` issues. (I may be missing an `env` variable?)

### CODE REVIEW

**Review by srindom — COMMENTED** [review]
Thanks for the contribution! 

I would prefer that we throw a "pretty" error from the ProductService when no `profile_id` is provided in the create method, instead of changing the current behavior.

Also, we generally want to move towards never having more than one service depend on a repository. This change introduces an additional dependency on ShippingProfileRepository.

**Comment by richardwardza** [comment]
> Thanks for the contribution!
> 
> I would prefer that we throw a "pretty" error from the ProductService when no `profile_id` is provided in the create method, instead of changing the current behavior.
> 
> Also, we generally want to move towards never having more than one service depend on a repository. This change introduces an additional dependency on ShippingProfileRepository.

Hi @srindom 

Thank you for the feedback!

I'll close this PR and go the route of making the [profile_id in CreateProductInput](https://github.com/medusajs/medusa/blob/0703dd94e88be47fdc61c1caa451c050fbabbef3/packages/medusa/src/types/product.ts#L137) mandatory then and see where that leads.

This will be a change to the inputs to the `ProductService.create` but it's more "true". It doesn't make sense to leave it as optional and then fail on the create (but I can still put in a message for if it is missing).

**Comment by srindom** [comment]
Thanks @richardwardza - this sounds like a perfect approach 🙏

**Comment by olivermrbl** [comment]
@richardwardza Everything alright? Let us know if we can be of any assistance!

**Comment by richardwardza** [comment]
Hi @olivermrbl  - apologies for the delay, I've started a new 4 week contract and am busy getting settled in.
I have this done, just need to update the existing test and add a new one. I'll have it finished this evening (it's taken too long already!) :)

**Comment by richardwardza** [comment]
@olivermrbl  - PR is up at https://github.com/medusajs/medusa/pull/2065

**Comment by olivermrbl** [comment]
Amazing thanks @richardwardza !

**Pull request closed without merging**
