### PR TITLE
fix(medusa): downgrade `papaparse` version

### PR DESCRIPTION
**Pull request by fPolic**
**What**
- latest minor version bump of the library is causing several issues while importing a CSV file - fixing the version to 5.3.2 seems to fix the issues
- more readable formatting of error message
- add types

### CODE REVIEW

**Comment by raukaute** [comment]
@fPolic 

Can you add some information on the several issues this commit fixes?

**Review by adrien2p — APPROVED** [review]
LGTM 💪 do you have an idea of which issues it is fixing so far? was it a breaking changes on their side? Should we warn them?

**Comment by olivermrbl** [comment]
@fPolic merging - will you get back on the comments? :)

**Comment by fPolic** [comment]
> LGTM 💪 do you have an idea of which issues it is fixing so far? was it a breaking changes on their side? Should we warn them?

@adrien2p There were different errors reported depending on the input file but all were a result of broken parsing, also the issue with appended `_{index}` values instead of `null` is fixed by this PR.
There has been a couple of similar reports on their GitHub page so they are aware of the problem.

**Pull request merged**
