### PR TITLE
feat(medusa): Allow all relations on `/admin/*` endpoints

### PR DESCRIPTION
**Pull request by fPolic**
**What**
- allow all fields/relations to be requested on the admin endpoints
- cleanup of unused `allowedFields` and `allowedRelations` in controllers

---

RESOLVES CORE-899

### CODE REVIEW

**Review by adrien2p — CHANGES_REQUESTED** [review]
Shouldn't the admin be allowed to any fields in reality? I would say that only the store should be constraints but not necessarily the admin wdyt?

**Comment by olivermrbl** [comment]
> Shouldn't the admin be allowed to any fields in reality? I would say that only the store should be constraints but not necessarily the admin wdyt?

Yes, I think this is reasonable. 

@fPolic Would you be up for changing the scope of this PR to be centered around updating all allowed relations for `/admin/*` to allow for everything?

**Comment by olivermrbl** [comment]
Alternatively, we can split it into several PRs - also totally fine with me.

**Comment by adrien2p** [comment]
> Alternatively, we can split it into several PRs - also totally fine with me.

I think ew can just remove it in those routes in order to resolve the issues and create a new linear issue that @fPolic can handle immediately after. wdy? @olivermrbl @fPolic

**Comment by fPolic** [comment]
> > Shouldn't the admin be allowed to any fields in reality? I would say that only the store should be constraints but not necessarily the admin wdyt?
> 
> Yes, I think this is reasonable.
> 
> @fPolic Would you be up for changing the scope of this PR to be centered around updating all allowed relations for `/admin/*` to allow for everything?

Of course, I can do it in this PR :)

**Comment by olivermrbl** [comment]
Sure, all of them or just the order routes - both approaches are fine - so whatever you find best @fPolic :)

**Review by adrien2p — APPROVED** [review]
LGTM, it looks good 🎉

**Review by olivermrbl — APPROVED** [review]
LGTM!

**Pull request merged**
