### PR TITLE
chore(framework): medusa app loaders

### PR DESCRIPTION
**Pull request by adrien2p**
RESOLVE FRMW-2636

**What**
cleanup and move medusa app loader for now

### CODE REVIEW

**Review by olivermrbl — APPROVED** [review]
🧹 💪

**Comment by adrien2p** [comment]
I will do a last thing before merging

**Comment by adrien2p** [comment]
@olivermrbl do you want to re review it or should I merge?

**Comment by olivermrbl** [comment]
Depends on what changed? 😄

**Comment by adrien2p** [comment]
> Depends on what changed? 😄 

The entire medusa app loader 🤣 but it is more reorganisation ahah

**Review by carlos-r-l-rodrigues — APPROVED** [review]

**Review by olivermrbl — APPROVED** [review]
LGTM

**Pull request merged**
