### PR TITLE
fix(medusa-js)Issue#2019

### PR DESCRIPTION
**Pull request by sabakhilji**
Use the correct payload type in resetPassword method

### CODE REVIEW

**Comment by olivermrbl** [comment]
@sabakhilji Thanks for your contribution. Please see our contribution guidelines. Changes should be merged to `develop`. I've changed the base branch, but I will need you to rebase off `develop` 👍

**Comment by sabakhilji** [comment]
> @sabakhilji Thanks for your contribution. Please see our contribution guidelines. Changes should be merged to `develop`. I've changed the base branch, but I will need you to rebase off `develop` 👍

Hi @olivermrbl Thanks for the appreciation, I really need this as I am doing it for the first. I will do it today and sorry for the late update I was out of work for the last 2 weeks. Thanks!

**Comment by sabakhilji** [comment]
Hi @olivermrbl. I am not able to find how to rebase off develop. I opened a new [PR](https://github.com/sabakhilji/medusa/pull/2) for this fix and initiated it with develop branch of my fork. Please let me know if that was fine. Thanks!

**Comment by olivermrbl** [comment]
> I opened a new https://github.com/sabakhilji/medusa/pull/2 for this fix and initiated it with develop branch of my for

I believe you've opened this PR to your own forked repo. Can I get you to open it again our `develop` branch>

**Pull request closed without merging**
