### PR TITLE
chore: default isQueryable module

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
Make module default isQueryable from the medusa loader as it is the one that decide to make them defaulted by default

FIXES FRMW-2602

### CODE REVIEW

**Comment by adrien2p** [comment]
@carlos-r-l-rodrigues wdyt as a first step, I have delegated this to the medusa loader layer so that it stays opininated at load time

**Comment by adrien2p** [comment]
Cc @olivermrbl @shahednasser

**Comment by shahednasser** [comment]
@adrien2p so there's no need to pass `isQueryable` once this is merged, correct?

**Comment by carlos-r-l-rodrigues** [comment]
It looks good. If you can `.catch` the `__joinerConfig.?()` too it would be ideal for external modules where the __joinerConfig will exist but the external call can fail. Then we can display the same message.

**Comment by adrien2p** [comment]
> @adrien2p so there's no need to pass `isQueryable` once this is merged, correct?

yes that's correct

**Comment by adrien2p** [comment]
@carlos-r-l-rodrigues like the last commit?

**Comment by olivermrbl** [comment]
This is super nice!

**Pull request merged**
