### PR TITLE
feat(dashboard): SO cart item total rules UI

### PR DESCRIPTION
**Pull request by kasperkristensen**
Resolves CMRC-757

### CODE REVIEW

**Review by fPolic — APPROVED** [review]
LGTM! 🔥

**Review by olivermrbl — APPROVED** [review]

**Comment by olivermrbl** [comment]
@kasperkristensen, should we get this merged?

**Comment by kasperkristensen** [comment]
@olivermrbl this [PR](https://github.com/medusajs/medusa/pull/10382) has changes to the API, so I would like to wait for it to be merged, so I can update this PR

**Comment by riqwan** [comment]
@kasperkristensen API PR is merged! 🤞🏻

**Pull request merged**
