### PR TITLE
chore(orchestrator): remote joiner using entitymap

### PR DESCRIPTION
**Pull request by carlos-r-l-rodrigues**
What:
Entity discovery using the entity map from graphql schema
This enables the same module having multiple links to another module, using the same alias in sub entities.

ex: product.translation, product.variant.translation, product.categories.translation

### CODE REVIEW

**Review by adrien2p — APPROVED** [review]
LGTM, one minor suggestion, can we make the different functions take an object as argument with the optional one being optional. That way it is named and we dont have to provide the undefined explicitly as well. Wdyt?

Later on, it can also be an improvement base where we always pass object with the same shape (property orders) no matter the values and we can benefit from v8 function optimisation in the retrieval path. But we can discuss that later ☺️

**Comment by carlos-r-l-rodrigues** [comment]
> LGTM, one minor suggestion, 

yeah, it's time to overhaul this entire class.

**Comment by adrien2p** [comment]
> > LGTM, one minor suggestion, 
> 
> 
> 
> yeah, it's time to overhaul this entire class.

We will get to that phase 😉

**Comment by carlos-r-l-rodrigues** [comment]
> We will get to that phase 😉

i've changed most function parameters to objects. That will help better organize things in the future.

**Pull request merged**
