### PR TITLE
Issue 2283

### PR DESCRIPTION
**Pull request by Zeesky-code**
* What - Solving PR https://github.com/medusajs/medusa/issues/2283

* Why - The introduction page only covers the Architecture overview. Therefore, it makes sense to just make it an "Architecture Overview" page

* How - Following the guideline in the issue made the changes to medusa/docs/content/usage/configurations.md 

* Testing - No test written because it's a markup file.

### CODE REVIEW

**Review by shahednasser — CHANGES_REQUESTED** [review]
Thanks @Zeesky-code but there are some issues here:

1. The change should be made to the [Introduction](https://docs.medusajs.com/introduction) page, not the homepage.
2. There are changes from another PR. Please create a different branch from the `master` branch

**Comment by Zeesky-code** [comment]
> Thanks @Zeesky-code but there are some issues here:
> 
> 1. The change should be made to the [Introduction](https://docs.medusajs.com/introduction) page, not the homepage.
> 2. There are changes from another PR. Please create a different branch from the `master` branch

Ohh, alright. Sorry for the mistake.

**Comment by Zeesky-code** [comment]
@shahednasser I think the changes have already been added.
image

**Comment by Zeesky-code** [comment]
@shahednasser I think the changes have already been added.

image

**Comment by shahednasser** [comment]
@Zeesky-code basically you need to change the title in the sidebar to be Architecture Overview, change the title in the document at the very top to `Architecture Overview`, and instead of `## Architecture Overview` it should be `# Architecture Overview` and for the headers (Headless Backend, Admin, etc...) they should be H2 headers (so `## Headless Backend` for example).

**Comment by Zeesky-code** [comment]
> @Zeesky-code basically you need to change the title in the sidebar to be Architecture Overview, change the title in the document at the very top to `Architecture Overview`, and instead of `## Architecture Overview` it should be `# Architecture Overview` and for the headers (Headless Backend, Admin, etc...) they should be H2 headers (so `## Headless Backend` for example).

Okay, thank you for the clarification. I'll close this PR and open another one because I created a different branch to work on it.

**Pull request closed without merging**
