### PR TITLE
fix(framework): handle deprecated Dirent path

### LINKED ISSUE #8419: Creating new medusaJs instance V2
### What Medusa version and documentation are you using?

None

### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

Hey Guys, We have been using and testing v1, but given the pace project is getting, company decided to go V2 and implement it for an actual client.
Currently, running this command.
```
npx create-medusa-app@preview
```

Im getting this error
```
An error occurred while preparing project: Error: Command failed: npx medusa user -e admin@medusa-test.com --invite
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at join (node:path:1172:7)
    at /Users/diegoram/dev/minimalart/heb2-backend/node_modules/@medusajs/framework/dist/subscribers/subscriber-loader.js:127:50
    at Array.flatMap (<anonymous>)
    at /Users/diegoram/dev/minimalart/heb2-backend/node_modules/@medusajs/framework/dist/subscribers/subscriber-loader.js:126:32
    at async SubscriberLoader.createMap (/Users/diegoram/dev/minimalart/heb2-backend/node_modules/@medusajs/framework/dist/subscribers/subscriber-loader.js:117:26)
    at async /Users/diegoram/dev/minimalart/heb2-backend/node_modules/@medusajs/framework/dist/subscribers/subscriber-loader.js:184:20
    at async Promise.allSettled (index 0)
    at async promiseAll (/Users/diegoram/dev/minimalart/heb2-backend/node_modules/@medusajs/utils/src/common/promise-all.ts:23:18) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### How can this issue be resolved?

1.NA
2.
3.
...

### Are you interested in working on this issue?

- [X] I would like to fix this issue

### PR DESCRIPTION
**Pull request by carlos-r-l-rodrigues**
What:

- `Dirent` class from `NodeJS` has different properties in different versions, causing issues in our loaders.
- Util `readDirRecursive` was introduced, avoiding old node versions to break

FIXES: https://github.com/medusajs/medusa/issues/8419

### CODE REVIEW

**Review by thetutlage — APPROVED** [review]
Looks good.

Do you think we should have some unit tests for the `readDirRecursive` util?

**Comment by carlos-r-l-rodrigues** [comment]
> Do you think we should have some unit tests for the `readDirRecursive` util?

Just pushed it

**Pull request merged**
