### PR TITLE
feat(medusa): Extend `POST /store/auth` response with shipping + billing address

### PR DESCRIPTION
**Pull request by Hemann55**
Attach previously entered shipping addresses and billing address to the response object in authentication endpoint

link to issue -
https://github.com/medusajs/medusa/issues/2977

### CODE REVIEW

**Comment by olivermrbl** [comment]
Thanks @Hemann55 - this is great. Can I get you to rebase off `develop`?

**Review by shahednasser — APPROVED** [review]

**Comment by olivermrbl** [comment]
@shahednasser Something looks very off with the files in this PR. Do you know what might be the issue 🤔

**Comment by olivermrbl** [comment]
@Hemann55 Please fix tests as well :)

**Comment by shahednasser** [comment]
@olivermrbl It's because of the rebase from `master` to `develop`. Basically all latest commits from the `master` are being pushed into `develop`

**Comment by olivermrbl** [comment]
@shahednasser Yeah, I know, but the files are named in a very strange way no?

**Comment by shahednasser** [comment]
@olivermrbl if you mean files like `postundefined` they're originally like that. It's generated from the split done by Redocly CLI but I'm still not sure what `undefined` stands for. Probably something to look into as part of the OAS project.

**Comment by olivermrbl** [comment]
@shahednasser Ah sorry for sounding the alarm. I saw the `...undefined` and thought it was incorrect 😅

**Comment by shahednasser** [comment]
No worries it makes sense 😄 cc @patrick-medusajs maybe something to consider taking a look at

**Comment by Hemann55** [comment]
> @Hemann55 Please fix tests as well :)

This is my first PR on GitHub. How do I fix the tests? :)

**Comment by patrick-medusajs** [comment]
> No worries it makes sense 😄 cc @patrick-medusajs maybe something to consider taking a look at
@shahednasser, Seems to be a limitation with Redocly. `x-codeSamples.lang` must be lowercase for the lib to infer the file extension.
https://github.com/Redocly/redocly-cli/blob/main/packages/cli/src/commands/split/index.ts#L306-L312
https://github.com/Redocly/redocly-cli/blob/main/packages/cli/src/commands/split/index.ts#L109-L121

**Comment by shahednasser** [comment]
> 
> @shahednasser, Seems to be a limitation with Redocly. `x-codeSamples.lang` must be lowercase for the lib to infer the file extension. https://github.com/Redocly/redocly-cli/blob/main/packages/cli/src/commands/split/index.ts#L306-L312 https://github.com/Redocly/redocly-cli/blob/main/packages/cli/src/commands/split/index.ts#L109-L121

@patrick-medusajs got it! I don't this is a major issue at the moment.

**Comment by patrick-medusajs** [comment]
@Hemann55 I believe that since the shape of the create session response has changed, some tests need to be updated to reflect this change. Look at the details of the failed jobs and search for the word `FAIL`. You should see the test files to fix.
Screen Shot 2023-01-13 at 9 56 25 AM


You can run the test suites on you local computer by running the commands `yarn test` (unit-tests) and `yarn test:integration:api` (integration-tests-api).

**Comment by olivermrbl** [comment]
@Hemann55 Can I get you to open a new PR with base branch `develop`, as it seems this one contains a huge amount of unrelated files? 😊

**Pull request closed without merging**
