### PR TITLE
refactor(medusa): Cleanup product repo and service

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
Follow the discount condition works. cleanup the product repo to use the new repository utils and cleanup the list methods of the product service

FIXES CORE-719

### CODE REVIEW

**Comment by adrien2p** [comment]
@olivermrbl if you could look at this one :) it is not a priority but part of another pr that I did split ahah

**Comment by adrien2p** [comment]
@olivermrbl did you get the time to review that one? So that I can merge then

**Comment by adrien2p** [comment]
@olivermrbl ? 🥹

**Comment by srindom** [comment]
@adrien2p, @olivermrbl - is this still relevant?

**Comment by adrien2p** [comment]
No let's close this one and tackle it another time 👌

**Pull request closed without merging**
