### PR TITLE
hotfix(medusa-js, medusa-react): Fix issue with JS client bundle

### PR DESCRIPTION
**Pull request by kasperkristensen**
**What**
- Remove `form-data` dependency from `@medusajs/medusa`
- Change build tool from `rollup` to `tsup`.
- Rollback version of `axios` to `0.24.0`, as the updated version introduced a bug related to `headers: {
      'Content-Type': 'multipart/form-data'
    }`. Should be fixed in newer versions, but since those version introduces changes to the types, we will rollback the update for now.
- Adds a new type to `@medusajs/medusa-js` for the payload used by `admin.uploads.create` and `admin.uploads.createProtected` as they were incorrect. The new type is `File | File[]` allowing users to upload 1 or more files at a time, which is supported by the API but the JS client would throw a TS error. 
- Adds missing dependency `uuid` to `@medusajs/medusa-js`.

**Why**
Until this PR we have used `import FormData from "form-data"` in our JS client for handling file uploads. The dependency is a node package and should not be used in a browser environment, where the browser native FormData class should be used instead. This has previously not been an issue that caused errors because Axios corrected the mistake for us under the hood. 

This PR changes the use of `rollup` as the build tool of choice to `tsup`, as I was not able to create a working `rollup` config that bundled `axios` correctly.

With the release of `1.3.5` we added the use of `uuid` to the JS client, but it was never installed as a dependency. This usually worked out as it is a common dependency, also included in many metaframeworks. But if the user did not install the dependency themselves this would cause an error, as reported by some users.

### CODE REVIEW

**Review by olivermrbl — APPROVED** [review]
LGTM, great work! Did you test the file upload? 

Also, can we close #3016 in favor of this one?

**Comment by kasperkristensen** [comment]
@olivermrbl Yes tested file upload and it works as expected. And also yes, I've closed the other PR 😄

**Pull request merged**
