### PR TITLE
fix(medusa): products retrieve uses query strategy for performance

### PR DESCRIPTION
**Pull request by riqwan**
What:
- switches relation load strategy from default join to query
- takes up lesser memory
- faster query results and endpoint response time

Why:
- using deep joins and then building objects via typeorm takes a high amount of memory
- querying deeper joins is faster with queries, object building also takes lesser memory before of the extra left join results that the ORM has to work with.

Before and After:
failure
successful

RESOLVES CORE-1355

### CODE REVIEW

**Review by pKorsholm — APPROVED** [review]
lgtm

**Review by olivermrbl — APPROVED** [review]
epic - lgtm!

**Comment by adrien2p** [comment]
LGTM 👌 next thing will be to wait for typeorm answer in order to remove the ternary arround the strategy 🥳

**Review by adrien2p — APPROVED** [review]

**Review by fPolic — APPROVED** [review]
LGTM

**Review by olivermrbl — APPROVED** [review]
Should be good - will merge!

**Pull request merged**
