### PR TITLE
feat(admin-ui): sorted and added the espanol translations

### PR DESCRIPTION
**Pull request by prajjwalkumar17**
##Description

-> Español translation correction and sorting for Admin UI

Resolves: https://github.com/medusajs/medusa/issues/5346

### CODE REVIEW

**Review by VariableVic — APPROVED** [review]
LGTM!

**Comment by prajjwalkumar17** [comment]
Hey @VariableVic can you please add the Hacktoberfest label as don't know why this isn't getting accepted as a hactoberfest PR

**Comment by VariableVic** [comment]
> Hey @VariableVic can you please add the Hacktoberfest label as don't know why this isn't getting accepted as a hactoberfest PR

@prajjwalkumar17 done, let me know if that works! I think it should count as soon as it's merged.

**Comment by prajjwalkumar17** [comment]
> > Hey @VariableVic can you please add the Hacktoberfest label as don't know why this isn't getting accepted as a hactoberfest PR
> 
> @prajjwalkumar17 done, let me know if that works! I think it should count as soon as it's merged.

Not yet I hope it will be done once it gets merged

**Comment by prajjwalkumar17** [comment]
Can you add The Hacktoberfest-accepted label as that insures it getting added to the selected contributions :)

**Comment by olivermrbl** [comment]
We are reworking how translations in admin are handled, so this will not be merged. However, we appreciate the contribution. Keep an eye out for our upcoming releases to know more about this update, and if you are still interested, we'd love to see a new PR then :)

**Pull request closed without merging**
